[setup]
;------------名称
AppTitle      =     中国2联合国之章 
Ename         = zhongguo2lianhe
;------------主EXE路径                 
AppName       =  China2EX.exe
SoftId        = 3838
StarEndPath   =   
RunManner     =0
DiskLikeName  = 
AppProgramArg =   
isReg         = 0  
RUNCommand    =   
LastTime  =2026/6/21 22:06:13 
RunNum        =5
isclose       =0
isDirRun      =0
webName=962
