/*
 * Generated by Ghidra headless decompiler from China2EX_fontfix8.exe.
 * Address request: 0x00405540
 * This is reconstructed pseudocode, not original source.
 */


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void AI_Diplomat(void)

{
  byte bVar1;
  byte *pbVar2;
  short *psVar3;
  char cVar4;
  uint uVar5;
  int iVar6;
  uint uVar7;
  int iVar8;
  int *piVar9;
  undefined4 *puVar10;
  int iVar11;
  int iVar12;
  int local_24;
  short *local_20;
  int local_1c;
  int *local_18;
  int local_14;
  int local_10;
  int local_4;

  Trace_Function(s_AI_Diplomat_0051209c);
  if (DAT_00706838 != '\x01') goto LAB_00405b00;
  local_18 = (int *)0x0;
  local_10 = -1;
  if (_DAT_0074a374 < 1) {
LAB_00405863:
    cVar4 = FUN_0040fdf0();
    if (cVar4 == '\x01') {
      return;
    }
  }
  else {
    local_14 = _DAT_0074a374;
    iVar12 = local_4;
    psVar3 = g_edit_dest_round_buffers[(int)*(short *)(_DAT_00748ff0 + 0x1c) & 1];
    do {
      iVar11 = 0;
      local_24 = (int)psVar3[4] + (int)*(short *)(_DAT_00748ff0 + 0x1a);
      iVar6 = (int)psVar3[5] + (int)*(short *)(_DAT_00748ff0 + 0x1c);
      if (((iVar6 < 0) || (g_map_height_tiles <= iVar6)) ||
         (((local_24 < 0 || (g_map_width_tiles <= local_24)) &&
          (g_current_map_scenario_info.horizontal_wrap_enabled != 1)))) goto LAB_004057da;
      if (local_24 < 0) {
        local_24 = local_24 + g_map_width_tiles;
      }
      if (g_map_width_tiles <= local_24) {
        local_24 = local_24 - g_map_width_tiles;
      }
      if ((g_current_map_scenario_info.scenario_value_2c == 1) && (_DAT_00749a50 != 1)) {
        if ((local_24 < 0x4b) || (((iVar6 < 0x43 || (0x9e < local_24)) || (0xa4 < iVar6)))) {
          if (_DAT_00749a50 == 0) goto switchD_0040565c_switchD;
        }
        else if (_DAT_00749a50 == 2) goto switchD_0040565c_switchD;
      }
      else {
switchD_0040565c_switchD:
        switch(g_map_size_mode) {
        case 0:
          iVar12 = local_24 + iVar6 * 0x138;
          break;
        case 1:
          iVar12 = local_24 + iVar6 * 0x9c;
          break;
        case 2:
          iVar12 = local_24 + iVar6 * 0x4e;
          break;
        case 3:
          iVar12 = iVar6 * 0x27 + local_24;
          break;
        default:
          goto switchD_0040565c_default;
        }
        iVar12 = iVar12 * 0x100 + _g_land_tiles;
switchD_0040565c_default:
        if (*(short *)(iVar12 + 0x10) == *(short *)(DAT_0075597c + 0x10)) {
          if (*(int *)(iVar12 + 0x88) == 0) {
            if ('\0' < *(char *)(iVar12 + 0x50)) {
              local_1c = 0;
              piVar9 = (int *)(iVar12 + 0x28);
              do {
                iVar8 = *piVar9;
                if (((iVar8 != 0) && (*(char *)(iVar8 + 1) != _DAT_00748e34)) &&
                   (*(char *)(iVar8 + 1) != '\0')) {
                  if ((g_active_country->diplomacy_state_by_country[*(char *)(iVar8 + 1)] < 2) ||
                     (5 < g_active_country->diplomacy_state_by_country[*(char *)(iVar8 + 1)])) {
                    iVar11 = 0x82;
                    iVar8 = *(int *)(psVar3 + 6) << 4;
                  }
                  else {
                    iVar11 = 0x3c;
                    iVar8 = *(int *)(psVar3 + 6) << 3;
                  }
                  iVar11 = iVar11 - iVar8;
                  break;
                }
                piVar9 = piVar9 + 1;
                local_1c = local_1c + 1;
              } while (local_1c < 10);
            }
          }
          else {
            cVar4 = *(char *)(*(int *)(iVar12 + 0x88) + 1);
            if ((cVar4 != _DAT_00748e34) && (cVar4 != '\0')) {
              if ((g_active_country->diplomacy_state_by_country[cVar4] < 2) ||
                 (5 < g_active_country->diplomacy_state_by_country[cVar4])) {
                if ((int)*(char *)(iVar12 + 0x7c) + (int)*(char *)(iVar12 + 0x50) == 0) {
                  iVar11 = *(int *)(psVar3 + 6) * -0x100 + 0x1888;
                }
                else {
                  iVar11 = *(int *)(psVar3 + 6) * -0x10 + 0x244;
                }
              }
              else if ((int)*(char *)(iVar12 + 0x7c) + (int)*(char *)(iVar12 + 0x50) == 0) {
                iVar11 = *(int *)(psVar3 + 6) * -0x40 + 0xcf8;
              }
              else {
                iVar11 = *(int *)(psVar3 + 6) * -8 + 0x154;
              }
            }
          }
        }
      }
LAB_004057da:
      if ((int)local_18 < iVar11) {
        local_18 = (int *)iVar11;
        local_10 = local_24;
        local_4 = iVar6;
      }
      local_14 = local_14 + -1;
      psVar3 = psVar3 + 4;
    } while (local_14 != 0);
    if (local_10 < 0) goto LAB_00405863;
    *(short *)(_DAT_00748ff0 + 0x22) = (short)local_10;
    *(undefined2 *)(_DAT_00748ff0 + 0x24) = (undefined2)local_4;
    FUN_004d2cc0(_DAT_00748ff0);
    if ('\0' < *(char *)(_DAT_00748ff0 + 0x120)) {
      FUN_004b0130(_DAT_00748ff0,0x24,1,0xffffffff,0xffffffff,0,0xffffffff,0xffffffff);
      return;
    }
  }
  if (DAT_0074c858 != 0) {
    iVar12 = 0;
    puVar10 = (undefined4 *)(DAT_0075597c + 0x28);
    do {
      pbVar2 = (byte *)*puVar10;
      if ((pbVar2 != (byte *)0x0) && (pbVar2[0x127] == 0)) {
        bVar1 = *pbVar2;
        if (((0 < g_army_type_table[bVar1].transport_capacity) && (pbVar2[0x152] == 0)) &&
           ((((g_army_type_table[bVar1].unit_class == 1 && (*(char *)(DAT_0074c858 + 0xbe) != '\0'))
             || (g_army_type_table[bVar1].unit_class == 2)) &&
            (((g_army_type_table[bVar1].air_or_city_capability_mask &
              *(uint *)(_DAT_0074a0b8 + 0x144)) != 0 &&
             ((int)(*(byte *)(_DAT_00748ff0 + 0x148) + 1 + (uint)pbVar2[0x148]) <=
              g_army_type_table[bVar1].transport_capacity)))))) {
          if (-1 < iVar12) {
            FUN_004b0130(_DAT_00748ff0,0x4e,0x51,0xffffffff,0xffffffff,
                         *(undefined4 *)(DAT_0075597c + 0x28 + iVar12 * 4),0xffffffff,0xffffffff);
            FUN_004b0130(*(undefined4 *)(DAT_0075597c + 0x28 + iVar12 * 4),0x43,0x52,0xffffffff,
                         0xffffffff,0,0xffffffff,0xffffffff);
            return;
          }
          break;
        }
      }
      iVar12 = iVar12 + 1;
      puVar10 = puVar10 + 1;
    } while (iVar12 < 10);
  }
  local_10 = g_map_width_tiles + g_map_height_tiles;
  iVar11 = 0;
  iVar12 = -0x74a038;
  local_14 = 0;
  local_20 = (short *)&DAT_007360ca;
  local_18 = (int *)&DAT_0074a1e8;
  iVar6 = _g_land_tiles;
  do {
    if ((0 < *(int *)((int)(local_18 + -0x1d280e) + (int)g_active_country)) && (*local_20 != 0)) {
      for (iVar8 = *local_18; iVar8 != 0; iVar8 = *(int *)(iVar8 + 0x1b4)) {
        uVar7 = (uint)*(ushort *)(iVar8 + 0x16);
        uVar5 = (uint)*(ushort *)(iVar8 + 0x18);
        switch(g_map_size_mode) {
        case 0:
          iVar12 = uVar7 + uVar5 * 0x138;
          break;
        case 1:
          iVar12 = uVar7 + uVar5 * 0x9c;
          break;
        case 2:
          iVar12 = uVar7 + uVar5 * 0x4e;
          break;
        case 3:
          iVar12 = uVar5 * 0x27 + uVar7;
          break;
        default:
          goto switchD_00405998_default;
        }
        iVar12 = iVar12 * 0x100 + iVar6;
switchD_00405998_default:
        if ((*(short *)(iVar12 + 0x10) == *(short *)(DAT_0075597c + 0x10)) &&
           (iVar11 = FUN_004c6ed0((int)*(short *)(_DAT_00748ff0 + 0x1a),
                                  (int)*(short *)(_DAT_00748ff0 + 0x1c),uVar7,uVar5,0),
           iVar6 = _g_land_tiles, iVar11 < local_10)) {
          local_14 = iVar8;
          local_10 = iVar11;
        }
        iVar11 = local_14;
      }
    }
    local_18 = local_18 + 1;
    local_20 = local_20 + 0x734;
  } while ((int)local_18 < 0x74a23c);
  if (iVar11 != 0) {
    *(undefined2 *)(_DAT_00748ff0 + 0x22) = *(undefined2 *)(iVar11 + 0x16);
    *(undefined2 *)(_DAT_00748ff0 + 0x24) = *(undefined2 *)(iVar11 + 0x18);
    FUN_004d2cc0(_DAT_00748ff0);
    if ('\0' < *(char *)(_DAT_00748ff0 + 0x120)) {
      FUN_004b0130(_DAT_00748ff0,0x24,1,0xffffffff,0xffffffff,0,0xffffffff,0xffffffff);
      return;
    }
  }
LAB_00405b00:
  if ((0 < *(int *)(_DAT_0074a0b8 + 0x90)) && (_DAT_00748ff0 != DAT_007584dc)) {
    FUN_004b0130(_DAT_00748ff0,6,0x3f,0xffffffff,0xffffffff,0,0xffffffff,0xffffffff);
  }
  if (DAT_00706838 == '\x01') {
    DAT_0070684c = 1;
  }
  return;
}
