/*
 * Generated by Ghidra headless decompiler from China2EX_fontfix8.exe.
 * Address request: 0x00405540
 * This is reconstructed pseudocode, not original source.
 */


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void AI_Diplomat(void)

{
  byte bVar1;
  byte *pbVar2;
  short *psVar3;
  char cVar4;
  uint to_y;
  int iVar5;
  uint to_x;
  int iVar6;
  int *piVar7;
  undefined4 *puVar8;
  int iVar9;
  int iVar10;
  int local_24;
  short *local_20;
  int local_1c;
  int *local_18;
  int local_14;
  int local_10;
  int local_4;

  Trace_Function(s_AI_Diplomat_0051209c);
  if (DAT_00706838 != '\x01') goto LAB_00405b00;
  local_18 = (int *)0x0;
  local_10 = -1;
  if (_DAT_0074a374 < 1) {
LAB_00405863:
    cVar4 = FUN_0040fdf0();
    if (cVar4 == '\x01') {
      return;
    }
  }
  else {
    local_14 = _DAT_0074a374;
    iVar10 = local_4;
    psVar3 = g_edit_dest_round_buffers[(int)_DAT_00748ff0->tile_y & 1];
    do {
      iVar9 = 0;
      local_24 = (int)psVar3[4] + (int)_DAT_00748ff0->tile_x;
      iVar5 = (int)psVar3[5] + (int)_DAT_00748ff0->tile_y;
      if (((iVar5 < 0) || (g_map_height_tiles <= iVar5)) ||
         (((local_24 < 0 || (g_map_width_tiles <= local_24)) &&
          (g_current_map_scenario_info.horizontal_wrap_setting != 1)))) goto LAB_004057da;
      if (local_24 < 0) {
        local_24 = local_24 + g_map_width_tiles;
      }
      if (g_map_width_tiles <= local_24) {
        local_24 = local_24 - g_map_width_tiles;
      }
      if ((g_current_map_scenario_info.gameplay_mode == 1) && (_DAT_00749a50 != 1)) {
        if ((local_24 < 0x4b) || (((iVar5 < 0x43 || (0x9e < local_24)) || (0xa4 < iVar5)))) {
          if (_DAT_00749a50 == 0) goto switchD_0040565c_switchD;
        }
        else if (_DAT_00749a50 == 2) goto switchD_0040565c_switchD;
      }
      else {
switchD_0040565c_switchD:
        switch(g_map_size_mode) {
        case 0:
          iVar10 = local_24 + iVar5 * 0x138;
          break;
        case 1:
          iVar10 = local_24 + iVar5 * 0x9c;
          break;
        case 2:
          iVar10 = local_24 + iVar5 * 0x4e;
          break;
        case 3:
          iVar10 = iVar5 * 0x27 + local_24;
          break;
        default:
          goto switchD_0040565c_default;
        }
        iVar10 = iVar10 * 0x100 + _g_land_tiles;
switchD_0040565c_default:
        if (*(short *)(iVar10 + 0x10) == *(short *)(DAT_0075597c + 0x10)) {
          if (*(int *)(iVar10 + 0x88) == 0) {
            if ('\0' < *(char *)(iVar10 + 0x50)) {
              local_1c = 0;
              piVar7 = (int *)(iVar10 + 0x28);
              do {
                iVar6 = *piVar7;
                if (((iVar6 != 0) && (*(char *)(iVar6 + 1) != _DAT_00748e34)) &&
                   (*(char *)(iVar6 + 1) != '\0')) {
                  if ((g_active_country->diplomacy_state_by_country[*(char *)(iVar6 + 1)] < 2) ||
                     (5 < g_active_country->diplomacy_state_by_country[*(char *)(iVar6 + 1)])) {
                    iVar9 = 0x82;
                    iVar6 = *(int *)(psVar3 + 6) << 4;
                  }
                  else {
                    iVar9 = 0x3c;
                    iVar6 = *(int *)(psVar3 + 6) << 3;
                  }
                  iVar9 = iVar9 - iVar6;
                  break;
                }
                piVar7 = piVar7 + 1;
                local_1c = local_1c + 1;
              } while (local_1c < 10);
            }
          }
          else {
            cVar4 = *(char *)(*(int *)(iVar10 + 0x88) + 1);
            if ((cVar4 != _DAT_00748e34) && (cVar4 != '\0')) {
              if ((g_active_country->diplomacy_state_by_country[cVar4] < 2) ||
                 (5 < g_active_country->diplomacy_state_by_country[cVar4])) {
                if ((int)*(char *)(iVar10 + 0x7c) + (int)*(char *)(iVar10 + 0x50) == 0) {
                  iVar9 = *(int *)(psVar3 + 6) * -0x100 + 0x1888;
                }
                else {
                  iVar9 = *(int *)(psVar3 + 6) * -0x10 + 0x244;
                }
              }
              else if ((int)*(char *)(iVar10 + 0x7c) + (int)*(char *)(iVar10 + 0x50) == 0) {
                iVar9 = *(int *)(psVar3 + 6) * -0x40 + 0xcf8;
              }
              else {
                iVar9 = *(int *)(psVar3 + 6) * -8 + 0x154;
              }
            }
          }
        }
      }
LAB_004057da:
      if ((int)local_18 < iVar9) {
        local_18 = (int *)iVar9;
        local_10 = local_24;
        local_4 = iVar5;
      }
      local_14 = local_14 + -1;
      psVar3 = psVar3 + 4;
    } while (local_14 != 0);
    if (local_10 < 0) goto LAB_00405863;
    _DAT_00748ff0->target_tile_x_or_anim_x = (short)local_10;
    _DAT_00748ff0->target_tile_y_or_anim_y = (short)local_4;
    TestRoad(_DAT_00748ff0);
    if ('\0' < (char)_DAT_00748ff0->active_anim_step_count) {
      Add_OrderQueue_Army(_DAT_00748ff0,0x24,1,-1,-1,(ArmyUnit_0x164_plus *)0x0,-1,-1);
      return;
    }
  }
  if (DAT_0074c858 != 0) {
    iVar10 = 0;
    puVar8 = (undefined4 *)(DAT_0075597c + 0x28);
    do {
      pbVar2 = (byte *)*puVar8;
      if ((pbVar2 != (byte *)0x0) && (pbVar2[0x127] == 0)) {
        bVar1 = *pbVar2;
        if (((0 < g_army_type_table[bVar1].transport_capacity) && (pbVar2[0x152] == 0)) &&
           ((((g_army_type_table[bVar1].unit_class == 1 && (*(char *)(DAT_0074c858 + 0xbe) != '\0'))
             || (g_army_type_table[bVar1].unit_class == 2)) &&
            (((g_army_type_table[bVar1].air_or_city_capability_mask &
              g_active_army_type_def->transportable_mask) != 0 &&
             ((int)(_DAT_00748ff0->cargo_or_subunit_count + 1 + (uint)pbVar2[0x148]) <=
              g_army_type_table[bVar1].transport_capacity)))))) {
          if (-1 < iVar10) {
            Add_OrderQueue_Army(_DAT_00748ff0,0x4e,0x51,-1,-1,
                                *(ArmyUnit_0x164_plus **)(DAT_0075597c + 0x28 + iVar10 * 4),-1,-1);
            Add_OrderQueue_Army(*(ArmyUnit_0x164_plus **)(DAT_0075597c + 0x28 + iVar10 * 4),0x43,
                                0x52,-1,-1,(ArmyUnit_0x164_plus *)0x0,-1,-1);
            return;
          }
          break;
        }
      }
      iVar10 = iVar10 + 1;
      puVar8 = puVar8 + 1;
    } while (iVar10 < 10);
  }
  local_10 = g_map_width_tiles + g_map_height_tiles;
  iVar9 = 0;
  iVar10 = -0x74a038;
  local_14 = 0;
  local_20 = (short *)&DAT_007360ca;
  local_18 = (int *)&DAT_0074a1e8;
  iVar5 = _g_land_tiles;
  do {
    if ((0 < *(int *)((int)(local_18 + -0x1d280e) + (int)g_active_country)) && (*local_20 != 0)) {
      for (iVar6 = *local_18; iVar6 != 0; iVar6 = *(int *)(iVar6 + 0x1b4)) {
        to_x = (uint)*(ushort *)(iVar6 + 0x16);
        to_y = (uint)*(ushort *)(iVar6 + 0x18);
        switch(g_map_size_mode) {
        case 0:
          iVar10 = to_x + to_y * 0x138;
          break;
        case 1:
          iVar10 = to_x + to_y * 0x9c;
          break;
        case 2:
          iVar10 = to_x + to_y * 0x4e;
          break;
        case 3:
          iVar10 = to_y * 0x27 + to_x;
          break;
        default:
          goto switchD_00405998_default;
        }
        iVar10 = iVar10 * 0x100 + iVar5;
switchD_00405998_default:
        if ((*(short *)(iVar10 + 0x10) == *(short *)(DAT_0075597c + 0x10)) &&
           (iVar9 = Tile_Distance_With_Wrap
                              ((int)_DAT_00748ff0->tile_x,(int)_DAT_00748ff0->tile_y,to_x,to_y,
                               (byte *)0x0), iVar5 = _g_land_tiles, iVar9 < local_10)) {
          local_14 = iVar6;
          local_10 = iVar9;
        }
        iVar9 = local_14;
      }
    }
    local_18 = local_18 + 1;
    local_20 = local_20 + 0x734;
  } while ((int)local_18 < 0x74a23c);
  if (iVar9 != 0) {
    _DAT_00748ff0->target_tile_x_or_anim_x = *(short *)(iVar9 + 0x16);
    _DAT_00748ff0->target_tile_y_or_anim_y = *(short *)(iVar9 + 0x18);
    TestRoad(_DAT_00748ff0);
    if ('\0' < (char)_DAT_00748ff0->active_anim_step_count) {
      Add_OrderQueue_Army(_DAT_00748ff0,0x24,1,-1,-1,(ArmyUnit_0x164_plus *)0x0,-1,-1);
      return;
    }
  }
LAB_00405b00:
  if ((0 < g_active_army_type_def->special_mission_range_limit) && (_DAT_00748ff0 != DAT_007584dc))
  {
    Add_OrderQueue_Army(_DAT_00748ff0,6,0x3f,-1,-1,(ArmyUnit_0x164_plus *)0x0,-1,-1);
  }
  if (DAT_00706838 == '\x01') {
    DAT_0070684c = 1;
  }
  return;
}
