/*
 * Generated by Ghidra headless decompiler from China2EX_fontfix8.exe.
 * Address request: 0x0048c8f0
 * This is reconstructed pseudocode, not original source.
 */


void CheckMouseOnWindow(void)

{
  char cVar1;
  int *piVar2;
  int *piVar3;
  uint uVar4;
  char *pcVar5;
  int local_4;
  
  Trace_Function(s_CheckMouseOnWindow_0057daec);
  piVar3 = DAT_00758528;
  do {
    piVar2 = DAT_00758530;
    if ((piVar3 == (int *)0x0) || (piVar3 == (int *)&DAT_005c1d08)) break;
    if (piVar3[2] == 1) {
      if ((((piVar3[3] == 1) && (piVar3[8] <= g_view_center_y)) &&
          (g_view_center_y <= piVar3[10] + piVar3[8])) &&
         ((piVar3[7] <= g_view_center_x &&
          (piVar2 = piVar3, g_view_center_x <= piVar3[9] + piVar3[7])))) break;
      if (piVar3[0x21] != 0) {
        DAT_00758530 = (int *)0x0;
        goto LAB_0048c9c9;
      }
    }
    piVar3 = (int *)piVar3[0x30];
  } while( true );
  DAT_00758530 = piVar2;
  if (DAT_00758530 == (int *)0x0) {
LAB_0048c9c9:
    if ((g_editor_mode_enabled == 0) || (g_map_interaction_mode != 99)) {
      DAT_00512af0 = 0xffffffff;
      return;
    }
    if ((g_view_center_x == DAT_0057dacc) && (g_view_center_y == DAT_00714e64)) {
      if (DAT_00714e7c == 0) {
        DAT_00714e7c = g_frame_tick;
        return;
      }
      if ((uint)(g_frame_tick - DAT_00714e7c) < 300) {
        return;
      }
      DAT_00714e80 = 1;
      return;
    }
    DAT_0057dacc = g_view_center_x;
    DAT_00714e64 = g_view_center_y;
    DAT_00714e80 = 0;
    DAT_00714e7c = 0;
    return;
  }
  if ((DAT_0075853c != 0) && (*(int **)(DAT_0075853c + 0x5c) != DAT_00758530)) {
    DAT_0075853c = 0;
  }
  if ((g_view_center_x == DAT_0057dacc) && (g_view_center_y == DAT_00714e64)) {
    if (DAT_00714e7c == 0) {
      DAT_00714e7c = g_frame_tick;
    }
    else if ((DAT_00512af0 == -1) && (299 < (uint)(g_frame_tick - DAT_00714e7c))) {
      local_4 = 0;
      piVar3 = &DAT_00512b00;
      do {
        if ((*DAT_00758530 == piVar3[-2]) && (0 < piVar3[1])) {
          if ((*piVar3 + DAT_00758530[8] <= g_view_center_y) &&
             (g_view_center_y <= piVar3[2] + *piVar3 + DAT_00758530[8])) {
            if ((piVar3[-1] + DAT_00758530[7] <= g_view_center_x) &&
               (g_view_center_x <= piVar3[1] + piVar3[-1] + DAT_00758530[7])) {
              uVar4 = 0xffffffff;
              DAT_00512af0 = local_4;
              pcVar5 = (&PTR_DAT_00512b0c)[local_4 * 6];
              goto code_r0x0048cab7;
            }
          }
        }
        piVar3 = piVar3 + 6;
        local_4 = local_4 + 1;
      } while ((int)piVar3 < 0x512c38);
    }
  }
  else {
    DAT_0057dacc = g_view_center_x;
    DAT_00714e64 = g_view_center_y;
    DAT_00714e7c = 0;
    DAT_00512af0 = -1;
  }
  goto LAB_0048cae0;
  while( true ) {
    uVar4 = uVar4 - 1;
    cVar1 = *pcVar5;
    pcVar5 = pcVar5 + 1;
    if (cVar1 == '\0') break;
code_r0x0048cab7:
    if (uVar4 == 0) break;
  }
  DAT_005d91d0 = ~uVar4 - 1;
LAB_0048cae0:
  if (g_map_interaction_mode != 5) {
    DAT_00755920 = 0;
  }
  if (DAT_00758530[0x23] == 0) {
    return;
  }
  DAT_00714e58 = DAT_00758530[7];
  DAT_00714e5c = DAT_00758530[8];
  (*(code *)DAT_00758530[0x23])();
  return;
}

