/*
 * Generated by Ghidra headless decompiler from China2EX_fontfix8.exe.
 * Address request: 0x00431800
 * This is reconstructed pseudocode, not original source.
 */


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void Decode_NewMap(int param_1,uint param_2)

{
  int iVar1;
  bool bVar2;
  bool bVar3;
  char cVar4;
  char cVar5;
  char cVar6;
  short sVar7;
  int iVar8;
  char *pcVar9;
  int iVar10;
  int *piVar11;
  char *pcVar12;
  int iVar13;
  uint uVar14;
  int local_108;
  undefined4 local_104;
  undefined4 local_100;
  int local_fc;
  int local_f8;
  int local_f4;
  int local_f0;
  int local_ec;
  int local_e8;
  int local_e4;
  int local_e0;
  int local_dc;
  int local_d8;
  int local_d4;
  int local_d0;
  int local_cc;
  int local_c8;
  char *local_c4;
  int local_c0;
  int local_bc;
  int local_b8;
  int local_b4;
  int local_b0;
  int local_ac;
  int local_a8;
  int local_a4;
  undefined4 local_a0;
  char *local_9c;
  char *local_98;
  char *local_94;
  char *local_90;
  char *local_8c;
  char *local_88;
  char *local_84;
  undefined4 local_80;
  undefined4 local_7c;
  undefined4 local_78;
  undefined4 local_74;
  undefined4 local_70;
  undefined4 local_6c;
  undefined4 local_68;
  int local_64;
  int local_60;
  int local_5c;
  int local_58;
  int local_54;
  int local_50;
  int local_4c;
  int local_48;
  int local_44;
  int local_40 [16];
  
  Trace_Function(s_Decode_NewMap_005188b0);
  if ((int)param_2 < 0) {
    return;
  }
  if (g_map_height_tiles <= (int)param_2) {
    return;
  }
  if (((param_1 < 0) || (g_map_width_tiles <= param_1)) && (DAT_0074c7dc != 1)) {
    return;
  }
  if (param_1 < 0) {
    param_1 = param_1 + g_map_width_tiles;
  }
  if (g_map_width_tiles <= param_1) {
    param_1 = param_1 - g_map_width_tiles;
  }
  local_a8 = FUN_004c6e90(param_1,param_2);
  local_a4 = FUN_004c6eb0(param_1,param_2);
  switch(g_map_size_mode) {
  case 0:
    local_bc = param_1 + param_2 * 0x138;
    break;
  case 1:
    local_bc = param_1 + param_2 * 0x9c;
    break;
  case 2:
    local_bc = param_1 + param_2 * 0x4e;
    break;
  case 3:
    local_bc = param_2 * 0x27 + param_1;
  }
  pcVar12 = (char *)(local_bc * 0x100 + _g_land_tiles);
  local_e0 = *(int *)(DAT_007584d0 + local_bc * 4);
  local_c4 = (char *)(param_2 & 1);
  iVar10 = 0;
  local_e4 = *(int *)(DAT_007584d4 + local_bc * 4);
  local_b8 = -1;
  local_4c = -1;
  local_b4 = -1;
  local_44 = -1;
  local_c0 = -1;
  local_64 = -1;
  local_b0 = -1;
  local_60 = -1;
  local_108 = -1;
  local_ac = -1;
  local_d4 = -1;
  local_cc = -1;
  local_d0 = -1;
  local_dc = -1;
  local_c8 = -1;
  local_d8 = -1;
  iVar13 = (int)(param_2 & 1) * 0x20;
  do {
    iVar8 = *(int *)((int)&DAT_00589374 + iVar10 + iVar13) + param_1;
    iVar1 = *(int *)((int)&DAT_005893b4 + iVar10 + iVar13);
    *(int *)((int)&local_104 + iVar10) = iVar8;
    iVar1 = iVar1 + param_2;
    *(int *)((int)local_40 + iVar10) = iVar1;
    if (((iVar1 < 0) || (g_map_height_tiles <= iVar1)) ||
       (((iVar8 < 0 || (g_map_width_tiles <= iVar8)) && (DAT_0074c7dc != 1)))) {
      *(undefined4 *)((int)&local_a0 + iVar10) = 0;
    }
    else {
      if (iVar8 < 0) {
        *(int *)((int)&local_104 + iVar10) = iVar8 + g_map_width_tiles;
      }
      if (g_map_width_tiles <= *(int *)((int)&local_104 + iVar10)) {
        *(int *)((int)&local_104 + iVar10) = *(int *)((int)&local_104 + iVar10) - g_map_width_tiles;
      }
      switch(g_map_size_mode) {
      case 0:
        iVar8 = *(int *)((int)&local_104 + iVar10) + iVar1 * 0x138;
        break;
      case 1:
        iVar8 = *(int *)((int)&local_104 + iVar10) + iVar1 * 0x9c;
        break;
      case 2:
        iVar8 = *(int *)((int)&local_104 + iVar10) + iVar1 * 0x4e;
        break;
      case 3:
        iVar8 = iVar1 * 0x27 + *(int *)((int)&local_104 + iVar10);
        break;
      default:
        goto switchD_004319e1_default;
      }
      *(int *)((int)&local_a0 + iVar10) = iVar8 * 0x100 + _g_land_tiles;
    }
switchD_004319e1_default:
    iVar10 = iVar10 + 4;
  } while (iVar10 < 0x20);
  if (local_9c != (char *)0x0) {
    local_b8 = (int)*local_9c;
    local_4c = (int)local_9c[8];
  }
  if (local_94 != (char *)0x0) {
    local_b4 = (int)*local_94;
    local_44 = (int)local_94[8];
  }
  if (local_84 != (char *)0x0) {
    local_c0 = (int)*local_84;
    local_64 = (int)local_84[8];
  }
  if (local_8c != (char *)0x0) {
    local_b0 = (int)*local_8c;
    local_60 = (int)local_8c[8];
  }
  if (local_98 != (char *)0x0) {
    local_108 = (int)*local_98;
    local_ac = (int)local_98[8];
  }
  if (local_a0 != (char *)0x0) {
    local_d4 = (int)*local_a0;
    local_cc = (int)local_a0[8];
  }
  if (local_90 != (char *)0x0) {
    local_d0 = (int)*local_90;
    local_dc = (int)local_90[8];
  }
  if (local_88 != (char *)0x0) {
    local_c8 = (int)*local_88;
    local_d8 = (int)local_88[8];
  }
  cVar5 = *pcVar12;
  iVar10 = (int)cVar5;
  if ((0x13b1 < *(short *)(pcVar12 + 4)) && (*(short *)(pcVar12 + 4) < 0x1403))
  goto switchD_00431b84_default;
  iVar13 = 0;
  piVar11 = &local_a0;
  do {
    if (((*piVar11 != 0) && (sVar7 = *(short *)(*piVar11 + 4), 0x13b1 < sVar7)) && (sVar7 < 0x1403))
    goto switchD_00431b84_default;
    iVar13 = iVar13 + 1;
    piVar11 = piVar11 + 1;
  } while (iVar13 < 8);
  switch(iVar10) {
  case 0:
  case 1:
  case 2:
  case 3:
  case 4:
  case 5:
  case 6:
  case 7:
  case 8:
  case 9:
  case 10:
    local_40[0] = 5;
    local_40[2] = 5;
    local_40[3] = 5;
    local_40[4] = 5;
    local_40[5] = 5;
    local_40[6] = 5;
    local_40[7] = 5;
    local_40[8] = 5;
    local_40[9] = 5;
    local_40[10] = 5;
    local_40[0xb] = 5;
    local_40[0xc] = 5;
    local_40[0xd] = 5;
    local_a0 = (char *)0x48;
    local_9c = (char *)0x0;
    local_98 = (char *)0x6;
    local_94 = (char *)0xb;
    local_90 = (char *)0x10;
    local_8c = (char *)0x15;
    local_88 = (char *)0x1a;
    local_84 = (char *)0x1f;
    local_80 = 0x24;
    local_7c = 0x29;
    local_78 = 0x2e;
    local_74 = 0x33;
    local_70 = 0x38;
    local_6c = 0x3d;
    local_68 = 0x42;
    local_40[1] = 6;
    local_40[0xe] = 6;
    uVar14 = (uint)(iVar10 == local_108);
    if (iVar10 == local_d0) {
      uVar14 = uVar14 + 2;
    }
    if (iVar10 == local_c8) {
      uVar14 = uVar14 + 4;
    }
    if (iVar10 == local_d4) {
      uVar14 = uVar14 + 8;
    }
    if ((iVar10 == 0) || (uVar14 == 0xf)) {
      *(short *)(pcVar12 + 4) = ((short)(local_a4 % 9) + cVar5 * 9) * 9 + (short)(local_a8 % 9);
    }
    else {
      sVar7 = FUN_004fbf50(CONCAT22((short)((uint)piVar11 >> 0x10),(short)local_40[uVar14]));
      *(short *)(pcVar12 + 4) =
           sVar7 + *(short *)(&local_a0 + uVar14) + 0x32e + cVar5 * 0x50 + cVar5 * -3;
    }
    *(undefined4 *)(DAT_007584c4 + local_e0 * 4) = (&DAT_00734c84)[iVar10];
    *(undefined4 *)(DAT_007584c8 + local_e4 * 4) = (&DAT_00734c84)[iVar10];
    pcVar12[0x12] = '\0';
    break;
  case 0xb:
  case 0xc:
  case 0xd:
  case 0xe:
    iVar13 = 0;
    pcVar12[0x16] = -1;
    pcVar12[4] = -1;
    pcVar12[5] = -1;
    *(ushort *)(pcVar12 + 6) = (byte)pcVar12[3] + 0xeb1d + cVar5 * 0x288;
    bVar2 = false;
    bVar3 = false;
    local_fc = 0;
    local_f8 = 0;
    if ((-1 < local_108) && (local_108 < 0xb)) {
      iVar13 = 1;
      bVar2 = true;
      bVar3 = true;
    }
    if ((-1 < local_d0) && (local_d0 < 0xb)) {
      iVar13 = iVar13 + 2;
      bVar3 = true;
      local_fc = 1;
    }
    if ((-1 < local_c8) && (local_c8 < 0xb)) {
      iVar13 = iVar13 + 4;
      local_fc = 1;
      local_f8 = 1;
    }
    if ((-1 < local_d4) && (local_d4 < 0xb)) {
      iVar13 = iVar13 + 8;
      bVar2 = true;
      local_f8 = 1;
    }
    iVar8 = 0;
    if (((-1 < local_b8) && (local_b8 < 0xb)) && (!bVar2)) {
      iVar8 = 1;
    }
    if (((-1 < local_b4) && (local_b4 < 0xb)) && (!bVar3)) {
      iVar8 = iVar8 + 2;
    }
    if (((-1 < local_b0) && (local_b0 < 0xb)) && (local_fc == 0)) {
      iVar8 = iVar8 + 4;
    }
    if (((-1 < local_c0) && (local_c0 < 0xb)) && (local_f8 == 0)) {
      iVar8 = iVar8 + 8;
    }
    if (iVar13 == 0) {
LAB_00432121:
      if ((iVar13 == 0) && (iVar8 != 0)) {
        local_104 = 0;
        local_a0 = (char *)0x20000;
        local_9c = (char *)0x10002;
        local_98 = (char *)0x10002;
        local_94 = (char *)0x10001;
        local_90 = (char *)0x10002;
        local_8c = (char *)0x10001;
        local_88 = (char *)0x10001;
        local_84 = (char *)0x10001;
        local_100 = 0x40002;
        local_fc = 0x70005;
        local_f8 = 0x90008;
        local_f4 = 0xc000a;
        local_f0 = 0xe000d;
        local_ec = 0x10000f;
        local_e8 = 0x120011;
        sVar7 = FUN_004fbf50(*(undefined2 *)((int)&local_a0 + iVar8 * 2));
        sVar7 = sVar7 + *(short *)((int)&local_104 + iVar8 * 2) + 0x1169;
        goto LAB_00432231;
      }
    }
    else {
      if (iVar8 == 0) {
        local_a0 = (char *)0x0;
        local_104 = 0x50000;
        local_100 = 0x40005;
        local_fc = 0x50005;
        local_f8 = 0x20004;
        local_f4 = 0x40005;
        local_f0 = 0x20005;
        local_ec = 0x20004;
        local_e8 = 0x20002;
        local_9c = (char *)0xa0005;
        local_98 = (char *)0x13000e;
        local_94 = (char *)0x1c0018;
        local_90 = (char *)0x23001e;
        local_8c = (char *)0x2c0027;
        local_88 = (char *)0x32002e;
        local_84 = (char *)0x360034;
        sVar7 = FUN_004fbf50(*(undefined2 *)((int)&local_104 + iVar13 * 2));
        sVar7 = sVar7 + *(short *)((int)&local_a0 + iVar13 * 2) + 0x1115;
      }
      else {
        if (iVar8 == 0) goto LAB_00432121;
        if (iVar13 == 1) {
          if (iVar8 == 8) {
            sVar7 = FUN_004fbf50(2);
            sVar7 = sVar7 + 0x114d;
          }
          else {
            if (iVar8 != 4) {
              if (iVar8 == 0xc) {
                pcVar12[4] = '|';
                pcVar12[5] = '\x11';
              }
              goto LAB_00432235;
            }
            sVar7 = FUN_004fbf50(2);
            sVar7 = sVar7 + 0x114f;
          }
        }
        else if (iVar13 == 2) {
          if (iVar8 == 8) {
            sVar7 = FUN_004fbf50(2);
            sVar7 = sVar7 + 0x1151;
          }
          else {
            if (iVar8 != 1) {
              if (iVar8 == 9) {
                pcVar12[4] = '}';
                pcVar12[5] = '\x11';
              }
              goto LAB_00432235;
            }
            sVar7 = FUN_004fbf50(2);
            sVar7 = sVar7 + 0x1153;
          }
        }
        else if (iVar13 == 3) {
          if (iVar8 != 8) goto LAB_00432235;
          sVar7 = FUN_004fbf50(3);
          sVar7 = sVar7 + 0x1155;
        }
        else if (iVar13 == 4) {
          if (iVar8 == 1) {
            sVar7 = FUN_004fbf50(2);
            sVar7 = sVar7 + 0x1158;
          }
          else {
            if (iVar8 != 2) {
              if (iVar8 == 3) {
                pcVar12[4] = '~';
                pcVar12[5] = '\x11';
              }
              goto LAB_00432235;
            }
            sVar7 = FUN_004fbf50(2);
            sVar7 = sVar7 + 0x115a;
          }
        }
        else if (iVar13 == 6) {
          if (iVar8 != 1) goto LAB_00432235;
          sVar7 = FUN_004fbf50(3);
          sVar7 = sVar7 + 0x115c;
        }
        else {
          if (iVar13 != 8) {
            if (iVar13 == 9) {
              if (iVar8 == 4) {
                sVar7 = FUN_004fbf50(3);
                sVar7 = sVar7 + 0x1163;
                goto LAB_00432231;
              }
            }
            else if ((iVar13 == 0xc) && (iVar8 == 2)) {
              sVar7 = FUN_004fbf50(3);
              sVar7 = sVar7 + 0x1166;
              goto LAB_00432231;
            }
            goto LAB_00432235;
          }
          if (iVar8 == 2) {
            sVar7 = FUN_004fbf50(2);
            sVar7 = sVar7 + 0x115f;
          }
          else {
            if (iVar8 != 4) {
              if (iVar8 == 6) {
                pcVar12[4] = '\x7f';
                pcVar12[5] = '\x11';
              }
              goto LAB_00432235;
            }
            sVar7 = FUN_004fbf50(2);
            sVar7 = sVar7 + 0x1161;
          }
        }
      }
LAB_00432231:
      *(short *)(pcVar12 + 4) = sVar7;
    }
LAB_00432235:
    *(undefined4 *)(DAT_007584c4 + local_e0 * 4) = (&DAT_00734c84)[iVar10];
    *(undefined4 *)(DAT_007584c8 + local_e4 * 4) = (&DAT_00734c84)[iVar10];
  }
switchD_00431b84_default:
  if (-1 < pcVar12[0x13]) {
    local_100 = 1;
    local_fc = 1;
    local_f8 = 1;
    cVar6 = -1;
    local_f4 = 2;
    local_f0 = 2;
    iVar13 = (&DAT_0058937c)[(int)local_c4 * 8] + param_1;
    iVar10 = (&DAT_005893bc)[(int)local_c4 * 8] + param_2;
    cVar5 = -1;
    local_b8 = -1;
    local_54 = -1;
    local_48 = -1;
    local_d4 = -1;
    local_5c = -1;
    local_c0 = -1;
    local_50 = -1;
    local_d0 = -1;
    local_a4 = -1;
    local_b4 = -1;
    local_58 = -1;
    local_c8 = -1;
    local_a8 = -1;
    local_b0 = -1;
    local_104 = 0;
    if (((-1 < iVar10) && (iVar10 < g_map_height_tiles)) &&
       (((-1 < iVar13 && (iVar13 < g_map_width_tiles)) || (DAT_0074c7dc == 1)))) {
      if (iVar13 < 0) {
        iVar13 = iVar13 + g_map_width_tiles;
      }
      if (g_map_width_tiles <= iVar13) {
        iVar13 = iVar13 - g_map_width_tiles;
      }
      pcVar9 = local_c4;
      switch(g_map_size_mode) {
      case 0:
        pcVar9 = (char *)((iVar13 + iVar10 * 0x138) * 0x100 + _g_land_tiles);
        break;
      case 1:
        pcVar9 = (char *)((iVar13 + iVar10 * 0x9c) * 0x100 + _g_land_tiles);
        break;
      case 2:
        pcVar9 = (char *)((iVar13 + iVar10 * 0x4e) * 0x100 + _g_land_tiles);
        break;
      case 3:
        pcVar9 = (char *)((iVar10 * 0x27 + iVar13) * 0x100 + _g_land_tiles);
      }
      cVar5 = pcVar9[0x13];
      local_48 = (int)pcVar9[0x15];
      local_58 = (int)*pcVar9;
      local_50 = (&local_104)[pcVar9[8]];
    }
    iVar13 = (&DAT_00589374)[(int)local_c4 * 8] + param_1;
    iVar10 = (&DAT_005893b4)[(int)local_c4 * 8] + param_2;
    if (((-1 < iVar10) && (iVar10 < g_map_height_tiles)) &&
       (((-1 < iVar13 && (iVar13 < g_map_width_tiles)) || (DAT_0074c7dc == 1)))) {
      if (iVar13 < 0) {
        iVar13 = iVar13 + g_map_width_tiles;
      }
      if (g_map_width_tiles <= iVar13) {
        iVar13 = iVar13 - g_map_width_tiles;
      }
      pcVar9 = local_c4;
      switch(g_map_size_mode) {
      case 0:
        pcVar9 = (char *)((iVar13 + iVar10 * 0x138) * 0x100 + _g_land_tiles);
        break;
      case 1:
        pcVar9 = (char *)((iVar13 + iVar10 * 0x9c) * 0x100 + _g_land_tiles);
        break;
      case 2:
        pcVar9 = (char *)((iVar13 + iVar10 * 0x4e) * 0x100 + _g_land_tiles);
        break;
      case 3:
        pcVar9 = (char *)((iVar10 * 0x27 + iVar13) * 0x100 + _g_land_tiles);
      }
      local_b8 = (int)pcVar9[0x13];
      local_d4 = (int)pcVar9[0x15];
      local_c8 = (int)*pcVar9;
      local_d0 = (&local_104)[pcVar9[8]];
    }
    iVar13 = (&DAT_00589384)[(int)local_c4 * 8] + param_1;
    iVar10 = (&DAT_005893c4)[(int)local_c4 * 8] + param_2;
    if (((-1 < iVar10) && (iVar10 < g_map_height_tiles)) &&
       (((-1 < iVar13 && (iVar13 < g_map_width_tiles)) || (DAT_0074c7dc == 1)))) {
      if (iVar13 < 0) {
        iVar13 = iVar13 + g_map_width_tiles;
      }
      if (g_map_width_tiles <= iVar13) {
        iVar13 = iVar13 - g_map_width_tiles;
      }
      pcVar9 = local_c4;
      switch(g_map_size_mode) {
      case 0:
        pcVar9 = (char *)((iVar13 + iVar10 * 0x138) * 0x100 + _g_land_tiles);
        break;
      case 1:
        pcVar9 = (char *)((iVar13 + iVar10 * 0x9c) * 0x100 + _g_land_tiles);
        break;
      case 2:
        pcVar9 = (char *)((iVar13 + iVar10 * 0x4e) * 0x100 + _g_land_tiles);
        break;
      case 3:
        pcVar9 = (char *)((iVar10 * 0x27 + iVar13) * 0x100 + _g_land_tiles);
      }
      local_54 = (int)pcVar9[0x13];
      local_5c = (int)pcVar9[0x15];
      local_a8 = (int)*pcVar9;
      local_a4 = (&local_104)[pcVar9[8]];
    }
    iVar13 = (&DAT_0058938c)[(int)local_c4 * 8] + param_1;
    iVar10 = (&DAT_005893cc)[(int)local_c4 * 8] + param_2;
    if (((-1 < iVar10) && (iVar10 < g_map_height_tiles)) &&
       (((-1 < iVar13 && (iVar13 < g_map_width_tiles)) || (DAT_0074c7dc == 1)))) {
      if (iVar13 < 0) {
        iVar13 = iVar13 + g_map_width_tiles;
      }
      if (g_map_width_tiles <= iVar13) {
        iVar13 = iVar13 - g_map_width_tiles;
      }
      pcVar9 = local_c4;
      switch(g_map_size_mode) {
      case 0:
        pcVar9 = (char *)((iVar13 + iVar10 * 0x138) * 0x100 + _g_land_tiles);
        break;
      case 1:
        pcVar9 = (char *)((iVar13 + iVar10 * 0x9c) * 0x100 + _g_land_tiles);
        break;
      case 2:
        pcVar9 = (char *)((iVar13 + iVar10 * 0x4e) * 0x100 + _g_land_tiles);
        break;
      case 3:
        pcVar9 = (char *)((iVar10 * 0x27 + iVar13) * 0x100 + _g_land_tiles);
      }
      cVar6 = pcVar9[0x13];
      local_c0 = (int)pcVar9[0x15];
      local_b4 = (&local_104)[pcVar9[8]];
      local_b0 = (int)*pcVar9;
    }
    cVar4 = '\0';
    if (((cVar6 != -1) || (local_c0 != -1)) && ((local_b0 < 0xb || (*pcVar12 < '\v')))) {
      cVar4 = ((local_b4 <= (int)(&local_104)[pcVar12[8]]) - 1U & 9) + 9;
    }
    if (((local_b8 != -1) || (local_d4 != -1)) && ((local_c8 < 0xb || (*pcVar12 < '\v')))) {
      if ((int)(&local_104)[pcVar12[8]] < local_d0) {
        cVar4 = cVar4 + '6';
      }
      else {
        cVar4 = cVar4 + '\x1b';
      }
    }
    if (((cVar5 != -1) || (local_48 != -1)) && ((local_58 < 0xb || (*pcVar12 < '\v')))) {
      if ((int)(&local_104)[pcVar12[8]] < local_50) {
        cVar4 = cVar4 + '\x02';
      }
      else {
        cVar4 = cVar4 + '\x01';
      }
    }
    if (((local_54 != -1) || (local_5c != -1)) && ((local_a8 < 0xb || (*pcVar12 < '\v')))) {
      if ((int)(&local_104)[pcVar12[8]] < local_a4) {
        cVar4 = cVar4 + '\x06';
      }
      else {
        cVar4 = cVar4 + '\x03';
      }
    }
    pcVar12[0x13] = cVar4;
    if (DAT_005aa284 != 0) {
      *(undefined4 *)(DAT_007584c4 + local_e0 * 4) = DAT_00734cb4;
      *(undefined4 *)(DAT_007584c8 + local_e4 * 4) = DAT_00734cb4;
    }
  }
  cVar5 = pcVar12[8];
  if ('\0' < cVar5) {
    if (cVar5 < '\x04') {
      if (cVar5 == '\x03') {
        cVar5 = local_cc == 3;
        if (local_ac == 3) {
          cVar5 = cVar5 + '\x02';
        }
        if (local_d8 == 3) {
          cVar5 = cVar5 + '\x04';
        }
        if (local_dc == 3) {
          cVar5 = cVar5 + '\b';
        }
        cVar6 = FUN_004fbf50(2);
        pcVar12[9] = cVar6 + cVar5 * '\x02';
        if (DAT_005aa280 == 1) {
          *(uint *)(DAT_007584c4 + local_e0 * 4) =
               (uint)(ushort)(*(ushort *)(DAT_005cfea0 + 0x128) | *(ushort *)(DAT_005cfe9c + 0x128)
                             | *(ushort *)(DAT_005cfe98 + 0x128));
          *(uint *)(DAT_007584c8 + local_e4 * 4) =
               (uint)(ushort)(*(ushort *)(DAT_005cfea0 + 0x128) | *(ushort *)(DAT_005cfe9c + 0x128)
                             | *(ushort *)(DAT_005cfe98 + 0x128));
        }
      }
      else {
        uVar14 = 0;
        bVar2 = false;
        pcVar12[9] = -1;
        pcVar12[10] = -1;
        pcVar12[0xb] = -1;
        pcVar12[0xc] = -1;
        local_104 = 0;
        local_f8 = 0;
        pcVar12[0xd] = -1;
        pcVar12[0xe] = -1;
        local_f4 = 0;
        local_f0 = 0;
        local_ec = 0;
        local_e8 = 0;
        cVar5 = 3 < local_cc;
        if (3 < local_dc) {
          cVar5 = cVar5 + '\x02';
        }
        if (3 < local_ac) {
          cVar5 = cVar5 + '\x04';
        }
        if (3 < local_d8) {
          cVar5 = cVar5 + '\b';
        }
        bVar3 = false;
        if (3 < local_ac) {
          bVar2 = 3 < local_cc;
          if (bVar2) {
            cVar6 = FUN_004fbf50(4);
            pcVar12[9] = cVar6 + 'X';
          }
          local_104 = (uint)bVar2;
          uVar14 = (uint)bVar2;
          bVar3 = bVar2;
          if (3 < local_dc) {
            cVar6 = FUN_004fbf50(4);
            bVar3 = true;
            pcVar12[uVar14 + 9] = cVar6 + '\\';
            uVar14 = uVar14 + 1;
            local_f4 = 1;
            local_ec = 1;
          }
        }
        if (3 < local_d8) {
          if (3 < local_cc) {
            cVar6 = FUN_004fbf50(4);
            bVar2 = true;
            pcVar12[uVar14 + 9] = cVar6 + '`';
            uVar14 = uVar14 + 1;
            local_f8 = 1;
            local_f0 = 1;
          }
          if (3 < local_dc) {
            cVar6 = FUN_004fbf50(4);
            pcVar12[uVar14 + 9] = cVar6 + 'd';
            uVar14 = uVar14 + 1;
            local_f0 = 1;
            local_ec = 1;
            local_e8 = 1;
          }
        }
        if (uVar14 < 6) {
          if ((3 < local_4c) && (local_104 == 0)) {
            cVar6 = FUN_004fbf50(4);
            pcVar12[uVar14 + 9] = cVar6 + 'T';
            uVar14 = uVar14 + 1;
          }
          if (uVar14 < 6) {
            if ((3 < local_cc) && (!bVar2)) {
              cVar6 = FUN_004fbf50(6);
              pcVar12[uVar14 + 9] = cVar6 + 'D';
              uVar14 = uVar14 + 1;
            }
            if (uVar14 < 6) {
              if ((3 < local_ac) && (!bVar3)) {
                cVar6 = FUN_004fbf50(6);
                pcVar12[uVar14 + 9] = cVar6 + 'N';
                uVar14 = uVar14 + 1;
              }
              if (uVar14 < 6) {
                if ((3 < local_64) && (local_f8 == 0)) {
                  cVar6 = FUN_004fbf50(4);
                  pcVar12[uVar14 + 9] = cVar6 + ':';
                  uVar14 = uVar14 + 1;
                }
                if (uVar14 < 6) {
                  if ((3 < local_44) && (local_f4 == 0)) {
                    cVar6 = FUN_004fbf50(4);
                    pcVar12[uVar14 + 9] = cVar6 + 'J';
                    uVar14 = uVar14 + 1;
                  }
                  if (uVar14 < 6) {
                    if ((3 < local_d8) && (local_f0 == 0)) {
                      cVar6 = FUN_004fbf50(6);
                      pcVar12[uVar14 + 9] = cVar6 + '4';
                      uVar14 = uVar14 + 1;
                    }
                    if (uVar14 < 6) {
                      if ((3 < local_dc) && (local_ec == 0)) {
                        cVar6 = FUN_004fbf50(6);
                        pcVar12[uVar14 + 9] = cVar6 + '>';
                        uVar14 = uVar14 + 1;
                      }
                      if (((uVar14 < 6) && (3 < local_60)) && (local_e8 == 0)) {
                        cVar6 = FUN_004fbf50(4);
                        pcVar12[uVar14 + 9] = cVar6 + '0';
                        uVar14 = uVar14 + 1;
                      }
                    }
                  }
                }
              }
            }
          }
        }
        if ((uVar14 == 0) && (cVar5 == '\0')) {
          pcVar12[8] = '\0';
          pcVar12[9] = -1;
          pcVar12[10] = -1;
          pcVar12[0xb] = -1;
          pcVar12[0xc] = -1;
          pcVar12[0xd] = -1;
          pcVar12[0xe] = -1;
        }
        else if (DAT_005aa280 == 1) {
          *(uint *)(DAT_007584c4 + local_e0 * 4) =
               (uint)(ushort)(*(ushort *)(DAT_005cfea0 + 0x128) | *(ushort *)(DAT_005cfe9c + 0x128)
                             | *(ushort *)(DAT_005cfe98 + 0x128));
          *(uint *)(DAT_007584c8 + local_e4 * 4) =
               (uint)(ushort)(*(ushort *)(DAT_005cfea0 + 0x128) | *(ushort *)(DAT_005cfe9c + 0x128)
                             | *(ushort *)(DAT_005cfe98 + 0x128));
        }
      }
    }
    else {
      local_40[0] = 0;
      local_40[1] = 0xd;
      local_40[2] = 0xe;
      local_40[3] = 3;
      local_40[4] = 0xb;
      local_40[5] = 4;
      local_40[6] = 6;
      local_40[7] = 9;
      local_40[8] = 0xc;
      local_40[9] = 1;
      local_40[10] = 2;
      local_40[0xb] = 10;
      local_40[0xc] = 5;
      local_40[0xd] = 8;
      local_40[0xe] = 7;
      local_40[0xf] = 0xf;
      uVar14 = (uint)(3 < local_d8);
      if (3 < local_cc) {
        uVar14 = uVar14 + 2;
      }
      if (3 < local_ac) {
        uVar14 = uVar14 + 4;
      }
      if (3 < local_dc) {
        uVar14 = uVar14 + 8;
      }
      cVar5 = FUN_004fbf50(3);
      pcVar12[9] = cVar5 + (char)local_40[uVar14] * '\x03';
      if (DAT_005aa280 == 1) {
        if (pcVar12[8] == '\x04') {
          *(uint *)(DAT_007584c4 + local_e0 * 4) =
               (uint)(ushort)(*(ushort *)(DAT_005cfea0 + 0x330) | *(ushort *)(DAT_005cfe9c + 0x330)
                             | *(ushort *)(DAT_005cfe98 + 0x330));
          *(uint *)(DAT_007584c8 + local_e4 * 4) =
               (uint)(ushort)(*(ushort *)(DAT_005cfea0 + 0x330) | *(ushort *)(DAT_005cfe9c + 0x330)
                             | *(ushort *)(DAT_005cfe98 + 0x330));
        }
        else {
          *(uint *)(DAT_007584c4 + local_e0 * 4) =
               (uint)(ushort)(*(ushort *)(DAT_005cfea0 + 0x3fc) | *(ushort *)(DAT_005cfe9c + 0x3fc)
                             | *(ushort *)(DAT_005cfe98 + 0x3fc));
          *(uint *)(DAT_007584c8 + local_e4 * 4) =
               (uint)(ushort)(*(ushort *)(DAT_005cfea0 + 0x3fc) | *(ushort *)(DAT_005cfe9c + 0x3fc)
                             | *(ushort *)(DAT_005cfe98 + 0x3fc));
        }
      }
    }
  }
  if (DAT_00755954 != 0) {
    iVar10 = *(int *)((&DAT_007584d0)[DAT_007584d8] + local_bc * 4);
    if (DAT_005aa27c != 0) {
      if ('\n' < *pcVar12) {
        *(undefined2 *)(DAT_007584c0 + 4 + iVar10 * 2) = 10;
        return;
      }
      if ('\0' < pcVar12[0x25]) {
        *(undefined2 *)(DAT_007584c0 + 4 + iVar10 * 2) =
             *(undefined2 *)(&DAT_0074c0ac + pcVar12[0x25]);
        return;
      }
      *(undefined2 *)(DAT_007584c0 + 4 + iVar10 * 2) = 0;
      return;
    }
    if (*(int *)(pcVar12 + 0x88) == 0) {
      if (pcVar12[0x50] < '\x01') {
        if (DAT_005aa270 != 0) {
          *(undefined2 *)(DAT_007584c0 + 4 + iVar10 * 2) =
               *(undefined2 *)((&DAT_007584c4)[DAT_007584d8] + iVar10 * 4);
          return;
        }
        switch(g_map_size_mode) {
        case 0:
          local_c4 = (char *)((param_1 + param_2 * 0x138) * 0x100 + _g_land_tiles);
          break;
        case 1:
          local_c4 = (char *)((param_1 + param_2 * 0x9c) * 0x100 + _g_land_tiles);
          break;
        case 2:
          local_c4 = (char *)((param_1 + param_2 * 0x4e) * 0x100 + _g_land_tiles);
          break;
        case 3:
          local_c4 = (char *)((param_2 * 0x27 + param_1) * 0x100 + _g_land_tiles);
        }
        *(ushort *)(DAT_007584c0 + 4 + iVar10 * 2) = (*local_c4 < '\v') - 1 & 10;
      }
      else if (DAT_005aa278 != 0) {
        iVar13 = 0;
        piVar11 = (int *)(pcVar12 + 0x28);
        while (*piVar11 == 0) {
          iVar13 = iVar13 + 1;
          piVar11 = piVar11 + 1;
          if (9 < iVar13) {
            return;
          }
        }
        cVar5 = *(char *)(*(int *)(pcVar12 + iVar13 * 4 + 0x28) + 1);
        if (-1 < cVar5) {
          if (*(char *)(iVar10 + DAT_007584cc) == -1) {
            *(undefined2 *)(DAT_007584c0 + 4 + iVar10 * 2) = *(undefined2 *)(&DAT_0074c0ac + cVar5);
            *(char *)(iVar10 + DAT_007584cc) = cVar5;
            return;
          }
          if (*(char *)(iVar10 + DAT_007584cc) != cVar5) {
            *(undefined2 *)(DAT_007584c0 + 4 + iVar10 * 2) = DAT_0074c104;
            *(undefined1 *)(iVar10 + DAT_007584cc) = 0x16;
            return;
          }
        }
      }
    }
    else if (DAT_005aa274 != 0) {
      iVar13 = (int)*(char *)(*(int *)(pcVar12 + 0x88) + 1);
      if (-1 < iVar13) {
        *(undefined2 *)(DAT_007584c0 + 4 + iVar10 * 2) = *(undefined2 *)(&DAT_0074c0ac + iVar13);
        return;
      }
      if (*(short *)(DAT_007584c0 + 4 + iVar10 * 2) == 0) {
        *(undefined2 *)(DAT_007584c0 + 4 + iVar10 * 2) =
             *(undefined2 *)((&DAT_007584c4)[DAT_007584d8] + iVar10 * 4);
        return;
      }
    }
  }
  return;
}

