/*
 * Generated by Ghidra headless decompiler from China2EX_fontfix8.exe.
 * Address request: 0x0047c2a0
 * This is reconstructed pseudocode, not original source.
 */


void Del_City_Wall_Or_Culvert(int param_1,int param_2)

{
  int iVar1;
  uint uVar2;
  int iVar3;
  int iVar4;

  iVar1 = param_2;
  Trace_Function(s_Del_City_Wall_Or_Culvert_00576470);
  if (DAT_0074a2b1 != '\0') {
    iVar3 = *(int *)(param_1 + 0x1ac);
    param_2 = 0x30;
    do {
      iVar4 = 0x30;
      do {
        if (*(char *)(iVar3 + 7) == iVar1) {
          *(undefined1 *)(iVar3 + 7) = 0xff;
          *(undefined1 *)(iVar3 + 0xb) = 0xff;
          *(undefined2 *)(iVar3 + 8) = 0xffff;
          *(undefined1 *)(iVar3 + 10) = 0xff;
          uVar2 = Game_Random_Mod(0xc);
          *(short *)(iVar3 + 0xc) = (short)uVar2;
        }
        iVar3 = iVar3 + 0x20;
        iVar4 = iVar4 + -1;
      } while (iVar4 != 0);
      param_2 = param_2 + -1;
    } while (param_2 != 0);
  }
  *(undefined1 *)(param_1 + 100 + iVar1) = 0;
  if (param_1 == DAT_007584a8) {
    DAT_007584bc = 0;
  }
  return;
}
