/*
 * Generated by Ghidra headless decompiler from China2EX_fontfix8.exe.
 * Address request: 0x00439d70
 * This is reconstructed pseudocode, not original source.
 */


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

bool Diplomat_Commotion(void)

{
  byte bVar1;
  City_0x1b8_plus *city;
  ushort uVar2;
  short sVar3;
  int iVar4;
  undefined *puVar5;
  undefined *puVar6;
  byte *pbVar7;
  char *pcVar8;
  byte *pbVar9;
  bool local_c1;
  undefined1 local_c0 [192];

  Trace_Function(s_Diplomat_Commotion_005198dc);
  if ((_DAT_00748e34 != g_human_country_index) ||
     (iVar4 = DAT_0075597c, g_auto_turn_or_ai_control_flag != 0)) {
    iVar4 = 0;
    switch(g_map_size_mode) {
    case 0:
      iVar4 = (int)*(short *)(_DAT_00748ff0 + 0x1e) + *(short *)(_DAT_00748ff0 + 0x20) * 0x138;
      break;
    case 1:
      iVar4 = (int)*(short *)(_DAT_00748ff0 + 0x1e) + *(short *)(_DAT_00748ff0 + 0x20) * 0x9c;
      break;
    case 2:
      iVar4 = (int)*(short *)(_DAT_00748ff0 + 0x1e) + *(short *)(_DAT_00748ff0 + 0x20) * 0x4e;
      break;
    case 3:
      iVar4 = *(short *)(_DAT_00748ff0 + 0x20) * 0x27 + (int)*(short *)(_DAT_00748ff0 + 0x1e);
      break;
    default:
      goto switchD_00439db4_default;
    }
    iVar4 = iVar4 * 0x100 + _g_land_tiles;
  }
switchD_00439db4_default:
  city = *(City_0x1b8_plus **)(iVar4 + 0x88);
  *(undefined1 *)city = 1;
  iVar4 = (char)city->owner_country_id * 0xe68;
  if (city->safety_score < 1) {
    local_c1 = true;
  }
  else {
    bVar1 = g_active_country->leader_or_country_id;
    if (((bVar1 == 0x19) || (bVar1 == 0x21)) || (bVar1 == 0x23)) {
      sVar3 = 1;
    }
    else {
      sVar3 = 0;
    }
    uVar2 = FUN_004fbf50(CONCAT22((short)((uint)((char)city->owner_country_id * 0x73) >> 0x10),
                                  (short)city->safety_score));
    local_c1 = uVar2 < (ushort)(sVar3 * 0x1e + 10U);
    if (!local_c1) {
      if (_DAT_00748e34 == g_human_country_index) {
        if (DAT_0074a2cc != '\x01') {
          return false;
        }
        sVar3 = FUN_004fbf50(2);
        if (sVar3 == 0) {
          bVar1 = city->city_type_or_terrain_class;
          puVar6 = &DAT_005197cc;
        }
        else {
          bVar1 = city->city_type_or_terrain_class;
          puVar6 = &DAT_005192c8;
        }
        Format_Text(local_c0,puVar6,&DAT_007350bc + iVar4,&DAT_005a7bdc + (uint)bVar1 * 5,
                    city->name_bytes);
      }
      else if ((char)city->owner_country_id == g_human_country_index) {
        if (DAT_0074a2cc != '\x01') {
          return false;
        }
        sVar3 = FUN_004fbf50(2);
        if (sVar3 == 0) {
          Format_Text(local_c0,&DAT_005197a8,
                      &DAT_005a7bdc + (uint)city->city_type_or_terrain_class * 5,city->name_bytes,
                      g_active_country->name_bytes);
        }
        else {
          Format_Text(local_c0,&DAT_0051977c,
                      &DAT_005a7bdc + (uint)city->city_type_or_terrain_class * 5,city->name_bytes,
                      g_active_country->name_bytes);
        }
      }
      else {
        if (DAT_00755940 == 0) {
          if (_DAT_00748e34 == 0) {
            return false;
          }
          if ((*(int *)(_DAT_00748e30 + 0x1ac + _DAT_00748e34 * 4) < 2) &&
             (*(int *)(_DAT_00748e30 + 0x1ac + (char)city->owner_country_id * 4) < 2)) {
            return false;
          }
        }
        if (DAT_0074a2cd != '\x01') {
          return false;
        }
        Format_Text(local_c0,&DAT_00519758,g_active_country->name_bytes,&DAT_007350bc + iVar4,
                    &DAT_005a7bdc + (uint)city->city_type_or_terrain_class * 5,city->name_bytes);
      }
      FUN_004898b0(DAT_007350b4,local_c0,1,city->tile_x,city->tile_y);
      goto LAB_0043a1cd;
    }
  }
  FUN_004fbf50(0x19);
  City_Safe_Change(city);
  if (_DAT_00748e34 == g_human_country_index) {
    if (DAT_0074a2cc != '\x01') {
      return local_c1;
    }
    sVar3 = FUN_004fbf50(2);
    if (sVar3 == 0) {
      bVar1 = city->city_type_or_terrain_class;
      puVar6 = &DAT_005198b8;
    }
    else {
      bVar1 = city->city_type_or_terrain_class;
      puVar6 = &DAT_00519888;
    }
    Format_Text(local_c0,puVar6,&DAT_007350bc + iVar4,&DAT_005a7bdc + (uint)bVar1 * 5,
                city->name_bytes);
  }
  else {
    if ((char)city->owner_country_id == g_human_country_index) {
      if (DAT_0074a2cc != '\x01') {
        return local_c1;
      }
      sVar3 = FUN_004fbf50(2);
      if (sVar3 != 0) {
        Format_Text(local_c0,&DAT_00519824,
                    &DAT_005a7bdc + (uint)city->city_type_or_terrain_class * 5,city->name_bytes,
                    g_active_country->name_bytes);
        goto LAB_0043a01e;
      }
      pcVar8 = city->name_bytes;
      pbVar7 = g_active_country->name_bytes;
      puVar6 = &DAT_005a7bdc + (uint)city->city_type_or_terrain_class * 5;
      puVar5 = &DAT_00519854;
      pbVar9 = pbVar7;
    }
    else {
      if (DAT_00755940 == 0) {
        if (_DAT_00748e34 == 0) {
          return local_c1;
        }
        if ((*(int *)(_DAT_00748e30 + 0x1ac + _DAT_00748e34 * 4) < 2) &&
           (*(int *)(_DAT_00748e30 + 0x1ac + (char)city->owner_country_id * 4) < 2)) {
          return local_c1;
        }
      }
      if (DAT_0074a2cd != '\x01') {
        return local_c1;
      }
      pbVar9 = (byte *)city->name_bytes;
      puVar6 = &DAT_007350bc + iVar4;
      pcVar8 = &DAT_005a7bdc + (uint)city->city_type_or_terrain_class * 5;
      pbVar7 = g_active_country->name_bytes;
      puVar5 = &DAT_005197fc;
    }
    Format_Text(local_c0,puVar5,pbVar7,puVar6,pcVar8,pbVar9);
  }
LAB_0043a01e:
  FUN_004898b0(DAT_007350b4,local_c0,1,city->tile_x,city->tile_y);
LAB_0043a1cd:
  UI_YesNo_Message(local_c0,0,0,1);
  return local_c1;
}
