/*
 * Generated by Ghidra headless decompiler from China2EX_fontfix8.exe.
 * Address request: 0x0049fe50
 * This is reconstructed pseudocode, not original source.
 */


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

undefined4 Edit_Finish(void)

{
  bool bVar1;
  undefined4 uVar2;
  undefined4 uVar3;
  int iVar4;
  uint *puVar5;
  char *pcVar6;
  int iVar7;
  int *piVar8;
  int iVar9;
  undefined4 *puVar10;
  undefined1 local_180 [192];
  undefined1 local_c0 [192];

  Trace_Function(s_Edit_Finish_0057ed30);
  if ((((_DAT_00748e30 == (char *)0x0) || (*_DAT_00748e30 < '\0')) ||
      ((_DAT_00748e30[1] == '\0' && (_DAT_00748e30[3] == '\0')))) ||
     ((*(short *)(_DAT_00748e30 + 0x1aa) == 0 && (*(short *)(_DAT_00748e30 + 0x7c) == 0)))) {
    bVar1 = true;
  }
  else {
    bVar1 = false;
    if (g_current_map_scenario_info.country_setup_mode < 1) {
      UI_YesNo_Result(&DAT_0057ed04,0);
      return 0;
    }
  }
  _DAT_0075c964 = 0;
  g_map_interaction_mode = 1;
  g_editor_mode_enabled = 0;
  iVar4 = g_map_width_tiles;
  iVar9 = DAT_00758524;
  uVar2 = DAT_0075c96c;
  if (g_editor_land_tile_backup != (LandTile_0x100 *)0x0) {
    FUN_0047de70(g_editor_land_tile_backup,s_Edit_MAP_TYPE_BackUp_00517900,1);
    g_editor_land_tile_backup = (LandTile_0x100 *)0x0;
    iVar4 = g_map_width_tiles;
    iVar9 = DAT_00758524;
    uVar2 = DAT_0075c96c;
  }
  for (; uVar3 = DAT_0075c96c, g_map_width_tiles = iVar4, iVar9 != 0; iVar9 = *(int *)(iVar9 + 0xc4)
      ) {
    DAT_0075c96c = uVar2;
    if (*(int *)(iVar9 + 4) != 0) {
      if (*(int *)(iVar9 + 8) < 1) {
        if (*(int *)(iVar9 + 8) < 0) {
          if (*(int *)(iVar9 + 0x10) != 0) {
            DAT_0070791c = DAT_0070791c + 1;
          }
          *(int *)(iVar9 + 8) = -*(int *)(iVar9 + 8);
        }
      }
      else {
        FUN_00472320(iVar9);
      }
    }
    iVar4 = g_map_width_tiles;
    uVar2 = DAT_0075c96c;
    DAT_0075c96c = uVar3;
  }
  DAT_00755958 = 0;
  DAT_0075595c = 0;
  if ((DAT_0057ecdc != g_human_country_index) && (iVar9 = 0, 0 < g_map_height_tiles)) {
    do {
      iVar7 = 0;
      if (0 < iVar4) {
        do {
          FUN_00413d80(iVar7,iVar9,1);
          iVar7 = iVar7 + 1;
          iVar4 = g_map_width_tiles;
        } while (iVar7 < g_map_width_tiles);
      }
      iVar9 = iVar9 + 1;
    } while (iVar9 < g_map_height_tiles);
  }
  FUN_004a16b0();
  if (bVar1) {
    FUN_0049c990();
    g_app_screen_state = 0x28;
    g_menu_action_tick = Get_Game_Tick();
    g_frame_tick = g_menu_action_tick;
  }
  else {
    FUN_0049ca90();
    piVar8 = &DAT_0074d660;
    do {
      if (0 < *piVar8) {
        FUN_00478dc0(*piVar8);
      }
      piVar8 = piVar8 + 0x50;
    } while ((int)piVar8 < 0x755220);
    puVar10 = &DAT_0074d524;
    piVar8 = &DAT_00589a50;
    do {
      if ((0 < piVar8[-0xe]) &&
         (-1 < g_country_profile_defs[*piVar8].portrait_enabled_or_display_flag)) {
        iVar4 = g_country_profile_defs[*piVar8].profile_portrait_resource_id;
        Format_Text(local_c0,s_DIP__02d_IMG_005178b8,iVar4);
        Format_Text(local_180,s_DIP__02d_IDI_005178a8,iVar4);
        iVar4 = FUN_00478bc0(local_c0,local_180);
        puVar10[-1] = iVar4;
        if (iVar4 < 0) {
          FUN_0046a230(local_c0,local_180);
        }
        *puVar10 = 0;
        puVar10[1] = 0;
        puVar10[2] = 0;
        puVar10[3] = 0;
      }
      iVar4 = DAT_005cfe9c;
      piVar8 = piVar8 + 0x80;
      puVar10 = puVar10 + 0x50;
    } while ((int)piVar8 < 0x596250);
    pcVar6 = &g_country_states;
    puVar5 = &DAT_0074c0ac;
    do {
      if ('\0' < *pcVar6) {
        iVar9 = (uint)(byte)pcVar6[1] * 0x200;
        *puVar5 = (uint)(ushort)(*(ushort *)(*(int *)(&DAT_00589b40 + iVar9) * 0x20 + DAT_005cfea0)
                                 | *(ushort *)(*(int *)(&DAT_00589b3c + iVar9) * 0x20 + iVar4) |
                                *(ushort *)(*(int *)(&DAT_00589b38 + iVar9) * 0x20 + DAT_005cfe98));
      }
      puVar5 = puVar5 + 1;
      pcVar6 = pcVar6 + 0xe68;
    } while ((int)puVar5 < 0x74c104);
    FUN_00477d00();
    FUN_004a16b0();
  }
  FUN_004bdc90();
  DAT_0075852c = 0;
  DAT_005c77a8 = 0xffffffff;
  return 1;
}
