/*
 * Generated by Ghidra headless decompiler from China2EX_fontfix8.exe.
 * Address request: 0x0048edd0
 * This is reconstructed pseudocode, not original source.
 */


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

undefined4
InRange_NearDest_City_Found(int param_1,int param_2,int param_3,int *param_4,int *param_5)

{
  short *psVar1;
  byte bVar2;
  int iVar3;
  int iVar4;
  int iVar5;
  int iVar6;
  int from_x;
  int from_y;
  int iVar7;
  int local_14;
  int local_10;
  int local_c;
  int local_4;

  Trace_Function(s_InRange_NearDest_City_Found_0057dc68);
  bVar2 = *(byte *)(_DAT_00748ff0 + 0x1c);
  local_c = -1;
  local_14 = 1;
  local_10 = g_map_height_tiles + g_map_width_tiles;
  iVar4 = _g_land_tiles;
  iVar5 = _DAT_00748ff0;
  iVar6 = g_map_width_tiles;
  iVar7 = param_3;
  if (0 < g_tile_radius_offset_counts[param_3]) {
    do {
      psVar1 = (short *)((int)g_edit_dest_round_buffers[bVar2 & 1] + local_14 * 8);
      from_x = (int)*(short *)(iVar5 + 0x1a) + (int)*psVar1;
      from_y = (int)psVar1[1] + (int)*(short *)(iVar5 + 0x1c);
      if (((-1 < from_y) && (from_y < g_map_height_tiles)) &&
         (((-1 < from_x && (from_x < iVar6)) ||
          (g_current_map_scenario_info.horizontal_wrap_setting == 1)))) {
        if (from_x < 0) {
          from_x = from_x + iVar6;
        }
        if (iVar6 <= from_x) {
          from_x = from_x - iVar6;
        }
        switch(g_map_size_mode) {
        case 0:
          iVar7 = from_x + from_y * 0x138;
          break;
        case 1:
          iVar7 = from_x + from_y * 0x9c;
          break;
        case 2:
          iVar7 = from_x + from_y * 0x4e;
          break;
        case 3:
          iVar7 = from_y * 0x27 + from_x;
          break;
        default:
          goto switchD_0048ee93_default;
        }
        iVar7 = iVar7 * 0x100 + iVar4;
switchD_0048ee93_default:
        if ((((*(int *)(iVar7 + 0x88) != 0) && (*(char *)(iVar7 + 0x25) == _DAT_00748e34)) &&
            (iVar6 = g_map_width_tiles,
            (int)((uint)*(byte *)(iVar5 + 0x148) + (int)*(char *)(iVar7 + 0x7c) + 1 +
                 (int)*(char *)(iVar7 + 0x50)) < 0xb)) &&
           (iVar3 = Tile_Distance_With_Wrap(from_x,from_y,param_1,param_2,(byte *)0x0),
           iVar4 = _g_land_tiles, iVar5 = _DAT_00748ff0, iVar6 = g_map_width_tiles, iVar3 < local_10
           )) {
          local_10 = iVar3;
          local_c = from_x;
          local_4 = from_y;
        }
      }
      local_14 = local_14 + 1;
    } while (local_14 <= g_tile_radius_offset_counts[param_3]);
    if (-1 < local_c) {
      *param_4 = local_c;
      *param_5 = local_4;
      return 1;
    }
  }
  return 0;
}
