/*
 * Generated by Ghidra headless decompiler from China2EX_fontfix8.exe.
 * Address request: 0x0045b1d0
 * This is reconstructed pseudocode, not original source.
 */


void MouseOn_Edit_Sel_Custom_Map(void)

{
  int iVar1;
  int iVar2;
  int iVar3;

  Trace_Function(s_MouseOn_Edit_Sel_Custom_Map_00571f74);
  g_custom_map_hover_index = -1;
  iVar3 = 0;
  iVar2 = DAT_00714e5c + 0x3f;
  do {
    if ((((iVar2 + -0x17 <= g_view_center_y) && (g_view_center_y <= iVar2)) &&
        (DAT_00714e58 + 0x1c <= g_view_center_x)) &&
       (iVar1 = iVar3, g_view_center_x <= DAT_00714e58 + 0xc4)) break;
    iVar3 = iVar3 + 1;
    iVar2 = iVar2 + 0x1a;
    iVar1 = g_custom_map_hover_index;
  } while (iVar3 < 0x14);
  g_custom_map_hover_index = iVar1;
  g_custom_map_action = -1;
  if (-1 < g_selected_custom_map_index) {
    if (((DAT_00714e5c + 0x1b8 <= g_view_center_y) && (g_view_center_y <= DAT_00714e5c + 0x1d8)) &&
       ((DAT_00714e58 + 0x14a <= g_view_center_x && (g_view_center_x <= DAT_00714e58 + 0x1ca)))) {
      g_custom_map_action = 0;
    }
    if (((DAT_00714e5c + 0x1e0 <= g_view_center_y) && (g_view_center_y <= DAT_00714e5c + 0x200)) &&
       ((DAT_00714e58 + 0x14a <= g_view_center_x && (g_view_center_x <= DAT_00714e58 + 0x1ca)))) {
      g_custom_map_action = 1;
    }
  }
  if ((((DAT_00714e5c + 0x208 <= g_view_center_y) && (g_view_center_y <= DAT_00714e5c + 0x228)) &&
      (DAT_00714e58 + 0x14a <= g_view_center_x)) && (g_view_center_x <= DAT_00714e58 + 0x1ca)) {
    g_custom_map_action = 2;
  }
  return;
}
