/*
 * Generated by Ghidra headless decompiler from China2EX_fontfix8.exe.
 * Address request: 0x0048efa0
 * This is reconstructed pseudocode, not original source.
 */


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

undefined4 Near_City_With_Air_Found(undefined4 *param_1,int *param_2,int *param_3)

{
  int *piVar1;
  byte bVar2;
  byte *pbVar3;
  short *psVar4;
  int iVar5;
  int iVar6;
  int iVar7;
  int local_20;
  int local_1c;
  int local_18;
  int local_14;

  Trace_Function(s_Near_City_With_Air_Found_0057dc84);
  local_14 = 1;
  piVar1 = g_tile_radius_offset_counts + (int)param_1;
  if (0 < *piVar1) {
    iVar5 = (int)param_1;
    psVar4 = g_edit_dest_round_buffers[(int)*(short *)(_DAT_00748ff0 + 0x1c) & 1];
    do {
      iVar6 = (int)psVar4[4] + (int)*(short *)(_DAT_00748ff0 + 0x1a);
      iVar7 = (int)psVar4[5] + (int)*(short *)(_DAT_00748ff0 + 0x1c);
      if (((-1 < iVar7) && (iVar7 < g_map_height_tiles)) &&
         (((-1 < iVar6 && (iVar6 < g_map_width_tiles)) ||
          (g_current_map_scenario_info.horizontal_wrap_setting == 1)))) {
        if (iVar6 < 0) {
          iVar6 = iVar6 + g_map_width_tiles;
        }
        if (g_map_width_tiles <= iVar6) {
          iVar6 = iVar6 - g_map_width_tiles;
        }
        switch(g_map_size_mode) {
        case 0:
          iVar5 = iVar6 + iVar7 * 0x138;
          break;
        case 1:
          iVar5 = iVar6 + iVar7 * 0x9c;
          break;
        case 2:
          iVar5 = iVar6 + iVar7 * 0x4e;
          break;
        case 3:
          iVar5 = iVar7 * 0x27 + iVar6;
          break;
        default:
          goto switchD_0048f05c_default;
        }
        iVar5 = iVar5 * 0x100 + _g_land_tiles;
switchD_0048f05c_default:
        if ((((*(int *)(iVar5 + 0x88) != 0) && (*(char *)(iVar5 + 0x25) == _DAT_00748e34)) &&
            ((int)((uint)*(byte *)(_DAT_00748ff0 + 0x148) + (int)*(char *)(iVar5 + 0x7c) + 1 +
                  (int)*(char *)(iVar5 + 0x50)) < 0xb)) && ('\x01' < *(char *)(iVar5 + 0x50))) {
          local_18 = 10;
          local_1c = 0;
          local_20 = 0;
          param_1 = (undefined4 *)(iVar5 + 0x28);
          do {
            pbVar3 = (byte *)*param_1;
            if ((pbVar3 != (byte *)0x0) && (pbVar3[0x127] == 0)) {
              bVar2 = *pbVar3;
              if ((g_army_type_table[bVar2].unit_class == 1) &&
                 ((pbVar3[0x148] == 0 && (bVar2 == 0x28)))) {
                local_1c = local_1c + 1;
              }
              else if ((g_army_type_table[bVar2].unit_class == 2) &&
                      ((g_army_type_table[bVar2].transportable_mask &
                       g_active_army_type_def->air_or_city_capability_mask) != 0)) {
                local_20 = local_20 + 1;
              }
            }
            param_1 = param_1 + 1;
            local_18 = local_18 + -1;
          } while (local_18 != 0);
          if ((0 < local_20) && (local_1c == 0)) {
            *param_2 = iVar6;
            *param_3 = iVar7;
            return 1;
          }
        }
      }
      local_14 = local_14 + 1;
      psVar4 = psVar4 + 4;
    } while (local_14 <= *piVar1);
  }
  return 0;
}
