/*
 * Generated by Ghidra headless decompiler from China2EX_fontfix8.exe.
 * Address request: 0x004b8db0
 * This is reconstructed pseudocode, not original source.
 */


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void Read_MRR_Edit(void)

{
  LandTile_0x100 *pLVar1;
  int iVar2;
  
  Trace_Function(s_Read_MRR_Edit_0057f920);
  pLVar1 = g_current_land_tile;
  if ((((DAT_005c77a8 == -1) && (-1 < _DAT_00755908)) && (-1 < _DAT_0075590c)) &&
     ((_DAT_00755908 < g_map_width_tiles && (_DAT_0075590c < g_map_height_tiles)))) {
    if (DAT_00716124 == 1) {
      DAT_00716124 = 2;
    }
    if (0 < DAT_005c6d88) {
      FUN_00472320(&DAT_005c6d80);
      return;
    }
    if (g_current_land_tile->linked_record != (void *)0x0) {
      DAT_0071610c = g_current_land_tile->linked_record;
      FUN_00472120(&DAT_005c6d80);
      return;
    }
    if ((char)g_current_land_tile->army_count_or_occupant_count < '\x01') {
      if (g_editor_tool_mode == 7) {
        if (-1 < g_current_land_tile->editor_named_point_index_a) {
          (&DAT_005e7d54)[g_current_land_tile->editor_named_point_index_a * 8] = 0xffffffff;
          (&DAT_005e7d58)[pLVar1->editor_named_point_index_a * 8] = 0xffffffff;
          iVar2 = (int)pLVar1->editor_named_point_index_a;
          *(undefined4 *)(&DAT_005e7d5c + iVar2 * 0x20) = 0;
          (&DAT_005e7d60)[iVar2 * 8] = 0;
          (&DAT_005e7d64)[iVar2 * 8] = 0;
          (&DAT_005e7d68)[iVar2 * 8] = 0;
          (&DAT_005e7d6c)[iVar2 * 0x20] = 0;
          pLVar1->editor_named_point_index_a = -1;
          return;
        }
      }
      else if ((g_editor_tool_mode == 8) && (-1 < g_current_land_tile->editor_named_point_index_b))
      {
        (&DAT_005e0050)[g_current_land_tile->editor_named_point_index_b * 0x20] = 0;
        (&DAT_005e0054)[pLVar1->editor_named_point_index_b * 8] = 0xffffffff;
        (&DAT_005e0058)[pLVar1->editor_named_point_index_b * 8] = 0xffffffff;
        iVar2 = (int)pLVar1->editor_named_point_index_b;
        (&DAT_005e005c)[iVar2 * 8] = 0;
        (&DAT_005e0060)[iVar2 * 8] = 0;
        (&DAT_005e0064)[iVar2 * 8] = 0;
        (&DAT_005e0068)[iVar2 * 8] = 0;
        (&DAT_005e006c)[iVar2 * 0x20] = 0;
        pLVar1->editor_named_point_index_b = -1;
      }
    }
    else {
      iVar2 = UI_YesNo_Dialog(&DAT_0057f90c,0,0,0xffffffff,0,0xffffffff,0,DAT_007350b4);
      if (iVar2 == 1) {
        FUN_004b8f60(g_current_land_tile);
        return;
      }
    }
  }
  return;
}

