/*
 * Generated by Ghidra headless decompiler from China2EX_fontfix8.exe.
 * Address request: 0x004b80c0
 * This is reconstructed pseudocode, not original source.
 */


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void Read_MRP_Edit(void)

{
  short *psVar1;
  void *pvVar2;
  char *pcVar3;
  undefined4 *puVar4;
  undefined4 *puVar5;
  undefined4 *puVar6;
  int iVar7;
  int iVar8;
  int iVar9;
  char *pcVar10;
  uint uVar11;
  LandTile_0x100 *pLVar12;
  int iVar13;
  int local_148;
  int local_140;
  int local_13c;
  int local_138;
  int local_134 [4];
  undefined1 local_124 [284];
  undefined4 uStack_8;
  char *pcStack_4;

  pcStack_4 = s_Mouse_MRP_0057f8c0;
  uStack_8 = 0x4b80ca;
  Trace_Function();
  if ((g_editor_mode_enabled == 0) || (DAT_00716108 != '\0')) {
    return;
  }
  Trace_Function(s_Read_MRP_Edit_0057f8e0);
  if ((((DAT_00758530 == 0) && (-1 < _DAT_00755908)) && (-1 < (int)_DAT_0075590c)) &&
     ((_DAT_00755908 < g_map_width_tiles && ((int)_DAT_0075590c < g_map_height_tiles)))) {
    if (DAT_00716124 != 1) {
      DAT_00716124 = 1;
      puVar5 = _g_land_tiles;
      pLVar12 = g_editor_land_tile_backup;
      for (iVar7 = (g_map_height_tiles * g_map_width_tiles & 0xffffffU) << 6; iVar7 != 0;
          iVar7 = iVar7 + -1) {
        *(undefined4 *)pLVar12 = *puVar5;
        puVar5 = puVar5 + 1;
        pLVar12 = (LandTile_0x100 *)&pLVar12->field_0x4;
      }
      for (iVar7 = 0; iVar7 != 0; iVar7 = iVar7 + -1) {
        *(undefined1 *)pLVar12 = *(undefined1 *)puVar5;
        puVar5 = (undefined4 *)((int)puVar5 + 1);
        pLVar12 = (LandTile_0x100 *)&pLVar12->field_0x1;
      }
    }
    local_134[0] = 0;
    local_134[1] = 1;
    local_134[2] = 2;
    local_134[3] = 4;
    switch(g_editor_tool_mode) {
    case 1:
      pvVar2 = g_current_land_tile->linked_record;
      if (pvVar2 != (void *)0x0) {
        Format_Text(local_124,&DAT_0057f8cc,(int)pvVar2 + 3);
        iVar7 = UI_YesNo_Dialog(local_124,0,0,0xffffffff,0,0xffffffff,0,DAT_007350b4);
        if (iVar7 == 1) {
          FUN_0047b0c0(pvVar2);
          DAT_00588b80 = 1;
          return;
        }
      }
      break;
    case 2:
      if ('\0' < (char)g_current_land_tile->army_count_or_occupant_count) {
        FUN_004b8f60(g_current_land_tile);
        DAT_00588b80 = 1;
        return;
      }
      break;
    default:
      puVar6 = (undefined4 *)(_DAT_0075590c & 1);
      local_148 = 0;
      iVar7 = g_editor_tool_mode;
      puVar5 = puVar6;
      if (-1 < *(int *)(&DAT_0074a360 + local_134[g_editor_brush_size_index] * 4)) {
        do {
          iVar13 = *(short *)((int)g_edit_dest_round_buffers[(int)puVar6] + local_148 * 8) +
                   _DAT_00755908;
          uVar11 = (int)*(short *)((int)g_edit_dest_round_buffers[(int)puVar6] + local_148 * 8 + 2)
                   + _DAT_0075590c;
          if (((-1 < (int)uVar11) && ((int)uVar11 < g_map_height_tiles)) &&
             (((-1 < iVar13 && (iVar13 < g_map_width_tiles)) ||
              (g_current_map_scenario_info.horizontal_wrap_enabled == 1)))) {
            if (iVar13 < 0) {
              iVar13 = iVar13 + g_map_width_tiles;
            }
            if (g_map_width_tiles <= iVar13) {
              iVar13 = iVar13 - g_map_width_tiles;
            }
            switch(g_map_size_mode) {
            case 0:
              iVar9 = iVar13 + uVar11 * 0x138;
              break;
            case 1:
              iVar9 = iVar13 + uVar11 * 0x9c;
              break;
            case 2:
              iVar9 = iVar13 + uVar11 * 0x4e;
              break;
            case 3:
              iVar9 = uVar11 * 0x27 + iVar13;
              break;
            default:
              goto switchD_004b86b7_default;
            }
            puVar5 = _g_land_tiles + iVar9 * 0x40;
switchD_004b86b7_default:
            if (iVar7 == 4) {
              if (-1 < *(char *)((int)puVar5 + 0x16)) {
                *(undefined1 *)((int)puVar5 + 0x16) = 0xff;
              }
            }
            else if ((iVar7 == 3) && ('\0' < *(char *)(puVar5 + 2))) {
              FUN_004b8820(iVar13,uVar11);
            }
            local_140 = 8;
            iVar9 = (uVar11 & 1) << 5;
            do {
              Decode_Road(*(int *)((int)&DAT_00589374 + iVar9) + iVar13,
                          *(int *)((int)&DAT_005893b4 + iVar9) + uVar11);
              iVar9 = iVar9 + 4;
              local_140 = local_140 + -1;
              iVar7 = g_editor_tool_mode;
            } while (local_140 != 0);
          }
          local_148 = local_148 + 1;
        } while (local_148 <= *(int *)(&DAT_0074a360 + local_134[g_editor_brush_size_index] * 4));
      }
      break;
    case 5:
      local_140 = local_134[g_editor_brush_size_index];
      if (g_editor_overlay_kind == 4) {
        local_140 = 0;
      }
      pcVar3 = (char *)(_DAT_0075590c & 1);
      local_148 = 0;
      iVar7 = g_editor_overlay_kind;
      pcVar10 = pcVar3;
      if (-1 < *(int *)(&DAT_0074a360 + local_140 * 4)) {
        do {
          psVar1 = (short *)((int)g_edit_dest_round_buffers[(int)pcVar3] + local_148 * 8);
          local_13c = *psVar1 + _DAT_00755908;
          uVar11 = (int)psVar1[1] + _DAT_0075590c;
          if (((-1 < (int)uVar11) && ((int)uVar11 < g_map_height_tiles)) &&
             (((-1 < local_13c && (local_13c < g_map_width_tiles)) ||
              (g_current_map_scenario_info.horizontal_wrap_enabled == 1)))) {
            if (local_13c < 0) {
              local_13c = local_13c + g_map_width_tiles;
            }
            if (g_map_width_tiles <= local_13c) {
              local_13c = local_13c - g_map_width_tiles;
            }
            switch(g_map_size_mode) {
            case 0:
              iVar13 = local_13c + uVar11 * 0x138;
              break;
            case 1:
              iVar13 = local_13c + uVar11 * 0x9c;
              break;
            case 2:
              iVar13 = local_13c + uVar11 * 0x4e;
              break;
            case 3:
              iVar13 = uVar11 * 0x27 + local_13c;
              break;
            default:
              goto switchD_004b8314_default;
            }
            pcVar10 = (char *)(_g_land_tiles + iVar13 * 0x40);
switchD_004b8314_default:
            local_138 = 1;
            if (g_editor_overlay_action < 0) {
              switch(iVar7) {
              case 0:
              case 1:
              case 2:
                if (-1 < pcVar10[0x13]) {
                  pcVar10[0x13] = -1;
                  pcVar10[0x14] = -1;
                }
                break;
              case 3:
                if (-1 < pcVar10[0x15]) {
                  pcVar10[0x15] = -1;
                  pcVar10[0x13] = -1;
                  pcVar10[0x14] = -1;
                }
                break;
              case 4:
                pcVar10[0x24] = -1;
                break;
              case 5:
                if (*pcVar10 < '\v') {
                  *pcVar10 = pcVar10[1];
                }
                local_138 = 2;
                pcVar10[2] = pcVar10[1];
              }
            }
            else {
              g_current_land_tile->field_0x1a = 0xff;
            }
            iVar13 = 0;
            iVar7 = g_editor_overlay_kind;
            if (-1 < *(int *)(&DAT_0074a360 + local_138 * 4)) {
              do {
                iVar7 = *(short *)((int)g_edit_dest_round_buffers[uVar11 & 1] + iVar13 * 8) +
                        local_13c;
                iVar9 = (int)*(short *)((int)g_edit_dest_round_buffers[uVar11 & 1] + iVar13 * 8 + 2)
                        + uVar11;
                switch(g_editor_overlay_kind) {
                case 0:
                case 1:
                case 2:
                  Decode_Road(iVar7,iVar9);
                  break;
                case 4:
                  Decode_LongWall(iVar7,iVar9);
                  break;
                case 5:
                  Decode_NewMap(iVar7,iVar9);
                }
                iVar13 = iVar13 + 1;
                iVar7 = g_editor_overlay_kind;
              } while (iVar13 <= *(int *)(&DAT_0074a360 + local_138 * 4));
            }
          }
          local_148 = local_148 + 1;
          if (*(int *)(&DAT_0074a360 + local_140 * 4) < local_148) {
            DAT_00588b80 = 1;
            return;
          }
        } while( true );
      }
      break;
    case 6:
      g_current_land_tile->city_resource_or_feature_id = 0xff;
      g_current_land_tile->city_resource_or_feature_stockpile = 0;
      DAT_00588b80 = 1;
      return;
    case 9:
      if (((g_editor_selected_country_id < 0) || (0x15 < g_editor_selected_country_id)) ||
         ((char)(&g_country_states)[g_editor_selected_country_id * 0xe68] < '\x01')) {
        FUN_00469f90(&DAT_0057f2fc,1);
        DAT_00588b80 = 1;
        return;
      }
      local_148 = 0;
      puVar4 = (undefined4 *)(_DAT_0075590c & 1);
      puVar5 = puVar4;
      uVar11 = _DAT_0075590c;
      iVar7 = g_map_width_tiles;
      puVar6 = _g_land_tiles;
      iVar13 = g_editor_selected_country_id;
      if (-1 < *(int *)(&DAT_0074a360 + local_134[g_editor_brush_size_index] * 4)) {
        do {
          psVar1 = (short *)((int)g_edit_dest_round_buffers[(int)puVar4] + local_148 * 8);
          iVar9 = *psVar1 + _DAT_00755908;
          iVar8 = (int)psVar1[1] + uVar11;
          if (((-1 < iVar8) && (iVar8 < g_map_height_tiles)) &&
             (((-1 < iVar9 && (iVar9 < iVar7)) ||
              (g_current_map_scenario_info.horizontal_wrap_enabled == 1)))) {
            if (iVar9 < 0) {
              iVar9 = iVar9 + iVar7;
            }
            if (iVar7 <= iVar9) {
              iVar9 = iVar9 - iVar7;
            }
            switch(g_map_size_mode) {
            case 0:
              iVar9 = iVar9 + iVar8 * 0x138;
              break;
            case 1:
              iVar9 = iVar9 + iVar8 * 0x9c;
              break;
            case 2:
              iVar9 = iVar9 + iVar8 * 0x4e;
              break;
            case 3:
              iVar9 = iVar8 * 0x27 + iVar9;
              break;
            default:
              goto switchD_004b8555_default;
            }
            puVar5 = puVar6 + iVar9 * 0x40;
switchD_004b8555_default:
            iVar7 = g_map_width_tiles;
            if ((*(char *)(puVar5 + 0x14) == '\0') && (puVar5[0x22] == 0)) {
              *(undefined1 *)((int)puVar5 + iVar13 + 0xb5) = 0;
              *(undefined1 *)((int)puVar5 + 0x25) = 0xff;
              *(undefined1 *)((int)puVar5 + 0x27) = 0xff;
              uVar11 = _DAT_0075590c;
              iVar7 = g_map_width_tiles;
              puVar6 = _g_land_tiles;
              iVar13 = g_editor_selected_country_id;
            }
          }
          local_148 = local_148 + 1;
          if (*(int *)(&DAT_0074a360 + local_134[g_editor_brush_size_index] * 4) < local_148) {
            DAT_00588b80 = 1;
            return;
          }
        } while( true );
      }
    }
    DAT_00588b80 = 1;
  }
  return;
}
