/*
 * Generated by Ghidra headless decompiler from China2EX_fontfix8.exe.
 * Address request: 0x004b80c0
 * This is reconstructed pseudocode, not original source.
 */


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void Read_MRP_Edit(void)

{
  short *psVar1;
  void *pvVar2;
  char *pcVar3;
  undefined4 *puVar4;
  undefined4 *puVar5;
  undefined4 *puVar6;
  int iVar7;
  int iVar8;
  int iVar9;
  int iVar10;
  char *pcVar11;
  uint uVar12;
  LandTile_0x100 *pLVar13;
  int iVar14;
  int local_148;
  int local_140;
  int local_13c;
  int local_138;
  int local_134 [4];
  undefined1 local_124 [284];
  undefined4 uStack_8;
  char *pcStack_4;

  pcStack_4 = s_Mouse_MRP_0057f8c0;
  uStack_8 = 0x4b80ca;
  Trace_Function();
  if ((g_editor_mode_enabled == 0) || (g_editor_form_input_blocked != 0)) {
    return;
  }
  Trace_Function(s_Read_MRP_Edit_0057f8e0);
  if ((((DAT_00758530 == 0) && (-1 < g_editor_cursor_tile_x)) && (-1 < g_editor_cursor_tile_y)) &&
     ((g_editor_cursor_tile_x < g_map_width_tiles && (g_editor_cursor_tile_y < g_map_height_tiles)))
     ) {
    if (g_editor_map_backup_state != 1) {
      g_editor_map_backup_state = 1;
      puVar5 = _g_land_tiles;
      pLVar13 = g_editor_land_tile_backup;
      for (iVar7 = (g_map_height_tiles * g_map_width_tiles & 0xffffffU) << 6; iVar7 != 0;
          iVar7 = iVar7 + -1) {
        *(undefined4 *)pLVar13 = *puVar5;
        puVar5 = puVar5 + 1;
        pLVar13 = (LandTile_0x100 *)&pLVar13->field_0x4;
      }
      for (iVar7 = 0; iVar7 != 0; iVar7 = iVar7 + -1) {
        *(undefined1 *)pLVar13 = *(undefined1 *)puVar5;
        puVar5 = (undefined4 *)((int)puVar5 + 1);
        pLVar13 = (LandTile_0x100 *)&pLVar13->field_0x1;
      }
    }
    local_134[0] = 0;
    local_134[1] = 1;
    local_134[2] = 2;
    local_134[3] = 4;
    switch(g_editor_tool_mode) {
    case 1:
      pvVar2 = g_current_land_tile->linked_record;
      if (pvVar2 != (void *)0x0) {
        Format_Text(local_124,&DAT_0057f8cc,(int)pvVar2 + 3);
        iVar7 = UI_YesNo_Dialog(local_124,0,0,0xffffffff,0,0xffffffff,0,DAT_007350b4);
        if (iVar7 == 1) {
          FUN_0047b0c0(pvVar2);
          g_request_redraw = 1;
          return;
        }
      }
      break;
    case 2:
      if ('\0' < (char)g_current_land_tile->army_count_or_occupant_count) {
        Cancel_All_Army_On_Tile(g_current_land_tile);
        g_request_redraw = 1;
        return;
      }
      break;
    default:
      puVar6 = (undefined4 *)(g_editor_cursor_tile_y & 1);
      local_148 = 0;
      iVar7 = g_editor_tool_mode;
      puVar5 = puVar6;
      if (-1 < g_tile_radius_offset_counts[local_134[g_editor_brush_size_index]]) {
        do {
          iVar14 = *(short *)((int)g_edit_dest_round_buffers[(int)puVar6] + local_148 * 8) +
                   g_editor_cursor_tile_x;
          uVar12 = *(short *)((int)g_edit_dest_round_buffers[(int)puVar6] + local_148 * 8 + 2) +
                   g_editor_cursor_tile_y;
          if (((-1 < (int)uVar12) && ((int)uVar12 < g_map_height_tiles)) &&
             (((-1 < iVar14 && (iVar14 < g_map_width_tiles)) ||
              (g_current_map_scenario_info.horizontal_wrap_setting == 1)))) {
            if (iVar14 < 0) {
              iVar14 = iVar14 + g_map_width_tiles;
            }
            if (g_map_width_tiles <= iVar14) {
              iVar14 = iVar14 - g_map_width_tiles;
            }
            switch(g_map_size_mode) {
            case 0:
              iVar10 = iVar14 + uVar12 * 0x138;
              break;
            case 1:
              iVar10 = iVar14 + uVar12 * 0x9c;
              break;
            case 2:
              iVar10 = iVar14 + uVar12 * 0x4e;
              break;
            case 3:
              iVar10 = uVar12 * 0x27 + iVar14;
              break;
            default:
              goto switchD_004b86b7_default;
            }
            puVar5 = _g_land_tiles + iVar10 * 0x40;
switchD_004b86b7_default:
            if (iVar7 == 4) {
              if (-1 < *(char *)((int)puVar5 + 0x16)) {
                *(undefined1 *)((int)puVar5 + 0x16) = 0xff;
              }
            }
            else if ((iVar7 == 3) && ('\0' < *(char *)(puVar5 + 2))) {
              Clear_Mountain(iVar14,uVar12);
            }
            local_140 = 8;
            iVar10 = (uVar12 & 1) << 5;
            do {
              Decode_Road(*(int *)((int)&DAT_00589374 + iVar10) + iVar14,
                          *(int *)((int)&DAT_005893b4 + iVar10) + uVar12);
              iVar10 = iVar10 + 4;
              local_140 = local_140 + -1;
              iVar7 = g_editor_tool_mode;
            } while (local_140 != 0);
          }
          local_148 = local_148 + 1;
        } while (local_148 <= g_tile_radius_offset_counts[local_134[g_editor_brush_size_index]]);
      }
      break;
    case 5:
      local_140 = local_134[g_editor_brush_size_index];
      if (g_editor_overlay_kind == 4) {
        local_140 = 0;
      }
      pcVar3 = (char *)(g_editor_cursor_tile_y & 1);
      local_148 = 0;
      iVar7 = g_editor_overlay_kind;
      pcVar11 = pcVar3;
      if (-1 < g_tile_radius_offset_counts[local_140]) {
        do {
          psVar1 = (short *)((int)g_edit_dest_round_buffers[(int)pcVar3] + local_148 * 8);
          local_13c = *psVar1 + g_editor_cursor_tile_x;
          uVar12 = psVar1[1] + g_editor_cursor_tile_y;
          if (((-1 < (int)uVar12) && ((int)uVar12 < g_map_height_tiles)) &&
             (((-1 < local_13c && (local_13c < g_map_width_tiles)) ||
              (g_current_map_scenario_info.horizontal_wrap_setting == 1)))) {
            if (local_13c < 0) {
              local_13c = local_13c + g_map_width_tiles;
            }
            if (g_map_width_tiles <= local_13c) {
              local_13c = local_13c - g_map_width_tiles;
            }
            switch(g_map_size_mode) {
            case 0:
              iVar14 = local_13c + uVar12 * 0x138;
              break;
            case 1:
              iVar14 = local_13c + uVar12 * 0x9c;
              break;
            case 2:
              iVar14 = local_13c + uVar12 * 0x4e;
              break;
            case 3:
              iVar14 = uVar12 * 0x27 + local_13c;
              break;
            default:
              goto switchD_004b8314_default;
            }
            pcVar11 = (char *)(_g_land_tiles + iVar14 * 0x40);
switchD_004b8314_default:
            local_138 = 1;
            if (g_editor_overlay_action < 0) {
              switch(iVar7) {
              case 0:
              case 1:
              case 2:
                if (-1 < pcVar11[0x13]) {
                  pcVar11[0x13] = -1;
                  pcVar11[0x14] = -1;
                }
                break;
              case 3:
                if (-1 < pcVar11[0x15]) {
                  pcVar11[0x15] = -1;
                  pcVar11[0x13] = -1;
                  pcVar11[0x14] = -1;
                }
                break;
              case 4:
                pcVar11[0x24] = -1;
                break;
              case 5:
                if (*pcVar11 < '\v') {
                  *pcVar11 = pcVar11[1];
                }
                local_138 = 2;
                pcVar11[2] = pcVar11[1];
              }
            }
            else {
              g_current_land_tile->tile_work_kind = 0xff;
            }
            iVar14 = 0;
            iVar7 = g_editor_overlay_kind;
            if (-1 < g_tile_radius_offset_counts[local_138]) {
              do {
                iVar7 = *(short *)((int)g_edit_dest_round_buffers[uVar12 & 1] + iVar14 * 8) +
                        local_13c;
                iVar10 = (int)*(short *)((int)g_edit_dest_round_buffers[uVar12 & 1] + iVar14 * 8 + 2
                                        ) + uVar12;
                switch(g_editor_overlay_kind) {
                case 0:
                case 1:
                case 2:
                  Decode_Road(iVar7,iVar10);
                  break;
                case 4:
                  Decode_LongWall(iVar7,iVar10);
                  break;
                case 5:
                  Decode_NewMap(iVar7,iVar10);
                }
                iVar14 = iVar14 + 1;
                iVar7 = g_editor_overlay_kind;
              } while (iVar14 <= g_tile_radius_offset_counts[local_138]);
            }
          }
          local_148 = local_148 + 1;
          if (g_tile_radius_offset_counts[local_140] < local_148) {
            g_request_redraw = 1;
            return;
          }
        } while( true );
      }
      break;
    case 6:
      g_current_land_tile->city_resource_or_feature_id = 0xff;
      g_current_land_tile->city_resource_or_feature_stockpile = 0;
      g_request_redraw = 1;
      return;
    case 9:
      if (((g_editor_selected_country_id < 0) || (0x15 < g_editor_selected_country_id)) ||
         ((char)(&g_country_states)[g_editor_selected_country_id * 0xe68] < '\x01')) {
        FUN_00469f90(&DAT_0057f2fc,1);
        g_request_redraw = 1;
        return;
      }
      local_148 = 0;
      puVar4 = (undefined4 *)(g_editor_cursor_tile_y & 1);
      puVar5 = puVar4;
      iVar7 = g_editor_cursor_tile_y;
      iVar14 = g_map_width_tiles;
      puVar6 = _g_land_tiles;
      iVar10 = g_editor_selected_country_id;
      if (-1 < g_tile_radius_offset_counts[local_134[g_editor_brush_size_index]]) {
        do {
          psVar1 = (short *)((int)g_edit_dest_round_buffers[(int)puVar4] + local_148 * 8);
          iVar9 = *psVar1 + g_editor_cursor_tile_x;
          iVar8 = psVar1[1] + iVar7;
          if (((-1 < iVar8) && (iVar8 < g_map_height_tiles)) &&
             (((-1 < iVar9 && (iVar9 < iVar14)) ||
              (g_current_map_scenario_info.horizontal_wrap_setting == 1)))) {
            if (iVar9 < 0) {
              iVar9 = iVar9 + iVar14;
            }
            if (iVar14 <= iVar9) {
              iVar9 = iVar9 - iVar14;
            }
            switch(g_map_size_mode) {
            case 0:
              iVar9 = iVar9 + iVar8 * 0x138;
              break;
            case 1:
              iVar9 = iVar9 + iVar8 * 0x9c;
              break;
            case 2:
              iVar9 = iVar9 + iVar8 * 0x4e;
              break;
            case 3:
              iVar9 = iVar8 * 0x27 + iVar9;
              break;
            default:
              goto switchD_004b8555_default;
            }
            puVar5 = puVar6 + iVar9 * 0x40;
switchD_004b8555_default:
            iVar14 = g_map_width_tiles;
            if ((*(char *)(puVar5 + 0x14) == '\0') && (puVar5[0x22] == 0)) {
              *(undefined1 *)((int)puVar5 + iVar10 + 0xb5) = 0;
              *(undefined1 *)((int)puVar5 + 0x25) = 0xff;
              *(undefined1 *)((int)puVar5 + 0x27) = 0xff;
              iVar7 = g_editor_cursor_tile_y;
              iVar14 = g_map_width_tiles;
              puVar6 = _g_land_tiles;
              iVar10 = g_editor_selected_country_id;
            }
          }
          local_148 = local_148 + 1;
          if (g_tile_radius_offset_counts[local_134[g_editor_brush_size_index]] < local_148) {
            g_request_redraw = 1;
            return;
          }
        } while( true );
      }
    }
    g_request_redraw = 1;
  }
  return;
}
