/*
 * Generated by Ghidra headless decompiler from China2EX_fontfix8.exe.
 * Address request: 0x004c2da0
 * This is reconstructed pseudocode, not original source.
 */


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void Apply_Resolution_Mode(int param_1,char param_2)

{
  int iVar1;

  Trace_Function(s_Screen_Size_00588638);
  if (param_1 != g_resolution_mode_index) {
    g_client_width = g_resolution_width_table[param_1];
    g_resolution_mode_index = param_1;
    g_client_height = g_resolution_height_table[param_1];
    _DAT_00588b98 = g_client_width + -1;
    _DAT_00588b9c = g_client_height + -1;
    _DAT_00734c1c = (g_client_height + 1) * (g_client_width + 1) * 2;
    if (param_2 == '\0') {
      FUN_0048b5a0();
    }
    Create_Back_Surface((int)(char)g_resolution_mode_index);
    if (param_2 == '\0') {
      FUN_0048b6e0();
    }
    FUN_004c2c20();
    iVar1 = (DAT_0074d340 - _DAT_00749d50) + 1;
    _DAT_00734c18 = iVar1 * _DAT_00749d54 * 2;
    _DAT_00734c20 = ((DAT_0074d33c - _DAT_00749d54) + 1) * iVar1 * 2;
    g_center_offset_x_from_800 = (g_client_width + -800) / 2;
    g_center_offset_y_from_600 = (g_client_height + -600) / 2;
    if (DAT_00758524 != 0) {
      for (iVar1 = *(int *)(DAT_00758524 + 0xc4); iVar1 != 0; iVar1 = *(int *)(iVar1 + 0xc4)) {
        if ((0 < *(int *)(iVar1 + 8)) && (*(int *)(iVar1 + 0x3c) != 0)) {
          if (DAT_00755810 < *(int *)(iVar1 + 0x1c) + *(int *)(iVar1 + 0x24)) {
            *(int *)(iVar1 + 0x1c) = (DAT_00755810 - *(int *)(iVar1 + 0x24)) + 1;
          }
          if (DAT_00755814 < *(int *)(iVar1 + 0x20) + *(int *)(iVar1 + 0x28)) {
            *(int *)(iVar1 + 0x20) = (DAT_00755814 - *(int *)(iVar1 + 0x28)) + 1;
          }
          if (*(int *)(iVar1 + 0x1c) < 0) {
            *(undefined4 *)(iVar1 + 0x1c) = 0;
          }
          if (*(int *)(iVar1 + 0x20) < 0) {
            *(undefined4 *)(iVar1 + 0x20) = 0;
          }
        }
      }
    }
  }
  return;
}
