/*
 * Generated by Ghidra headless decompiler from China2EX_fontfix8.exe.
 * Address request: 0x004af8f0
 * This is reconstructed pseudocode, not original source.
 */


void Build_Dark_Table(void)

{
  int iVar1;
  int iVar2;
  undefined4 *puVar3;

  iVar2 = 0;
  puVar3 = g_dark_table_buffer;
  for (iVar1 = 0x78000; iVar1 != 0; iVar1 = iVar1 + -1) {
    *puVar3 = 0;
    puVar3 = puVar3 + 1;
  }
  do {
    Build_Dark_Table_From_Fade_Frame(iVar2,*(undefined4 *)(DAT_00758594 + iVar2 * 4));
    iVar2 = iVar2 + 1;
  } while (iVar2 < 0x50);
  return;
}
