/*
 * Generated by Ghidra headless decompiler from China2EX_fontfix8.exe.
 * Address request: 0x00468320
 * This is reconstructed pseudocode, not original source.
 */


void MakeColorTable(int param_1,byte param_2)

{
  int iVar1;
  uint uVar2;
  int iVar3;
  int iVar4;
  int iVar5;
  uint uVar6;
  uint uVar7;
  int iVar8;
  int iVar9;
  uint uVar10;
  uint uVar11;
  uint uVar12;
  int iVar13;
  uint local_4c;
  uint local_48;
  uint local_44 [3];
  int local_38;
  uint local_34;
  int local_30;
  uint local_2c;
  uint local_28;
  uint local_24;
  int local_20;
  int local_1c;
  int local_18;
  uint local_14;
  uint local_10;
  uint local_c;
  uint local_8;
  int local_4;

  Trace_Function(s_MakeColorTable_005738f0);
  local_44[2] = 1 << (g_pixel_red_bits & 0x1f);
  local_38 = 1 << (g_pixel_green_bits & 0x1f);
  local_30 = 1 << (g_pixel_blue_bits & 0x1f);
  local_8 = 0;
  uVar10 = local_44[0];
  uVar12 = local_48;
  do {
    local_24 = (uint)g_pixel_red_shift;
    local_10 = (g_pixel_red_mask & local_8) >> (g_pixel_red_shift & 0x1f);
    local_28 = (uint)g_pixel_green_shift;
    local_c = (g_pixel_green_mask & local_8) >> (g_pixel_green_shift & 0x1f);
    local_2c = (uint)g_pixel_blue_shift;
    local_14 = (g_pixel_blue_mask & local_8) >> (g_pixel_blue_shift & 0x1f);
    if (local_44[2] == local_38) {
      local_44[1] = 0x3f800000;
      uVar2 = local_c;
    }
    else {
      local_44[1] = 0x40000000;
      uVar2 = (int)local_c / 2;
    }
    local_4 = local_14 * 8;
    local_18 = uVar2 * 8;
    local_1c = local_10 * 8;
    iVar13 = local_18;
    if (local_18 <= local_4) {
      iVar13 = local_4;
    }
    local_20 = local_1c;
    if ((local_1c <= iVar13) && (local_20 = local_18, local_18 <= local_4)) {
      local_20 = local_4;
    }
    iVar13 = local_18;
    if (local_4 <= local_18) {
      iVar13 = local_4;
    }
    iVar8 = local_1c;
    if ((iVar13 <= local_1c) && (iVar8 = local_18, local_4 <= local_18)) {
      iVar8 = local_4;
    }
    iVar8 = local_20 - iVar8;
    iVar13 = local_20 * 100 + 0x80;
    iVar13 = (int)(iVar13 + (iVar13 >> 0x1f & 0xffU)) >> 8;
    if (local_20 == 0) {
      iVar3 = 0;
LAB_00468495:
      iVar8 = 0;
    }
    else {
      iVar3 = (iVar8 * 100) / local_20;
      if (iVar3 == 0) goto LAB_00468495;
      if (local_1c == local_20) {
        iVar8 = (int)((local_18 + local_14 * -8) * 0x3c) / iVar8;
      }
      else if (local_18 == local_20) {
        iVar8 = (int)((local_4 + local_10 * -8) * 0x3c) / iVar8 + 0x78;
      }
      else {
        iVar8 = (int)((local_1c + uVar2 * -8) * 0x3c) / iVar8 + 0xf0;
      }
      if (iVar8 < 0) {
        iVar8 = iVar8 + 0x168;
      }
    }
    local_34 = local_8;
    if (0x15 < param_2) {
      if (param_2 == 0x16) {
        uVar12 = (int)((((int)(iVar13 - 0x1eU) < 0) - 1 & iVar13 - 0x1eU) << 8) / 100;
        if (uVar12 == 0) {
LAB_004688d1:
          local_44[0] = 0;
          local_4c = 0;
          local_48 = 0;
        }
        else {
          if (0x167 < iVar8) {
            iVar8 = iVar8 + -0x168;
          }
          uVar10 = (int)((100 - iVar3) * uVar12) / 100;
          uVar2 = (int)((6000 - (iVar8 % 0x3c) * iVar3) * uVar12) / 6000;
          uVar6 = (int)((6000 - (0x3c - iVar8 % 0x3c) * iVar3) * uVar12) / 6000;
          local_4c = uVar10;
          uVar7 = uVar10;
          uVar11 = uVar12;
          switch(iVar8 / 0x3c) {
          case 0:
switchD_004685cb_caseD_0:
            break;
          case 1:
switchD_004685cb_caseD_1:
            local_4c = uVar2;
            uVar6 = uVar10;
          case 2:
switchD_004685cb_caseD_2:
            uVar7 = uVar6;
            uVar11 = local_4c;
            uVar6 = uVar12;
            break;
          case 3:
switchD_004685cb_caseD_3:
            local_4c = uVar2;
            uVar7 = uVar12;
            uVar11 = uVar10;
            uVar6 = local_4c;
            break;
          case 4:
switchD_004685cb_caseD_4:
            uVar7 = uVar12;
            uVar11 = uVar6;
            uVar6 = uVar10;
            break;
          case 5:
switchD_004685cb_caseD_5:
            local_4c = uVar2;
            uVar7 = local_4c;
            uVar11 = uVar12;
            uVar6 = uVar10;
            break;
          default:
switchD_004685cb_default:
            uVar7 = 0;
            uVar11 = 0;
            uVar6 = 0;
          }
          local_4c = (int)(uVar6 + 4 + ((int)(uVar6 + 4) >> 0x1f & 7U)) >> 3;
          local_48 = (int)(uVar11 + 4 + ((int)(uVar11 + 4) >> 0x1f & 7U)) >> 3;
          local_44[0] = (int)(uVar7 + 4 + ((int)(uVar7 + 4) >> 0x1f & 7U)) >> 3;
        }
LAB_004688e1:
        uVar10 = local_44[0];
        uVar12 = local_48;
        local_4c = __ftol();
        if ((int)local_44[2] <= (int)uVar12) {
LAB_00468c1e:
          uVar12 = local_44[2] - 1;
          local_48 = uVar12;
        }
LAB_00468c25:
        if (local_38 <= (int)local_4c) {
LAB_00468a6f:
          local_4c = local_38 - 1;
        }
LAB_00468a76:
        if (local_30 <= (int)uVar10) {
          uVar10 = local_30 - 1;
          local_44[0] = uVar10;
        }
        local_34 = uVar10 << ((byte)local_2c & 0x1f) & 0xffff |
                   local_4c << ((byte)local_28 & 0x1f) & 0xffff |
                   uVar12 << ((byte)local_24 & 0x1f) & 0xffff;
      }
      else {
        if (param_2 != 0x17) {
          if (param_2 == 0x18) {
            if (((int)local_10 < (int)local_14) || ((int)local_c < (int)local_14)) {
              iVar8 = iVar8 + -0xb4;
              if (iVar8 < 0) {
                iVar8 = 0;
              }
              else if (0x168 < iVar8) {
                iVar8 = 0x168;
              }
              uVar12 = (iVar13 << 8) / 100;
              if (uVar12 != 0) {
                if (0x167 < iVar8) {
                  iVar8 = iVar8 + -0x168;
                }
                uVar10 = (int)((100 - iVar3) * uVar12) / 100;
                uVar2 = (int)((6000 - (iVar8 % 0x3c) * iVar3) * uVar12) / 6000;
                uVar6 = (int)((6000 - (0x3c - iVar8 % 0x3c) * iVar3) * uVar12) / 6000;
                local_4c = uVar10;
                uVar7 = uVar10;
                uVar11 = uVar12;
                switch(iVar8 / 0x3c) {
                case 0:
                  goto switchD_004685cb_caseD_0;
                case 1:
                  goto switchD_004685cb_caseD_1;
                case 2:
                  goto switchD_004685cb_caseD_2;
                case 3:
                  goto switchD_004685cb_caseD_3;
                case 4:
                  goto switchD_004685cb_caseD_4;
                case 5:
                  goto switchD_004685cb_caseD_5;
                default:
                  goto switchD_004685cb_default;
                }
              }
              goto LAB_004688d1;
            }
            goto LAB_0046986a;
          }
          if (param_2 != 0x19) {
            if (param_2 != 0x1a) goto LAB_0046986a;
            iVar8 = iVar8 + 0x1e;
            if (0x167 < iVar8) {
              iVar8 = 0x168;
            }
            iVar13 = (iVar13 << 8) / 100;
            if (iVar13 == 0) {
              local_44[0] = 0;
              local_4c = 0;
              local_48 = 0;
            }
            else {
              if (0x167 < iVar8) {
                iVar8 = iVar8 + -0x168;
              }
              iVar4 = ((100 - iVar3) * iVar13) / 100;
              iVar1 = ((6000 - (iVar8 % 0x3c) * iVar3) * iVar13) / 6000;
              iVar3 = ((6000 - (0x3c - iVar8 % 0x3c) * iVar3) * iVar13) / 6000;
              iVar5 = iVar13;
              iVar9 = iVar13;
              switch(iVar8 / 0x3c) {
              case 0:
                iVar5 = iVar4;
                break;
              case 1:
                iVar3 = iVar4;
                iVar4 = iVar1;
              case 2:
                iVar5 = iVar3;
                iVar9 = iVar4;
                iVar3 = iVar13;
                break;
              case 3:
                iVar9 = iVar4;
                iVar3 = iVar1;
                break;
              case 4:
                iVar9 = iVar3;
                iVar3 = iVar4;
                break;
              case 5:
                iVar5 = iVar1;
                iVar3 = iVar4;
                break;
              default:
                iVar5 = 0;
                iVar9 = 0;
                iVar3 = 0;
              }
              local_4c = (int)(iVar3 + 4 + (iVar3 + 4 >> 0x1f & 7U)) >> 3;
              local_48 = (int)(iVar9 + 4 + (iVar9 + 4 >> 0x1f & 7U)) >> 3;
              local_44[0] = (int)(iVar5 + 4 + (iVar5 + 4 >> 0x1f & 7U)) >> 3;
            }
            uVar10 = local_44[0];
            uVar12 = local_48;
            local_4c = __ftol();
            if ((int)local_44[2] <= (int)uVar12) goto LAB_00468c1e;
            goto LAB_00468c25;
          }
          iVar8 = iVar8 + -0x1e;
          if (iVar8 < 0) {
            iVar8 = 0;
          }
          iVar13 = (iVar13 << 8) / 100;
          if (iVar13 == 0) {
            local_44[0] = 0;
            local_4c = 0;
            local_48 = 0;
          }
          else {
            if (0x167 < iVar8) {
              iVar8 = iVar8 + -0x168;
            }
            iVar4 = ((100 - iVar3) * iVar13) / 100;
            iVar1 = ((6000 - (iVar8 % 0x3c) * iVar3) * iVar13) / 6000;
            iVar3 = ((6000 - (0x3c - iVar8 % 0x3c) * iVar3) * iVar13) / 6000;
            iVar5 = iVar13;
            iVar9 = iVar13;
            switch(iVar8 / 0x3c) {
            case 0:
              iVar5 = iVar4;
              break;
            case 1:
              iVar3 = iVar4;
              iVar4 = iVar1;
            case 2:
              iVar5 = iVar3;
              iVar9 = iVar4;
              iVar3 = iVar13;
              break;
            case 3:
              iVar9 = iVar4;
              iVar3 = iVar1;
              break;
            case 4:
              iVar9 = iVar3;
              iVar3 = iVar4;
              break;
            case 5:
              iVar5 = iVar1;
              iVar3 = iVar4;
              break;
            default:
              iVar5 = 0;
              iVar9 = 0;
              iVar3 = 0;
            }
            local_4c = (int)(iVar3 + 4 + (iVar3 + 4 >> 0x1f & 7U)) >> 3;
            local_48 = (int)(iVar9 + 4 + (iVar9 + 4 >> 0x1f & 7U)) >> 3;
            local_44[0] = (int)(iVar5 + 4 + (iVar5 + 4 >> 0x1f & 7U)) >> 3;
          }
          uVar10 = local_44[0];
          uVar12 = local_48;
          local_4c = __ftol();
          if ((int)local_44[2] <= (int)uVar12) {
            uVar12 = local_44[2] - 1;
            local_48 = uVar12;
          }
          if (local_38 <= (int)local_4c) goto LAB_00468a6f;
          goto LAB_00468a76;
        }
        if (((int)local_10 < (int)local_14) || ((int)local_c < (int)local_14)) {
          iVar3 = iVar3 + -0x5a;
          if (iVar3 < 0) {
            iVar3 = 0;
          }
          iVar13 = iVar13 + 0x23;
          if (100 < iVar13) {
            iVar13 = 100;
          }
          iVar13 = (iVar13 << 8) / 100;
          if (iVar13 == 0) {
            iVar13 = 0;
            iVar3 = 0;
            iVar8 = 0;
          }
          else {
            if (0x167 < iVar8) {
              iVar8 = iVar8 + -0x168;
            }
            iVar4 = ((100 - iVar3) * iVar13) / 100;
            iVar1 = ((6000 - (iVar8 % 0x3c) * iVar3) * iVar13) / 6000;
            iVar3 = ((6000 - (0x3c - iVar8 % 0x3c) * iVar3) * iVar13) / 6000;
            iVar5 = iVar13;
            iVar9 = iVar13;
            switch(iVar8 / 0x3c) {
            case 0:
              iVar5 = iVar4;
              break;
            case 1:
              iVar3 = iVar4;
              iVar4 = iVar1;
            case 2:
              iVar5 = iVar3;
              iVar9 = iVar4;
              iVar3 = iVar13;
              break;
            case 3:
              iVar9 = iVar4;
              iVar3 = iVar1;
              break;
            case 4:
              iVar9 = iVar3;
              iVar3 = iVar4;
              break;
            case 5:
              iVar5 = iVar1;
              iVar3 = iVar4;
              break;
            default:
              iVar5 = 0;
              iVar9 = 0;
              iVar3 = 0;
            }
            iVar8 = (int)(iVar9 + 4 + (iVar9 + 4 >> 0x1f & 7U)) >> 3;
            iVar3 = (int)(iVar3 + 4 + (iVar3 + 4 >> 0x1f & 7U)) >> 3;
            iVar13 = (int)(iVar5 + 4 + (iVar5 + 4 >> 0x1f & 7U)) >> 3;
            if (0x1f < iVar8) {
              local_48 = iVar8 + 10;
              local_4c = iVar3 + 10;
              local_44[0] = iVar13 + 10;
              goto LAB_004688e1;
            }
          }
          local_48 = iVar8 - 10;
          if ((int)local_48 < 0) {
            local_48 = 0;
          }
          local_4c = iVar3 - 10;
          if ((int)local_4c < 0) {
            local_4c = 0;
          }
          local_44[0] = iVar13 - 10;
          if ((int)local_44[0] < 0) {
            local_44[0] = 0;
          }
          goto LAB_004688e1;
        }
      }
      goto LAB_0046986a;
    }
    if ((iVar8 < 0xd7) || (0x103 < iVar8)) goto LAB_0046986a;
    switch(param_2) {
    case 0:
      uVar12 = 0;
      uVar10 = 0;
      local_44[0] = 0;
      local_48 = 0;
      local_4c = 0;
      goto switchD_00468c5c_default;
    case 1:
      uVar10 = local_14;
      uVar12 = local_10;
      local_4c = local_c;
      local_48 = local_10;
      local_44[0] = local_14;
      goto switchD_00468c5c_default;
    case 2:
      iVar8 = iVar8 + 0x78;
      if (0x168 < iVar8) {
        iVar8 = 0x168;
      }
      uVar12 = (iVar13 << 8) / 100;
      if (uVar12 == 0) break;
      if (0x167 < iVar8) {
        iVar8 = iVar8 + -0x168;
      }
      uVar10 = (int)((100 - iVar3) * uVar12) / 100;
      uVar2 = (int)((6000 - (iVar8 % 0x3c) * iVar3) * uVar12) / 6000;
      uVar6 = (int)((6000 - (0x3c - iVar8 % 0x3c) * iVar3) * uVar12) / 6000;
      local_4c = uVar10;
      uVar7 = uVar10;
      uVar11 = uVar12;
      switch(iVar8 / 0x3c) {
      case 0:
switchD_004696a1_caseD_0:
        break;
      case 1:
switchD_004696a1_caseD_1:
        local_4c = uVar2;
        uVar6 = uVar10;
      case 2:
switchD_004696a1_caseD_2:
        uVar7 = uVar6;
        uVar11 = local_4c;
        uVar6 = uVar12;
        break;
      case 3:
switchD_004696a1_caseD_3:
        local_4c = uVar2;
        uVar7 = uVar12;
        uVar11 = uVar10;
        uVar6 = local_4c;
        break;
      case 4:
switchD_004696a1_caseD_4:
        uVar7 = uVar12;
        uVar11 = uVar6;
        uVar6 = uVar10;
        break;
      case 5:
switchD_004696a1_caseD_5:
        local_4c = uVar2;
        uVar7 = local_4c;
        uVar11 = uVar12;
        uVar6 = uVar10;
        break;
      default:
switchD_004696a1_default:
        uVar7 = 0;
        uVar11 = 0;
        uVar6 = 0;
      }
      local_4c = (int)(uVar6 + 4 + ((int)(uVar6 + 4) >> 0x1f & 7U)) >> 3;
      local_48 = (int)(uVar11 + 4 + ((int)(uVar11 + 4) >> 0x1f & 7U)) >> 3;
      local_44[0] = (int)(uVar7 + 4 + ((int)(uVar7 + 4) >> 0x1f & 7U)) >> 3;
      goto LAB_004696b8;
    case 3:
      iVar4 = iVar8 + -0x6e;
      uVar12 = (iVar13 << 8) / 100;
      if (uVar12 != 0) {
        if (0x167 < iVar4) {
          iVar4 = iVar8 + -0x1d6;
        }
        uVar10 = (int)((100 - iVar3) * uVar12) / 100;
        uVar2 = (int)((6000 - (iVar4 % 0x3c) * iVar3) * uVar12) / 6000;
        uVar6 = (int)((6000 - (0x3c - iVar4 % 0x3c) * iVar3) * uVar12) / 6000;
        local_4c = uVar10;
        uVar7 = uVar10;
        uVar11 = uVar12;
        switch(iVar4 / 0x3c) {
        case 0:
          goto switchD_004696a1_caseD_0;
        case 1:
          goto switchD_004696a1_caseD_1;
        case 2:
          goto switchD_004696a1_caseD_2;
        case 3:
          goto switchD_004696a1_caseD_3;
        case 4:
          goto switchD_004696a1_caseD_4;
        case 5:
          goto switchD_004696a1_caseD_5;
        default:
          goto switchD_004696a1_default;
        }
      }
      break;
    case 4:
      iVar4 = 0xb4;
      if (iVar8 < 0xe2) {
        iVar4 = iVar8 + -0x2d;
      }
      iVar8 = iVar8 - iVar4;
      if (iVar8 < 0) {
        iVar8 = iVar8 + 0x168;
      }
      iVar3 = iVar3 + 0x32;
      if (99 < iVar3) {
        iVar3 = 100;
      }
      iVar13 = iVar13 + 0x14;
      if (99 < iVar13) {
        iVar13 = 100;
      }
      uVar12 = (iVar13 << 8) / 100;
      if (uVar12 != 0) {
        if (0x167 < iVar8) {
          iVar8 = iVar8 + -0x168;
        }
        uVar10 = (int)((100 - iVar3) * uVar12) / 100;
        uVar2 = (int)((6000 - (iVar8 % 0x3c) * iVar3) * uVar12) / 6000;
        uVar6 = (int)((6000 - (0x3c - iVar8 % 0x3c) * iVar3) * uVar12) / 6000;
        local_4c = uVar10;
        uVar7 = uVar10;
        uVar11 = uVar12;
        switch(iVar8 / 0x3c) {
        case 0:
          goto switchD_004696a1_caseD_0;
        case 1:
          goto switchD_004696a1_caseD_1;
        case 2:
          goto switchD_004696a1_caseD_2;
        case 3:
          goto switchD_004696a1_caseD_3;
        case 4:
          goto switchD_004696a1_caseD_4;
        case 5:
          goto switchD_004696a1_caseD_5;
        default:
          goto switchD_004696a1_default;
        }
      }
      break;
    case 5:
      if (iVar8 < 0x46) {
        iVar8 = 0;
      }
      else {
        iVar8 = iVar8 + -0x1e;
      }
      if (iVar3 < 0x1e) {
        iVar3 = 0;
      }
      else {
        iVar3 = iVar3 + -0x1e;
      }
      if (iVar13 < 0x32) {
        iVar13 = 0;
      }
      else {
        iVar13 = iVar13 + -0x32;
      }
      uVar12 = (iVar13 << 8) / 100;
      if (uVar12 != 0) {
        if (0x167 < iVar8) {
          iVar8 = iVar8 + -0x168;
        }
        uVar10 = (int)((100 - iVar3) * uVar12) / 100;
        uVar2 = (int)((6000 - (iVar8 % 0x3c) * iVar3) * uVar12) / 6000;
        uVar6 = (int)((6000 - (0x3c - iVar8 % 0x3c) * iVar3) * uVar12) / 6000;
        local_4c = uVar10;
        uVar7 = uVar10;
        uVar11 = uVar12;
        switch(iVar8 / 0x3c) {
        case 0:
          goto switchD_004696a1_caseD_0;
        case 1:
          goto switchD_004696a1_caseD_1;
        case 2:
          goto switchD_004696a1_caseD_2;
        case 3:
          goto switchD_004696a1_caseD_3;
        case 4:
          goto switchD_004696a1_caseD_4;
        case 5:
          goto switchD_004696a1_caseD_5;
        default:
          goto switchD_004696a1_default;
        }
      }
      break;
    case 6:
      iVar4 = 0x3c;
      if (iVar8 < 0xe2) {
        iVar4 = iVar8 + -0xa5;
      }
      iVar8 = iVar8 - iVar4;
      if (iVar8 < 0) {
        iVar8 = iVar8 + 0x168;
      }
      iVar3 = iVar3 + 0x32;
      if (99 < iVar3) {
        iVar3 = 100;
      }
      iVar13 = iVar13 + 10;
      if (99 < iVar13) {
        iVar13 = 100;
      }
      uVar12 = (iVar13 << 8) / 100;
      if (uVar12 != 0) {
        if (0x167 < iVar8) {
          iVar8 = iVar8 + -0x168;
        }
        uVar10 = (int)((100 - iVar3) * uVar12) / 100;
        uVar2 = (int)((6000 - (iVar8 % 0x3c) * iVar3) * uVar12) / 6000;
        uVar6 = (int)((6000 - (0x3c - iVar8 % 0x3c) * iVar3) * uVar12) / 6000;
        local_4c = uVar10;
        uVar7 = uVar10;
        uVar11 = uVar12;
        switch(iVar8 / 0x3c) {
        case 0:
          goto switchD_004696a1_caseD_0;
        case 1:
          goto switchD_004696a1_caseD_1;
        case 2:
          goto switchD_004696a1_caseD_2;
        case 3:
          goto switchD_004696a1_caseD_3;
        case 4:
          goto switchD_004696a1_caseD_4;
        case 5:
          goto switchD_004696a1_caseD_5;
        default:
          goto switchD_004696a1_default;
        }
      }
      break;
    case 7:
      iVar4 = 0x5a;
      if (iVar8 < 0xe2) {
        iVar4 = iVar8 + -0x87;
      }
      iVar8 = iVar8 + iVar4;
      if (0x167 < iVar8) {
        iVar8 = iVar8 + -0x168;
      }
      iVar3 = iVar3 + 0x32;
      if (99 < iVar3) {
        iVar3 = 100;
      }
      if (99 < iVar13) {
        iVar13 = 100;
      }
      uVar12 = (iVar13 << 8) / 100;
      if (uVar12 != 0) {
        if (0x167 < iVar8) {
          iVar8 = iVar8 + -0x168;
        }
        uVar10 = (int)((100 - iVar3) * uVar12) / 100;
        uVar2 = (int)((6000 - (iVar8 % 0x3c) * iVar3) * uVar12) / 6000;
        uVar6 = (int)((6000 - (0x3c - iVar8 % 0x3c) * iVar3) * uVar12) / 6000;
        local_4c = uVar10;
        uVar7 = uVar10;
        uVar11 = uVar12;
        switch(iVar8 / 0x3c) {
        case 0:
          goto switchD_004696a1_caseD_0;
        case 1:
          goto switchD_004696a1_caseD_1;
        case 2:
          goto switchD_004696a1_caseD_2;
        case 3:
          goto switchD_004696a1_caseD_3;
        case 4:
          goto switchD_004696a1_caseD_4;
        case 5:
          goto switchD_004696a1_caseD_5;
        default:
          goto switchD_004696a1_default;
        }
      }
      break;
    case 8:
      iVar4 = 0x136;
      if (iVar8 < 0xe2) {
        iVar4 = iVar8 + 0x55;
      }
      iVar8 = iVar8 - iVar4;
      if (iVar8 < 0) {
        iVar8 = iVar8 + 0x168;
      }
      iVar3 = iVar3 + 0x32;
      if (99 < iVar3) {
        iVar3 = 100;
      }
      iVar13 = iVar13 + 0x1e;
      if (99 < iVar13) {
        iVar13 = 100;
      }
      uVar12 = (iVar13 << 8) / 100;
      if (uVar12 != 0) {
        if (0x167 < iVar8) {
          iVar8 = iVar8 + -0x168;
        }
        uVar10 = (int)((100 - iVar3) * uVar12) / 100;
        uVar2 = (int)((6000 - (iVar8 % 0x3c) * iVar3) * uVar12) / 6000;
        uVar6 = (int)((6000 - (0x3c - iVar8 % 0x3c) * iVar3) * uVar12) / 6000;
        local_4c = uVar10;
        uVar7 = uVar10;
        uVar11 = uVar12;
        switch(iVar8 / 0x3c) {
        case 0:
          goto switchD_004696a1_caseD_0;
        case 1:
          goto switchD_004696a1_caseD_1;
        case 2:
          goto switchD_004696a1_caseD_2;
        case 3:
          goto switchD_004696a1_caseD_3;
        case 4:
          goto switchD_004696a1_caseD_4;
        case 5:
          goto switchD_004696a1_caseD_5;
        default:
          goto switchD_004696a1_default;
        }
      }
      break;
    case 9:
      if (iVar8 < 0xe2) {
        iVar8 = iVar8 + -0x5f;
      }
      else {
        iVar8 = 0x168;
      }
      if (iVar3 < 0x1e) {
        iVar3 = 0;
      }
      else {
        iVar3 = iVar3 + -0x1e;
      }
      if (iVar13 < 0x5b) {
        iVar13 = iVar13 + 10;
      }
      else {
        iVar13 = 100;
      }
      uVar12 = (iVar13 << 8) / 100;
      if (uVar12 != 0) {
        if (0x167 < iVar8) {
          iVar8 = iVar8 + -0x168;
        }
        uVar10 = (int)((100 - iVar3) * uVar12) / 100;
        uVar2 = (int)((6000 - (iVar8 % 0x3c) * iVar3) * uVar12) / 6000;
        uVar6 = (int)((6000 - (0x3c - iVar8 % 0x3c) * iVar3) * uVar12) / 6000;
        local_4c = uVar10;
        uVar7 = uVar10;
        uVar11 = uVar12;
        switch(iVar8 / 0x3c) {
        case 0:
          goto switchD_004696a1_caseD_0;
        case 1:
          goto switchD_004696a1_caseD_1;
        case 2:
          goto switchD_004696a1_caseD_2;
        case 3:
          goto switchD_004696a1_caseD_3;
        case 4:
          goto switchD_004696a1_caseD_4;
        case 5:
          goto switchD_004696a1_caseD_5;
        default:
          goto switchD_004696a1_default;
        }
      }
      break;
    case 10:
      iVar13 = (iVar13 << 8) / 100;
      if (iVar13 == 0) break;
      iVar8 = (iVar13 * 6000) / 6000 + 4;
      local_4c = (int)(iVar8 + (iVar8 >> 0x1f & 7U)) >> 3;
      iVar8 = (iVar13 * 100) / 100 + 4;
      local_48 = (int)(iVar13 + 4 + (iVar13 + 4 >> 0x1f & 7U)) >> 3;
      local_44[0] = (int)(iVar8 + (iVar8 >> 0x1f & 7U)) >> 3;
      goto LAB_004696b8;
    case 0xb:
      iVar4 = 0xbe;
      if (iVar8 < 0xe2) {
        iVar4 = iVar8 + -0x23;
      }
      iVar8 = iVar8 - iVar4;
      if (iVar8 < 0) {
        iVar8 = iVar8 + 0x168;
      }
      iVar3 = iVar3 + 0x32;
      if (99 < iVar3) {
        iVar3 = 100;
      }
      iVar13 = iVar13 + 10;
      if (99 < iVar13) {
        iVar13 = 100;
      }
      uVar12 = (iVar13 << 8) / 100;
      if (uVar12 != 0) {
        if (0x167 < iVar8) {
          iVar8 = iVar8 + -0x168;
        }
        uVar10 = (int)((100 - iVar3) * uVar12) / 100;
        uVar2 = (int)((6000 - (iVar8 % 0x3c) * iVar3) * uVar12) / 6000;
        uVar6 = (int)((6000 - (0x3c - iVar8 % 0x3c) * iVar3) * uVar12) / 6000;
        local_4c = uVar10;
        uVar7 = uVar10;
        uVar11 = uVar12;
        switch(iVar8 / 0x3c) {
        case 0:
          goto switchD_004696a1_caseD_0;
        case 1:
          goto switchD_004696a1_caseD_1;
        case 2:
          goto switchD_004696a1_caseD_2;
        case 3:
          goto switchD_004696a1_caseD_3;
        case 4:
          goto switchD_004696a1_caseD_4;
        case 5:
          goto switchD_004696a1_caseD_5;
        default:
          goto switchD_004696a1_default;
        }
      }
      break;
    case 0xc:
      if (iVar8 < 0x96) {
        iVar8 = 0;
      }
      else {
        iVar8 = iVar8 + -0x96;
      }
      if (iVar3 < 0x32) {
        iVar3 = 0;
      }
      else {
        iVar3 = iVar3 + -0x32;
      }
      uVar12 = (iVar13 << 8) / 100;
      if (uVar12 != 0) {
        if (0x167 < iVar8) {
          iVar8 = iVar8 + -0x168;
        }
        uVar10 = (int)((100 - iVar3) * uVar12) / 100;
        uVar2 = (int)((6000 - (iVar8 % 0x3c) * iVar3) * uVar12) / 6000;
        uVar6 = (int)((6000 - (0x3c - iVar8 % 0x3c) * iVar3) * uVar12) / 6000;
        local_4c = uVar10;
        uVar7 = uVar10;
        uVar11 = uVar12;
        switch(iVar8 / 0x3c) {
        case 0:
          goto switchD_004696a1_caseD_0;
        case 1:
          goto switchD_004696a1_caseD_1;
        case 2:
          goto switchD_004696a1_caseD_2;
        case 3:
          goto switchD_004696a1_caseD_3;
        case 4:
          goto switchD_004696a1_caseD_4;
        case 5:
          goto switchD_004696a1_caseD_5;
        default:
          goto switchD_004696a1_default;
        }
      }
      break;
    case 0xd:
      if (iVar8 < 0x32) {
        iVar8 = 0;
      }
      else {
        iVar8 = iVar8 + -0x32;
      }
      if (iVar3 < 0x1e) {
        iVar3 = 0;
      }
      else {
        iVar3 = iVar3 + -0x1e;
      }
      goto LAB_004697e0;
    case 0xe:
      if (iVar8 < 0x32) {
        iVar8 = 0;
      }
      else {
        iVar8 = iVar8 + -0x32;
      }
      if (iVar3 < 0x1e) {
        iVar3 = 0;
      }
      else {
        iVar3 = iVar3 + -0x1e;
      }
      if (iVar13 < 0x28) {
        iVar13 = 0;
      }
      else {
        iVar13 = iVar13 + -0x28;
      }
      goto LAB_004697e0;
    case 0xf:
      if (iVar8 < 0x47) {
        iVar8 = iVar8 + 0x28;
      }
      else {
        iVar8 = 100;
      }
      if (iVar3 < 0x1e) {
        iVar3 = 0;
      }
      else {
        iVar3 = iVar3 + -0x28;
      }
      if (iVar13 < 0x32) {
        iVar13 = 0;
      }
      else {
        iVar13 = iVar13 + -0x32;
      }
      goto LAB_004697e0;
    case 0x10:
      if (iVar8 < 0x47) {
        iVar8 = iVar8 + 0x3c;
      }
      else {
        iVar8 = 100;
      }
      if (iVar3 < 0x1e) {
        iVar3 = 0;
      }
      else {
        iVar3 = iVar3 + -0x1e;
      }
      if (iVar13 < 0x32) {
        iVar13 = 0;
      }
      else {
        iVar13 = iVar13 + -0x14;
      }
      goto LAB_004697e0;
    case 0x11:
    case 0x13:
    case 0x15:
      if (iVar8 < 0x47) {
        iVar8 = iVar8 + 10;
      }
      else {
        iVar8 = 100;
      }
      if (iVar3 < 0x1e) {
        iVar3 = 0;
      }
      else {
        iVar3 = iVar3 + -10;
      }
      if (iVar13 < 0x32) {
        iVar13 = 0;
      }
      else {
        iVar13 = iVar13 + -0x46;
      }
      goto LAB_004697e0;
    case 0x12:
    case 0x14:
      if (iVar8 < 0x47) {
        iVar8 = iVar8 + 10;
      }
      else {
        iVar8 = 100;
      }
      if (iVar3 < 0x1e) {
        iVar3 = 0;
      }
      else {
        iVar3 = iVar3 + -10;
      }
      if (iVar13 < 0x32) {
        iVar13 = 0;
      }
      else {
        iVar13 = iVar13 + -0x46;
      }
LAB_004697e0:
      FUN_00469a60(iVar8,iVar3,iVar13,&local_48,&local_4c,local_44);
      local_4c = __ftol();
      uVar10 = local_44[0];
      uVar12 = local_48;
    default:
      goto switchD_00468c5c_default;
    }
    local_44[0] = 0;
    local_4c = 0;
    local_48 = 0;
LAB_004696b8:
    uVar10 = local_44[0];
    uVar12 = local_48;
    local_4c = __ftol();
switchD_00468c5c_default:
    if ((int)local_44[2] <= (int)uVar12) {
      uVar12 = local_44[2] - 1;
      local_48 = uVar12;
    }
    if (local_38 <= (int)local_4c) {
      local_4c = local_38 - 1;
    }
    if (local_30 <= (int)uVar10) {
      uVar10 = local_30 - 1;
      local_44[0] = uVar10;
    }
    local_34 = uVar10 << (g_pixel_blue_shift & 0x1f) & 0xffff |
               local_4c << (g_pixel_green_shift & 0x1f) & 0xffff |
               uVar12 << (g_pixel_red_shift & 0x1f) & 0xffff;
LAB_0046986a:
    *(undefined2 *)(param_1 + local_8 * 2) = (undefined2)local_34;
    local_8 = local_8 + 1;
    if (0xffff < local_8) {
      return;
    }
  } while( true );
}
