/*
 * Generated by Ghidra headless decompiler from China2EX_fontfix8.exe.
 * Address request: 0x004f0070
 * This is reconstructed pseudocode, not original source.
 */


void Unlock_Back_Surface(void)

{
  (**(code **)(*(int *)g_back_surface + 0x80))(g_back_surface,0);
  g_back_surface_locked = 0;
  DAT_00755924 = 0;
  return;
}
