/*
 * Generated by Ghidra headless decompiler from China2EX_fontfix8.exe.
 * Address request: 0x004094b0
 * This is reconstructed pseudocode, not original source.
 */


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void AI_UnClear(void)

{
  byte bVar1;
  int iVar2;
  CountryState_0xe68 *pCVar3;
  int iVar4;
  int iVar5;
  undefined4 *puVar6;
  int iVar7;
  int iVar8;
  int iVar9;
  int local_158;
  short *local_154;
  int local_150;
  int local_14c;
  int local_148;
  int local_144;
  int local_140;
  undefined4 local_13c;
  undefined1 local_138;
  undefined4 local_137;
  undefined1 local_133;
  undefined4 local_132;
  undefined1 local_12e;
  undefined *local_12c;
  int local_128;
  undefined1 local_124 [292];

  Trace_Function(s_AI_UnClear_005122f0);
  if (DAT_00706838 != '\x01') {
LAB_004098fa:
    if ((0 < g_active_army_type_def->special_mission_range_limit) && (_DAT_00748ff0 != DAT_007584dc)
       ) {
      Add_OrderQueue_Army(_DAT_00748ff0,6,0x3f,-1,-1,(ArmyUnit_0x164_plus *)0x0,-1,-1);
    }
    if (DAT_00706838 == '\x01') {
      DAT_0070684c = 1;
    }
    return;
  }
  local_144 = 0;
  local_14c = 0;
  local_158 = 1;
  local_154 = (short *)&DAT_007360ca;
  local_150 = 0x470;
  local_12c = &DAT_00749d78;
  pCVar3 = g_active_country;
  do {
    if ((5 < *(int *)(local_150 + -0x2c0 + (int)pCVar3)) && (*local_154 != 0)) {
      iVar4 = *(int *)(local_12c + local_150);
      local_140 = 0;
      iVar8 = ((uint)(byte)(&pCVar3->field_0x5f8)[local_158] * 0x40 -
              *(int *)(pCVar3->name_bytes + local_150 + -4)) +
              *(int *)(local_150 + -0xb0 + (int)pCVar3);
      local_148 = 0;
      local_128 = iVar8;
      if (iVar4 == 0) {
LAB_004096bb:
        iVar8 = 0;
      }
      else {
        do {
          iVar2 = Tile_Distance_With_Wrap
                            ((uint)*(ushort *)(iVar4 + 0x16),(uint)*(ushort *)(iVar4 + 0x18),
                             DAT_0070683c,DAT_00706840,(byte *)0x0);
          if (5 < iVar2) {
            iVar7 = 0;
            bVar1 = _DAT_00748ff0->army_type_id;
            if (bVar1 == 0x1e) {
              iVar7 = 500;
            }
            else if (bVar1 == 0x3f) {
              iVar7 = 0x19;
            }
            else if (bVar1 == 0x41) {
              iVar7 = 0x46;
            }
            if (iVar7 < iVar2) goto LAB_004096a0;
            iVar2 = 0;
            iVar7 = (uint)*(byte *)(iVar4 + 0x20) * 0x10;
            switch(g_map_size_mode) {
            case 0:
              iVar2 = (uint)*(ushort *)(iVar4 + 0x16) + (uint)*(ushort *)(iVar4 + 0x18) * 0x138;
              break;
            case 1:
              iVar2 = (uint)*(ushort *)(iVar4 + 0x16) + (uint)*(ushort *)(iVar4 + 0x18) * 0x9c;
              break;
            case 2:
              iVar2 = (uint)*(ushort *)(iVar4 + 0x16) + (uint)*(ushort *)(iVar4 + 0x18) * 0x4e;
              break;
            case 3:
              iVar2 = (uint)*(ushort *)(iVar4 + 0x18) * 0x27 + (uint)*(ushort *)(iVar4 + 0x16);
              break;
            default:
              goto switchD_004095e1_default;
            }
            iVar2 = iVar2 * 0x100 + _g_land_tiles;
switchD_004095e1_default:
            iVar5 = (int)*(char *)(iVar2 + 0x50);
            if (0 < iVar5) {
              iVar7 = iVar7 + iVar5;
              iVar9 = 0;
              puVar6 = (undefined4 *)(iVar2 + 0x28);
              do {
                if (iVar5 < 1) break;
                if ((byte *)*puVar6 != (byte *)0x0) {
                  if (g_army_type_table[*(byte *)*puVar6].attack_category == 2) {
                    iVar7 = iVar7 + 100;
                  }
                  iVar5 = iVar5 + -1;
                  iVar8 = local_128;
                }
                iVar9 = iVar9 + 1;
                puVar6 = puVar6 + 1;
              } while (iVar9 < 10);
            }
            if (local_148 < iVar7) {
              local_148 = iVar7;
              local_140 = iVar4;
            }
          }
LAB_004096a0:
          iVar4 = *(int *)(iVar4 + 0x1b4);
        } while (iVar4 != 0);
        pCVar3 = g_active_country;
        if (local_140 == 0) goto LAB_004096bb;
      }
      if (local_14c < iVar8) {
        local_14c = iVar8;
        local_144 = local_140;
      }
    }
    local_154 = local_154 + 0x734;
    local_150 = local_150 + 4;
    local_158 = local_158 + 1;
  } while (local_150 < 0x4c4);
  if (local_144 == 0) goto LAB_004098fa;
  if (_DAT_00748ff0->cargo_or_subunit_count != 0) {
    BreakOut(_DAT_00748ff0);
    pCVar3 = g_active_country;
  }
  _DAT_0074946c = 2;
  if (*(char *)(local_144 + 1) != g_human_country_index) goto LAB_00409828;
  local_13c = DAT_005122e8;
  local_137 = DAT_005122e0;
  local_138 = DAT_005122ec;
  local_132 = DAT_005122d8;
  local_133 = DAT_005122e4;
  local_12e = DAT_005122dc;
  if (DAT_0074c034 == 0x1e) {
    puVar6 = &local_132;
LAB_004097ce:
    Format_Text(local_124,&DAT_005122b0,pCVar3->name_bytes,puVar6,g_active_army_type_def->name_bytes
                ,local_144 + 3);
  }
  else {
    if (DAT_0074c034 == 0x3f) {
      puVar6 = &local_13c;
      goto LAB_004097ce;
    }
    if (DAT_0074c034 == 0x41) {
      puVar6 = &local_137;
      goto LAB_004097ce;
    }
  }
  _DAT_0074a348 = DAT_0070683c;
  _DAT_0074a350 = DAT_00706840;
  UI_YesNo_Result(local_124,0);
  FUN_00489e20((int)*(char *)(local_144 + 1),_DAT_00748e34,0xffffffff,local_124);
LAB_00409828:
  DAT_007584e0 = _DAT_00748ff0;
  if (DAT_0074c034 == 0x41) {
    _DAT_00748ff0->mission_action_id = 0x59;
  }
  else {
    _DAT_00748ff0->mission_action_id = 0x58;
  }
  DAT_007584e0->mission_progress_counter = 0;
  DAT_007584e0->target_tile_x_or_anim_x = *(short *)(local_144 + 0x16);
  DAT_007584e0->target_tile_y_or_anim_y = *(short *)(local_144 + 0x18);
  DAT_007584e0->path_replan_origin_x = DAT_007584e0->tile_x;
  DAT_007584e0->path_replan_origin_y = DAT_007584e0->tile_y;
  iVar4 = Tile_Direction_DeltaX
                    ((int)DAT_007584e0->target_tile_x_or_anim_x,
                     (int)DAT_007584e0->target_tile_y_or_anim_y,(int)DAT_007584e0->tile_x,
                     (int)DAT_007584e0->tile_y);
  iVar8 = Tile_Direction_DeltaY
                    ((int)DAT_007584e0->target_tile_y_or_anim_y,(int)DAT_007584e0->tile_y);
  iVar4 = Mission_Direct(iVar4,iVar8);
  DAT_007584e0->facing_or_move_direction = (byte)iVar4;
  *(undefined1 *)(DAT_0075597c + 0xb4) = 1;
  g_map_interaction_mode = 0xc;
  return;
}
