/*
 * Generated by Ghidra headless decompiler from China2EX_fontfix8.exe.
 * Address request: 0x00425bd0
 * This is reconstructed pseudocode, not original source.
 */


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void City_People_Born_Rate(void)

{
  int iVar1;
  ushort uVar2;
  short sVar3;
  double local_10;
  
  Trace_Function(s_City_People_Born_Rate_00515a30);
  g_active_country->population_or_score_total =
       g_active_country->population_or_score_total -
       (double)g_current_city->stored_population_or_value;
  if (g_active_country->leader_or_country_id == 6) {
    iVar1 = g_current_city->stored_population_or_value;
    if (iVar1 < 100000) {
      _DAT_007068c8 = 1.018;
    }
    else if (iVar1 < 300000) {
      _DAT_007068c8 = 1.013;
    }
    else if (iVar1 < 1000000) {
      _DAT_007068c8 = 1.008;
    }
    else if (iVar1 < 5000000) {
      _DAT_007068c8 = 1.006;
    }
    else {
      _DAT_007068c8 = 1.003;
    }
  }
  else {
    iVar1 = g_current_city->stored_population_or_value;
    if (iVar1 < 100000) {
      _DAT_007068c8 = 1.02;
    }
    else if (iVar1 < 300000) {
      _DAT_007068c8 = 1.015;
    }
    else if (iVar1 < 1000000) {
      _DAT_007068c8 = 1.01;
    }
    else if (iVar1 < 5000000) {
      _DAT_007068c8 = 1.008;
    }
    else {
      _DAT_007068c8 = 1.005;
    }
  }
  switch(g_active_country->population_growth_policy) {
  case 0:
    uVar2 = FUN_004fbf50(5);
    local_10 = (double)uVar2 * _DAT_0050f368;
    sVar3 = FUN_004fbf50(2);
    if (sVar3 == 0) {
      _DAT_007068c8 = _DAT_007068c8 + -local_10;
      return;
    }
    break;
  case 1:
    uVar2 = FUN_004fbf50(3);
    local_10 = (double)uVar2 * _DAT_0050f368;
    sVar3 = FUN_004fbf50(2);
    if (sVar3 == 0) {
      local_10 = -local_10;
    }
    uVar2 = FUN_004fbf50(5);
    _DAT_007068c8 = _DAT_007068c8 + (double)uVar2 * _DAT_0050f368 + local_10;
    return;
  case 2:
    uVar2 = FUN_004fbf50(5);
    local_10 = (double)uVar2 * _DAT_0050f368;
    sVar3 = FUN_004fbf50(2);
    if (sVar3 == 0) {
      local_10 = -local_10;
    }
    uVar2 = FUN_004fbf50(3);
    _DAT_007068c8 = _DAT_007068c8 + (local_10 - (double)uVar2 * _DAT_0050f368);
    return;
  case 3:
    uVar2 = FUN_004fbf50(3);
    local_10 = (double)uVar2 * _DAT_0050f368;
    sVar3 = FUN_004fbf50(2);
    if (sVar3 == 0) {
      local_10 = -local_10;
    }
    uVar2 = FUN_004fbf50(3);
    _DAT_007068c8 = _DAT_007068c8 + (local_10 - (double)uVar2 * _DAT_0050f368);
    return;
  }
  _DAT_007068c8 = _DAT_007068c8 + local_10;
  return;
}

