/*
 * Generated by Ghidra headless decompiler from China2EX_fontfix8.exe.
 * Address request: 0x0041f8c0
 * This is reconstructed pseudocode, not original source.
 */


/* WARNING: Unknown calling convention -- yet parameter storage is locked */

void City_Like_Change(City_0x1b8_plus *city)

{
  int iVar1;
  int in_stack_00000008;
  int in_stack_0000000c;
  
  Trace_Function(s_City_Like_Change_00515394);
  iVar1 = (char)(&city->field_0x34)[in_stack_00000008] + in_stack_0000000c;
  if (iVar1 < 0) {
    (&city->field_0x34)[in_stack_00000008] = 0;
    return;
  }
  if (100 < iVar1) {
    iVar1 = 100;
  }
  (&city->field_0x34)[in_stack_00000008] = (char)iVar1;
  return;
}

