/*
 * Generated by Ghidra headless decompiler from China2EX_fontfix8.exe.
 * Address request: 0x00428bf0
 * This is reconstructed pseudocode, not original source.
 */


void City_Size_Scale(int param_1)

{
  int iVar1;
  byte bVar2;
  uint uVar3;
  uint uVar4;
  short sVar5;
  uint uVar6;
  ushort uVar7;
  undefined1 local_c0 [192];

  Trace_Function(s_City_Size_Scale_00515d10);
  iVar1 = *(int *)(param_1 + 0x24);
  if (iVar1 < 50000) {
    uVar6 = 0;
  }
  else if (iVar1 < 200000) {
    uVar6 = 1;
  }
  else if (iVar1 < 400000) {
    uVar6 = 2;
  }
  else if (iVar1 < 1200000) {
    uVar6 = 3;
  }
  else if (iVar1 < 1800000) {
    uVar6 = 4;
  }
  else if (iVar1 < 2600000) {
    uVar6 = 5;
  }
  else {
    uVar6 = (4999999 < iVar1) + 6;
  }
  uVar4 = (uint)*(byte *)(param_1 + 0x21);
  if ((uVar4 < uVar6) &&
     (((*(char *)(param_1 + 0x7a) < '\x02' && (*(char *)(param_1 + 0x8d) < '\x02')) ||
      (*(int *)(param_1 + 0xcc) < *(int *)(&DAT_005a7c78 + uVar4 * 4) * 4)))) {
    *(undefined1 *)(param_1 + 0xd0) = 1;
    uVar6 = uVar4;
    if (*(byte *)(param_1 + 0x21) < 7) {
      uVar3 = FUN_004fbf50(3000);
      *(uint *)(param_1 + 0x24) = *(int *)(&DAT_00515c7c + uVar4 * 4) - (uVar3 & 0xffff);
    }
    else {
      uVar4 = FUN_004fbf50(3000);
      *(uint *)(param_1 + 0x24) = 99999999 - (uVar4 & 0xffff);
    }
  }
  else {
    *(undefined1 *)(param_1 + 0xd0) = 0;
  }
  if (*(int *)(param_1 + 0x24) < 10000) {
    uVar4 = 0;
  }
  else {
    uVar4 = (*(int *)(param_1 + 0x24) - *(int *)(&DAT_00515c78 + uVar6 * 4)) /
            *(int *)(&DAT_00515cb8 + uVar6 * 4) + *(int *)(&DAT_00515c98 + uVar6 * 4);
    if (99 < (int)uVar4) {
      uVar4 = 99;
    }
  }
  if (uVar4 == *(byte *)(param_1 + 0x20)) {
    if (((*(char *)(param_1 + 0xd0) == '\x01') &&
        ((*(char *)(param_1 + 0x7a) == '\x02' || (*(char *)(param_1 + 0x8d) == '\x02')))) &&
       (*(int *)(&DAT_005a7c78 + (uint)*(byte *)(param_1 + 0x21) * 4) * 4 <=
        *(int *)(param_1 + 0xcc))) {
      *(undefined1 *)(param_1 + 0xd0) = 0;
    }
  }
  else {
    if (param_1 == DAT_007584a8) {
      DAT_005e0000 = 1;
    }
    bVar2 = *(byte *)(param_1 + 0x20);
    uVar7 = (ushort)bVar2;
    if (10 < bVar2) {
      if (2 < g_current_map_scenario_info.scenario_value_30) {
        uVar7 = uVar7 * 2;
      }
      if (4 < g_current_map_scenario_info.scenario_value_30) {
        uVar7 = uVar7 + (bVar2 >> 1);
      }
      if (0x1e < bVar2) {
        uVar7 = uVar7 * 2;
      }
    }
    if (uVar7 == 0) {
      uVar7 = 1;
    }
    *(short *)(param_1 + 0xd2) = *(short *)(param_1 + 0xd2) - uVar7;
    bVar2 = (byte)uVar4;
    *(byte *)(param_1 + 0x20) = bVar2;
    uVar4 = uVar4 & 0xff;
    if (10 < bVar2) {
      uVar3 = uVar4;
      if (2 < g_current_map_scenario_info.scenario_value_30) {
        uVar3 = uVar4 * 2;
      }
      if (4 < g_current_map_scenario_info.scenario_value_30) {
        uVar3 = uVar3 + (uVar4 >> 1);
      }
      uVar4 = uVar3;
      if (0x1e < bVar2) {
        uVar4 = uVar4 * 2;
      }
    }
    sVar5 = (short)uVar4;
    if (uVar4 == 0) {
      sVar5 = 1;
    }
    *(short *)(param_1 + 0xd2) = *(short *)(param_1 + 0xd2) + sVar5;
    if ((*(byte *)(param_1 + 0x21) < uVar6) && (*(char *)(param_1 + 0xd0) == '\0')) {
      Del_Army_View((uint)*(ushort *)(param_1 + 0x16),(uint)*(ushort *)(param_1 + 0x18),
                    *(uint *)(&DAT_005a7c58 + (uint)*(byte *)(param_1 + 0x21) * 4),
                    (int)*(char *)(param_1 + 1),0);
      if ((*(char *)(param_1 + 1) == g_human_country_index) && (DAT_0074a2ce != '\0')) {
        if (*(byte *)(param_1 + 0x21) < uVar6) {
          Format_Text(local_c0,&DAT_00515cf4,param_1 + 3,
                      &DAT_005a7bdc + (uint)*(byte *)(param_1 + 0x21) * 5,&DAT_005a7bdc + uVar6 * 5)
          ;
          *(int *)(param_1 + 0xcc) = *(int *)(param_1 + 0xcc) / 3;
        }
        else {
          Format_Text(local_c0,&DAT_00515cd8,param_1 + 3,
                      &DAT_005a7bdc + (uint)*(byte *)(param_1 + 0x21) * 5,&DAT_005a7bdc + uVar6 * 5)
          ;
        }
        FUN_004898b0(DAT_007350b4,local_c0,1,*(undefined2 *)(param_1 + 0x16),
                     *(undefined2 *)(param_1 + 0x18));
      }
      *(char *)(param_1 + 0x21) = (char)uVar6;
      Add_New_View((uint)*(ushort *)(param_1 + 0x16),(uint)*(ushort *)(param_1 + 0x18),
                   *(int *)(&DAT_005a7c58 + uVar6 * 4),(int)*(char *)(param_1 + 1),1,1,0,0);
      return;
    }
  }
  return;
}
