/*
 * Generated by Ghidra headless decompiler from China2EX_fontfix8.exe.
 * Address request: 0x0041f7c0
 * This is reconstructed pseudocode, not original source.
 */


void __cdecl City_Loyal_Change(City_0x1b8_plus *city)

{
  int iVar1;
  int in_stack_00000008;

  Trace_Function(s_City_Loyal_Change_0051534c);
  iVar1 = in_stack_00000008 + city->growth_or_industry_score;
  if (iVar1 < 0) {
    city->growth_or_industry_score = 0;
    return;
  }
  if (100 < iVar1) {
    iVar1 = 100;
  }
  city->growth_or_industry_score = iVar1;
  return;
}
