/*
 * Generated by Ghidra headless decompiler from China2EX_fontfix8.exe.
 * Address request: 0x0041f880
 * This is reconstructed pseudocode, not original source.
 */


int City_People_Change_Percent(int param_1,int param_2)

{
  int iVar1;
  int iVar2;
  
  Trace_Function(s_City_People_Change_Percent_00515378);
  iVar1 = *(int *)(param_1 + 0x24);
  iVar2 = (iVar1 * param_2) / 100;
  if (iVar2 < 0) {
    iVar2 = 0;
  }
  *(int *)(param_1 + 0x24) = iVar2;
  return iVar2 - iVar1;
}

