/*
 * Generated by Ghidra headless decompiler from China2EX_fontfix8.exe.
 * Address request: 0x004939c0
 * This is reconstructed pseudocode, not original source.
 */


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */
/* WARNING: Unknown calling convention -- yet parameter storage is locked */

void Clear_Forest_Or_Resource(LandTile_0x100 *tile)

{
  Trace_Function(s_Forset_Disappear_0057e1b4);
  FUN_0041f600(_DAT_0074a0f8,10,
               *(int *)(&DAT_00589644 + (char)tile->battle_resource_or_feature_id * 4) * 0xf,0);
  if ((-1 < (char)tile->city_resource_or_feature_id) &&
     ((&DAT_005a816c)[(char)tile->city_resource_or_feature_id * 0x36] != 0)) {
    tile->city_resource_or_feature_stockpile = 0;
    tile->city_resource_or_feature_id = 0xff;
    tile->battle_resource_or_feature_id = 0xff;
    tile->tile_work_progress = 0;
    return;
  }
  tile->battle_resource_or_feature_id = 0xff;
  tile->tile_work_progress = 0;
  return;
}
