/*
 * Generated by Ghidra headless decompiler from China2EX_fontfix8.exe.
 * Address request: 0x0043dec0
 * This is reconstructed pseudocode, not original source.
 */


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void Diplomat_Start(int param_1,int param_2,ArmyUnit_0x164_plus *param_3)

{
  int iVar1;
  undefined4 *puVar2;
  char cVar3;
  undefined4 uVar4;
  bool bVar5;
  int iVar6;
  uint uVar7;
  uint uVar8;
  int iVar9;
  int iVar10;
  uint uVar11;
  int iVar12;
  int *piVar13;
  char *pcVar14;
  undefined4 *puVar15;
  char *pcVar16;
  char *pcVar17;
  char *pcVar18;
  int iVar19;
  undefined1 local_c0 [192];

  Trace_Function(s_Diplomat_Start_0051a968);
  iVar12 = param_2 + param_1 * 0x16;
  iVar1 = iVar12 * 0x848;
  puVar2 = (undefined4 *)(&DAT_0060b670 + iVar1);
  if ((*(int *)(&DAT_0060b670 + iVar12 * 0x848) != 0) ||
     (iVar12 = param_1 + param_2 * 0x16, *(int *)(&DAT_0060b670 + iVar12 * 0x848) != 0)) {
    return;
  }
  DAT_00705e90 = 0;
  iVar6 = param_1 * 0xe68;
  uVar8 = 0xffffffff;
  if (*(int *)(&DAT_0051bd74 + (uint)(byte)(&DAT_00735592)[param_2 + iVar6] * 0x15a8) == 3) {
    uVar8 = (uint)(byte)(&DAT_00735592)[param_2 + iVar6];
  }
  iVar9 = param_2 * 0xe68;
  if (((&DAT_007355a8)[param_1 + iVar9] == '\x01') && ((int)uVar8 < 0)) {
    if (param_1 == g_human_country_index) {
      Format_Text(local_c0,&DAT_0051a94c,&DAT_007350bc + iVar9,
                  g_empire_country_defs[(byte)(&DAT_007350b9)[iVar9]].country_profile_id * 0x7c +
                  0x596229,&DAT_007350cd + iVar9);
      FUN_00443e00(param_1,local_c0,&DAT_0051a928,0,0);
      return;
    }
    if (param_2 != g_human_country_index) {
      DAT_00705e90 = 0;
      return;
    }
    Format_Text(local_c0,&DAT_0051a908,&DAT_007350bc + iVar6,
                g_empire_country_defs[(byte)(&DAT_007350b9)[iVar6]].country_profile_id * 0x7c +
                0x596229,&DAT_007350cd + iVar6);
    FUN_00443e00(param_1,local_c0,&DAT_0051a928,0,0);
    return;
  }
  if ((_DAT_00748e30 != 0) && (g_auto_turn_or_ai_control_flag == 0)) {
    if ((-1 < (char)(&DAT_00735116)[iVar6]) &&
       (*(char *)(_DAT_00748e30 + 0x5e) == (&DAT_00735116)[iVar6])) {
      DAT_00705e90 = 1;
    }
    if ((-1 < (char)(&DAT_00735116)[iVar9]) &&
       (*(char *)(_DAT_00748e30 + 0x5e) == (&DAT_00735116)[iVar9])) {
      DAT_00705e90 = 2;
    }
    if ((-1 < (char)(&DAT_00735116)[iVar6]) && ((&DAT_00735116)[iVar6] == (&DAT_00735116)[iVar9])) {
      DAT_00705e90 = 0;
    }
  }
  if ((((param_1 == g_human_country_index) || (param_2 == g_human_country_index)) &&
      ((_DAT_0074a5e4 != 0 || (*(char *)(_DAT_00748e30 + 0x611) != '\0')))) &&
     (g_auto_turn_or_ai_control_flag != 1)) {
    if (DAT_00705e90 == 0) {
      return;
    }
    if (_DAT_0074a5e4 != 0) {
      return;
    }
    if (*(char *)(_DAT_00748e30 + 0x611) != '\0') {
      return;
    }
  }
  (&DAT_007356c9)[iVar6] = (&DAT_007356c9)[iVar6] + '\x01';
  (&DAT_007356c9)[iVar9] = (&DAT_007356c9)[iVar9] + '\x01';
  *puVar2 = 1;
  *(undefined4 *)(&DAT_0060b670 + iVar12 * 0x848) = 1;
  *(ArmyUnit_0x164_plus **)(&DAT_0060b690 + iVar1) = param_3;
  if (param_3 != (ArmyUnit_0x164_plus *)0x0) {
    Add_OrderQueue_Army(param_3,0x31,0x78,-1,-1,(ArmyUnit_0x164_plus *)0x0,-1,-1);
  }
  *(undefined **)(&DAT_0060b684 + iVar1) = &g_country_states + iVar9;
  *(undefined4 *)(&DAT_0060b674 + iVar1) = 0xffffffff;
  *(undefined **)(&DAT_0060b680 + iVar1) = &g_country_states + iVar6;
  *(undefined4 *)(&DAT_0060b69c + iVar1) = 0xffffffff;
  *(int *)(&DAT_0060b678 + iVar1) = param_1;
  *(int *)(&DAT_0060b67c + iVar1) = param_2;
  *(undefined4 *)(&DAT_0060b694 + iVar1) = 0;
  *(undefined4 *)(&DAT_0060b698 + iVar1) = 0;
  puVar15 = (undefined4 *)(&DAT_0060b6a0 + iVar1);
  for (iVar10 = 0x7c; iVar10 != 0; iVar10 = iVar10 + -1) {
    *puVar15 = 0;
    puVar15 = puVar15 + 1;
  }
  *(undefined4 *)(&DAT_0060b890 + iVar1) = 0;
  *(undefined4 *)(&DAT_0060b894 + iVar1) = 0;
  *(undefined4 *)(&DAT_0060b898 + iVar1) = 0;
  *(undefined4 *)(&DAT_0060b89c + iVar1) = 0;
  puVar15 = (undefined4 *)(&DAT_0060b8a0 + iVar1);
  for (iVar10 = 0x14; iVar10 != 0; iVar10 = iVar10 + -1) {
    *puVar15 = 0xffffffff;
    puVar15 = puVar15 + 1;
  }
  puVar15 = (undefined4 *)(&DAT_0060b8f0 + iVar1);
  for (iVar10 = 0x14; iVar10 != 0; iVar10 = iVar10 + -1) {
    *puVar15 = 0xffffffff;
    puVar15 = puVar15 + 1;
  }
  puVar15 = (undefined4 *)(&DAT_0060b94c + iVar1);
  for (iVar10 = 0x14; iVar10 != 0; iVar10 = iVar10 + -1) {
    *puVar15 = 0;
    puVar15 = puVar15 + 1;
  }
  *(undefined4 *)(&DAT_0060b940 + iVar1) = 0;
  *(undefined4 *)(&DAT_0060b944 + iVar1) = 0;
  *(undefined4 *)(&DAT_0060b948 + iVar1) = 0;
  if (g_auto_turn_or_ai_control_flag == 0) {
    if (param_1 == g_human_country_index) {
      *(undefined4 *)(&DAT_0060b674 + iVar1) = 0;
    }
    else if (param_2 == g_human_country_index) {
      *(undefined4 *)(&DAT_0060b674 + iVar1) = 1;
    }
  }
  DAT_00705f10 = 1;
  Diplomat_Compare(puVar2);
  FUN_00442910(puVar2);
  iVar10 = 0;
  Reflash_Dip_City_List(puVar2,0);
  Reflash_Dip_City_List(puVar2,1);
  FUN_00442c40(puVar2);
  FUN_00442ec0(puVar2);
  FUN_004430d0(puVar2);
  FUN_00443340(puVar2);
  FUN_00443590(puVar2);
  FUN_004437b0(puVar2);
  FUN_004439d0(puVar2);
  FUN_00443af0(puVar2);
  _DAT_0060b3f4 = 0;
  DAT_0075c408 = 0;
  if (*(int *)(&DAT_0060b674 + iVar1) < 0) {
    Diplomat_AskWhat(puVar2);
    if ((DAT_00705ebc == '\0') &&
       ((0 < *(int *)(&DAT_0060b940 + iVar1) || (0 < *(int *)(&DAT_0060b944 + iVar1))))) {
      iVar6 = *(int *)(&DAT_0060b698 + iVar1);
      iVar9 = 0;
      iVar19 = 0;
      if (0 < *(int *)(&DAT_0060b940 + iVar6 * 4 + iVar1)) {
        do {
          iVar6 = Diplomat_Value(puVar2,iVar6,iVar19);
          iVar9 = iVar9 + iVar6;
          iVar6 = *(int *)(&DAT_0060b698 + iVar1);
          iVar19 = iVar19 + 1;
        } while (iVar19 < *(int *)(&DAT_0060b940 + iVar6 * 4 + iVar1));
      }
      iVar6 = 0;
      uVar8 = (uint)(*(int *)(&DAT_0060b698 + iVar1) == 0);
      if (0 < *(int *)(&DAT_0060b940 + uVar8 * 4 + iVar1)) {
        do {
          iVar19 = Diplomat_Value(puVar2,uVar8,iVar6);
          iVar10 = iVar10 + iVar19;
          iVar6 = iVar6 + 1;
          uVar8 = (uint)(*(int *)(&DAT_0060b698 + iVar1) == 0);
        } while (iVar6 < *(int *)(&DAT_0060b940 + uVar8 * 4 + iVar1));
      }
      FUN_00444410(puVar2,iVar9 < iVar10);
      if (*(ArmyUnit_0x164_plus **)(&DAT_0060b690 + iVar1) != (ArmyUnit_0x164_plus *)0x0) {
        Add_OrderQueue_Army(*(ArmyUnit_0x164_plus **)(&DAT_0060b690 + iVar1),0,-1,0x1a,-1,
                            (ArmyUnit_0x164_plus *)0x0,-1,-1);
      }
      *puVar2 = 0;
      *(undefined4 *)(&DAT_0060b670 + iVar12 * 0x848) = 0;
    }
    else {
      if (*(ArmyUnit_0x164_plus **)(&DAT_0060b690 + iVar1) != (ArmyUnit_0x164_plus *)0x0) {
        Add_OrderQueue_Army(*(ArmyUnit_0x164_plus **)(&DAT_0060b690 + iVar1),0,-1,0x1b,-1,
                            (ArmyUnit_0x164_plus *)0x0,-1,-1);
      }
      *puVar2 = 0;
      *(undefined4 *)(&DAT_0060b670 + iVar12 * 0x848) = 0;
    }
    *(char *)(*(int *)(&DAT_0060b680 + iVar1) + 0x611) =
         *(char *)(*(int *)(&DAT_0060b680 + iVar1) + 0x611) + -1;
    *(char *)(*(int *)(&DAT_0060b684 + iVar1) + 0x611) =
         *(char *)(*(int *)(&DAT_0060b684 + iVar1) + 0x611) + -1;
    return;
  }
  for (iVar12 = *(int *)(DAT_00758524 + 0xc4); iVar12 != 0; iVar12 = *(int *)(iVar12 + 0xc4)) {
    if (-1 < *(int *)(iVar12 + 8)) {
      *(int *)(iVar12 + 8) = *(int *)(iVar12 + 8) + 5;
    }
  }
  g_request_redraw = 1;
  FUN_004a1a00();
  FUN_004f0780();
  FUN_0048b5a0();
  Present_Dirty_Rects(0,0);
  FUN_0048b6e0();
  DAT_005dfe84 = FUN_0047de30((DAT_00755814 + 1) * (DAT_00755810 + 1) * 2 + 4,
                              s_Diplomat__BattleBack_0051a8f0,0xe);
  FUN_004f5b9b(0,0,DAT_00755810 + 1,DAT_00755814 + 1,DAT_005dfe84);
  FUN_00472120(&DAT_005c4030);
  FUN_00472120(&DAT_005c40f8);
  FUN_00472120(&DAT_005c41c0);
  FUN_00472120(&DAT_005c4288);
  FUN_00472120(&DAT_005c44e0);
  FUN_00472120(&DAT_005c45a8);
  FUN_00472120(&DAT_005c4670);
  FUN_00472120(&DAT_005c4738);
  FUN_00472120(&DAT_005c4350);
  FUN_00472120(&DAT_005c4418);
  Load_EMG_Resource(s_UI_DIP_EMG_0051a8e4,&DAT_007585ac);
  if (*(int *)(&DAT_0060b674 + iVar1) == 0) {
    iVar12 = *(int *)(&DAT_0060b678 + iVar1);
  }
  else {
    iVar12 = *(int *)(&DAT_0060b67c + iVar1);
  }
  g_map_interaction_mode = 5;
  DAT_00705ebc = 0;
  uVar8 = (uint)(*(int *)(&DAT_0060b674 + iVar1) == 0);
  if (*(int *)(&DAT_0060b674 + iVar1) == 1) {
    iVar10 = g_empire_country_defs[(byte)(&DAT_007350b9)[iVar6]].diplomacy_battle_music_id;
  }
  else {
    iVar10 = g_empire_country_defs[(byte)(&DAT_007350b9)[iVar9]].diplomacy_battle_music_id;
  }
  DAT_00705e98 = DAT_00588b94;
  DAT_00705eb8 = puVar2;
  FUN_004f0170(iVar10);
  _DAT_0051a078 = (uint)(byte)(&DAT_007350b9)[iVar6];
  _DAT_0051a07c = (uint)(byte)(&DAT_007350b9)[iVar9];
  puVar15 = &DAT_0060b470;
  for (iVar10 = 0x32; iVar10 != 0; iVar10 = iVar10 + -1) {
    *puVar15 = 0;
    puVar15 = puVar15 + 1;
  }
  *(undefined1 *)puVar15 = 0;
  puVar15 = &DAT_0060b539;
  for (iVar10 = 0x32; iVar10 != 0; iVar10 = iVar10 + -1) {
    *puVar15 = 0;
    puVar15 = puVar15 + 1;
  }
  *(undefined1 *)puVar15 = 0;
  _DAT_00705e9c = 0;
  _DAT_00705ea0 = 0;
  if (*(int *)(*(int *)(&DAT_0060b680 + uVar8 * 4 + iVar1) + 0x1ac + iVar12 * 4) < 2) {
    if ((_DAT_0050f2c0 <= *(double *)(&DAT_0060be70 + iVar1)) ||
       (_DAT_0050f2c0 <= *(double *)(&DAT_0060be78 + iVar1))) {
      if ((*(double *)(&DAT_0060be70 + iVar1) < _DAT_0050f3d0) ||
         (*(double *)(&DAT_0060be78 + iVar1) < _DAT_0050f3d0)) {
LAB_0043e517:
        *(undefined4 *)(iVar1 + 0x60b688 + uVar8 * 4) = 0;
      }
      else {
        *(undefined4 *)(iVar1 + 0x60b688 + uVar8 * 4) = 6;
      }
    }
    else {
      *(undefined4 *)(iVar1 + 0x60b688 + uVar8 * 4) = 3;
    }
  }
  else if ((_DAT_0050f3c8 <= *(double *)(&DAT_0060be70 + iVar1)) ||
          (_DAT_0050f3c8 <= *(double *)(&DAT_0060be78 + iVar1))) {
    if ((*(double *)(&DAT_0060be70 + iVar1) < _DAT_0050f3d0) ||
       (*(double *)(&DAT_0060be78 + iVar1) < _DAT_0050f3d0)) goto LAB_0043e517;
    *(undefined4 *)(iVar1 + 0x60b688 + uVar8 * 4) = 6;
  }
  else {
    *(undefined4 *)(iVar1 + 0x60b688 + uVar8 * 4) = 3;
  }
  uVar4 = *(undefined4 *)(iVar1 + 0x60b688 + uVar8 * 4);
  *(undefined4 *)(&DAT_0060b604 + uVar8 * 4) = uVar4;
  *(undefined4 *)(&DAT_0060b668 + uVar8 * 4) = uVar4;
  if (*(int *)(&DAT_0060b674 + iVar1) == 0) {
    pcVar14 = (char *)((int)&DAT_0060b470 + uVar8 * 0xc9);
    uVar7 = Game_Random_Mod(3);
    uVar11 = 0xffffffff;
    pcVar18 = (&PTR_DAT_0051bcb0)[(uVar7 & 0xffff) + *(int *)(&DAT_0060b604 + uVar8 * 4) * 3];
    do {
      pcVar17 = pcVar18;
      if (uVar11 == 0) break;
      uVar11 = uVar11 - 1;
      pcVar17 = pcVar18 + 1;
      cVar3 = *pcVar18;
      pcVar18 = pcVar17;
    } while (cVar3 != '\0');
    uVar11 = ~uVar11;
    pcVar18 = pcVar17 + -uVar11;
    pcVar17 = pcVar14;
    for (uVar7 = uVar11 >> 2; uVar7 != 0; uVar7 = uVar7 - 1) {
      *(undefined4 *)pcVar17 = *(undefined4 *)pcVar18;
      pcVar18 = pcVar18 + 4;
      pcVar17 = pcVar17 + 4;
    }
    for (uVar11 = uVar11 & 3; uVar11 != 0; uVar11 = uVar11 - 1) {
      *pcVar17 = *pcVar18;
      pcVar18 = pcVar18 + 1;
      pcVar17 = pcVar17 + 1;
    }
    uVar7 = 0xffffffff;
    pcVar18 = &DAT_007350bc + iVar9;
    do {
      pcVar17 = pcVar18;
      if (uVar7 == 0) break;
      uVar7 = uVar7 - 1;
      pcVar17 = pcVar18 + 1;
      cVar3 = *pcVar18;
      pcVar18 = pcVar17;
    } while (cVar3 != '\0');
    uVar7 = ~uVar7;
    iVar12 = -1;
    pcVar18 = pcVar14;
    do {
      pcVar16 = pcVar18;
      if (iVar12 == 0) break;
      iVar12 = iVar12 + -1;
      pcVar16 = pcVar18 + 1;
      cVar3 = *pcVar18;
      pcVar18 = pcVar16;
    } while (cVar3 != '\0');
    pcVar18 = pcVar17 + -uVar7;
    pcVar17 = pcVar16 + -1;
    for (uVar11 = uVar7 >> 2; uVar11 != 0; uVar11 = uVar11 - 1) {
      *(undefined4 *)pcVar17 = *(undefined4 *)pcVar18;
      pcVar18 = pcVar18 + 4;
      pcVar17 = pcVar17 + 4;
    }
    for (uVar7 = uVar7 & 3; uVar7 != 0; uVar7 = uVar7 - 1) {
      *pcVar17 = *pcVar18;
      pcVar18 = pcVar18 + 1;
      pcVar17 = pcVar17 + 1;
    }
    uVar7 = 0xffffffff;
    pcVar18 = &DAT_0051a8e0;
    do {
      pcVar17 = pcVar18;
      if (uVar7 == 0) break;
      uVar7 = uVar7 - 1;
      pcVar17 = pcVar18 + 1;
      cVar3 = *pcVar18;
      pcVar18 = pcVar17;
    } while (cVar3 != '\0');
    uVar7 = ~uVar7;
    iVar12 = -1;
    pcVar18 = pcVar14;
    do {
      pcVar16 = pcVar18;
      if (iVar12 == 0) break;
      iVar12 = iVar12 + -1;
      pcVar16 = pcVar18 + 1;
      cVar3 = *pcVar18;
      pcVar18 = pcVar16;
    } while (cVar3 != '\0');
    pcVar18 = pcVar17 + -uVar7;
    pcVar17 = pcVar16 + -1;
    for (uVar11 = uVar7 >> 2; uVar11 != 0; uVar11 = uVar11 - 1) {
      *(undefined4 *)pcVar17 = *(undefined4 *)pcVar18;
      pcVar18 = pcVar18 + 4;
      pcVar17 = pcVar17 + 4;
    }
    for (uVar7 = uVar7 & 3; uVar7 != 0; uVar7 = uVar7 - 1) {
      *pcVar17 = *pcVar18;
      pcVar18 = pcVar18 + 1;
      pcVar17 = pcVar17 + 1;
    }
    uVar7 = 0xffffffff;
    pcVar18 = &DAT_007350de + iVar9;
    do {
      pcVar17 = pcVar18;
      if (uVar7 == 0) break;
      uVar7 = uVar7 - 1;
      pcVar17 = pcVar18 + 1;
      cVar3 = *pcVar18;
      pcVar18 = pcVar17;
    } while (cVar3 != '\0');
    uVar7 = ~uVar7;
    iVar12 = -1;
    pcVar18 = pcVar14;
    do {
      pcVar16 = pcVar18;
      if (iVar12 == 0) break;
      iVar12 = iVar12 + -1;
      pcVar16 = pcVar18 + 1;
      cVar3 = *pcVar18;
      pcVar18 = pcVar16;
    } while (cVar3 != '\0');
    pcVar18 = pcVar17 + -uVar7;
    pcVar17 = pcVar16 + -1;
    for (uVar11 = uVar7 >> 2; uVar11 != 0; uVar11 = uVar11 - 1) {
      *(undefined4 *)pcVar17 = *(undefined4 *)pcVar18;
      pcVar18 = pcVar18 + 4;
      pcVar17 = pcVar17 + 4;
    }
    for (uVar7 = uVar7 & 3; uVar7 != 0; uVar7 = uVar7 - 1) {
      *pcVar17 = *pcVar18;
      pcVar18 = pcVar18 + 1;
      pcVar17 = pcVar17 + 1;
    }
    uVar7 = 0xffffffff;
    pcVar18 = &DAT_007350cd + iVar9;
    do {
      pcVar17 = pcVar18;
      if (uVar7 == 0) break;
      uVar7 = uVar7 - 1;
      pcVar17 = pcVar18 + 1;
      cVar3 = *pcVar18;
      pcVar18 = pcVar17;
    } while (cVar3 != '\0');
    uVar7 = ~uVar7;
    iVar12 = -1;
    pcVar18 = pcVar14;
    do {
      pcVar16 = pcVar18;
      if (iVar12 == 0) break;
      iVar12 = iVar12 + -1;
      pcVar16 = pcVar18 + 1;
      cVar3 = *pcVar18;
      pcVar18 = pcVar16;
    } while (cVar3 != '\0');
    pcVar18 = pcVar17 + -uVar7;
    pcVar17 = pcVar16 + -1;
    for (uVar11 = uVar7 >> 2; uVar11 != 0; uVar11 = uVar11 - 1) {
      *(undefined4 *)pcVar17 = *(undefined4 *)pcVar18;
      pcVar18 = pcVar18 + 4;
      pcVar17 = pcVar17 + 4;
    }
    for (uVar7 = uVar7 & 3; uVar7 != 0; uVar7 = uVar7 - 1) {
      *pcVar17 = *pcVar18;
      pcVar18 = pcVar18 + 1;
      pcVar17 = pcVar17 + 1;
    }
    uVar7 = 0xffffffff;
    pcVar18 = &DAT_0051a8dc;
    do {
      pcVar17 = pcVar18;
      if (uVar7 == 0) break;
      uVar7 = uVar7 - 1;
      pcVar17 = pcVar18 + 1;
      cVar3 = *pcVar18;
      pcVar18 = pcVar17;
    } while (cVar3 != '\0');
    uVar7 = ~uVar7;
    iVar12 = -1;
    pcVar18 = pcVar14;
    do {
      pcVar16 = pcVar18;
      if (iVar12 == 0) break;
      iVar12 = iVar12 + -1;
      pcVar16 = pcVar18 + 1;
      cVar3 = *pcVar18;
      pcVar18 = pcVar16;
    } while (cVar3 != '\0');
    pcVar18 = pcVar17 + -uVar7;
    pcVar17 = pcVar16 + -1;
    for (uVar11 = uVar7 >> 2; uVar11 != 0; uVar11 = uVar11 - 1) {
      *(undefined4 *)pcVar17 = *(undefined4 *)pcVar18;
      pcVar18 = pcVar18 + 4;
      pcVar17 = pcVar17 + 4;
    }
    for (uVar7 = uVar7 & 3; uVar7 != 0; uVar7 = uVar7 - 1) {
      *pcVar17 = *pcVar18;
      pcVar18 = pcVar18 + 1;
      pcVar17 = pcVar17 + 1;
    }
    uVar11 = Game_Random_Mod(3);
    uVar7 = 0xffffffff;
    pcVar18 = (&PTR_DAT_0051bd04)[(uVar11 & 0xffff) + *(int *)(&DAT_0060b604 + uVar8 * 4) * 3];
    do {
      pcVar17 = pcVar18;
      if (uVar7 == 0) break;
      uVar7 = uVar7 - 1;
      pcVar17 = pcVar18 + 1;
      cVar3 = *pcVar18;
      pcVar18 = pcVar17;
    } while (cVar3 != '\0');
    uVar7 = ~uVar7;
    pcVar17 = pcVar17 + -uVar7;
  }
  else {
    Diplomat_AskWhat(puVar2);
    iVar12 = *(int *)(&DAT_0060b940 + uVar8 * 4 + iVar1);
    if ((iVar12 < 1) && (*(int *)(&DAT_0060b940 + (uint)(uVar8 == 0) * 4 + iVar1) < 1)) {
      pcVar14 = (char *)((int)&DAT_0060b470 + uVar8 * 0xc9);
      uVar7 = Game_Random_Mod(3);
      uVar11 = 0xffffffff;
      pcVar18 = (&PTR_DAT_0051bcb0)[(uVar7 & 0xffff) + *(int *)(&DAT_0060b604 + uVar8 * 4) * 3];
      do {
        pcVar17 = pcVar18;
        if (uVar11 == 0) break;
        uVar11 = uVar11 - 1;
        pcVar17 = pcVar18 + 1;
        cVar3 = *pcVar18;
        pcVar18 = pcVar17;
      } while (cVar3 != '\0');
      uVar11 = ~uVar11;
      pcVar18 = pcVar17 + -uVar11;
      pcVar17 = pcVar14;
      for (uVar7 = uVar11 >> 2; uVar7 != 0; uVar7 = uVar7 - 1) {
        *(undefined4 *)pcVar17 = *(undefined4 *)pcVar18;
        pcVar18 = pcVar18 + 4;
        pcVar17 = pcVar17 + 4;
      }
      for (uVar11 = uVar11 & 3; uVar11 != 0; uVar11 = uVar11 - 1) {
        *pcVar17 = *pcVar18;
        pcVar18 = pcVar18 + 1;
        pcVar17 = pcVar17 + 1;
      }
      uVar7 = 0xffffffff;
      pcVar18 = &DAT_007350bc + iVar6;
      do {
        pcVar17 = pcVar18;
        if (uVar7 == 0) break;
        uVar7 = uVar7 - 1;
        pcVar17 = pcVar18 + 1;
        cVar3 = *pcVar18;
        pcVar18 = pcVar17;
      } while (cVar3 != '\0');
      uVar7 = ~uVar7;
      iVar12 = -1;
      pcVar18 = pcVar14;
      do {
        pcVar16 = pcVar18;
        if (iVar12 == 0) break;
        iVar12 = iVar12 + -1;
        pcVar16 = pcVar18 + 1;
        cVar3 = *pcVar18;
        pcVar18 = pcVar16;
      } while (cVar3 != '\0');
      pcVar18 = pcVar17 + -uVar7;
      pcVar17 = pcVar16 + -1;
      for (uVar11 = uVar7 >> 2; uVar11 != 0; uVar11 = uVar11 - 1) {
        *(undefined4 *)pcVar17 = *(undefined4 *)pcVar18;
        pcVar18 = pcVar18 + 4;
        pcVar17 = pcVar17 + 4;
      }
      for (uVar7 = uVar7 & 3; uVar7 != 0; uVar7 = uVar7 - 1) {
        *pcVar17 = *pcVar18;
        pcVar18 = pcVar18 + 1;
        pcVar17 = pcVar17 + 1;
      }
      uVar7 = 0xffffffff;
      pcVar18 = &DAT_0051a8e0;
      do {
        pcVar17 = pcVar18;
        if (uVar7 == 0) break;
        uVar7 = uVar7 - 1;
        pcVar17 = pcVar18 + 1;
        cVar3 = *pcVar18;
        pcVar18 = pcVar17;
      } while (cVar3 != '\0');
      uVar7 = ~uVar7;
      iVar12 = -1;
      pcVar18 = pcVar14;
      do {
        pcVar16 = pcVar18;
        if (iVar12 == 0) break;
        iVar12 = iVar12 + -1;
        pcVar16 = pcVar18 + 1;
        cVar3 = *pcVar18;
        pcVar18 = pcVar16;
      } while (cVar3 != '\0');
      pcVar18 = pcVar17 + -uVar7;
      pcVar17 = pcVar16 + -1;
      for (uVar11 = uVar7 >> 2; uVar11 != 0; uVar11 = uVar11 - 1) {
        *(undefined4 *)pcVar17 = *(undefined4 *)pcVar18;
        pcVar18 = pcVar18 + 4;
        pcVar17 = pcVar17 + 4;
      }
      for (uVar7 = uVar7 & 3; uVar7 != 0; uVar7 = uVar7 - 1) {
        *pcVar17 = *pcVar18;
        pcVar18 = pcVar18 + 1;
        pcVar17 = pcVar17 + 1;
      }
      uVar7 = 0xffffffff;
      pcVar18 = &DAT_007350de + iVar6;
      do {
        pcVar17 = pcVar18;
        if (uVar7 == 0) break;
        uVar7 = uVar7 - 1;
        pcVar17 = pcVar18 + 1;
        cVar3 = *pcVar18;
        pcVar18 = pcVar17;
      } while (cVar3 != '\0');
      uVar7 = ~uVar7;
      iVar12 = -1;
      pcVar18 = pcVar14;
      do {
        pcVar16 = pcVar18;
        if (iVar12 == 0) break;
        iVar12 = iVar12 + -1;
        pcVar16 = pcVar18 + 1;
        cVar3 = *pcVar18;
        pcVar18 = pcVar16;
      } while (cVar3 != '\0');
      pcVar18 = pcVar17 + -uVar7;
      pcVar17 = pcVar16 + -1;
      for (uVar11 = uVar7 >> 2; uVar11 != 0; uVar11 = uVar11 - 1) {
        *(undefined4 *)pcVar17 = *(undefined4 *)pcVar18;
        pcVar18 = pcVar18 + 4;
        pcVar17 = pcVar17 + 4;
      }
      for (uVar7 = uVar7 & 3; uVar7 != 0; uVar7 = uVar7 - 1) {
        *pcVar17 = *pcVar18;
        pcVar18 = pcVar18 + 1;
        pcVar17 = pcVar17 + 1;
      }
      uVar7 = 0xffffffff;
      pcVar18 = &DAT_007350cd + iVar6;
      do {
        pcVar17 = pcVar18;
        if (uVar7 == 0) break;
        uVar7 = uVar7 - 1;
        pcVar17 = pcVar18 + 1;
        cVar3 = *pcVar18;
        pcVar18 = pcVar17;
      } while (cVar3 != '\0');
      uVar7 = ~uVar7;
      iVar12 = -1;
      pcVar18 = pcVar14;
      do {
        pcVar16 = pcVar18;
        if (iVar12 == 0) break;
        iVar12 = iVar12 + -1;
        pcVar16 = pcVar18 + 1;
        cVar3 = *pcVar18;
        pcVar18 = pcVar16;
      } while (cVar3 != '\0');
      pcVar18 = pcVar17 + -uVar7;
      pcVar17 = pcVar16 + -1;
      for (uVar11 = uVar7 >> 2; uVar11 != 0; uVar11 = uVar11 - 1) {
        *(undefined4 *)pcVar17 = *(undefined4 *)pcVar18;
        pcVar18 = pcVar18 + 4;
        pcVar17 = pcVar17 + 4;
      }
      for (uVar7 = uVar7 & 3; uVar7 != 0; uVar7 = uVar7 - 1) {
        *pcVar17 = *pcVar18;
        pcVar18 = pcVar18 + 1;
        pcVar17 = pcVar17 + 1;
      }
      uVar7 = Game_Random_Mod(3);
      uVar7 = uVar7 & 0xffff;
      if (uVar7 == 0) {
        pcVar18 = &DAT_0051a860;
LAB_0043e7f7:
        uVar7 = 0xffffffff;
        do {
          pcVar17 = pcVar18;
          if (uVar7 == 0) break;
          uVar7 = uVar7 - 1;
          pcVar17 = pcVar18 + 1;
          cVar3 = *pcVar18;
          pcVar18 = pcVar17;
        } while (cVar3 != '\0');
        uVar7 = ~uVar7;
        iVar12 = -1;
        do {
          pcVar18 = pcVar14;
          if (iVar12 == 0) break;
          iVar12 = iVar12 + -1;
          pcVar18 = pcVar14 + 1;
          cVar3 = *pcVar14;
          pcVar14 = pcVar18;
        } while (cVar3 != '\0');
        pcVar14 = pcVar17 + -uVar7;
        pcVar18 = pcVar18 + -1;
        for (uVar11 = uVar7 >> 2; uVar11 != 0; uVar11 = uVar11 - 1) {
          *(undefined4 *)pcVar18 = *(undefined4 *)pcVar14;
          pcVar14 = pcVar14 + 4;
          pcVar18 = pcVar18 + 4;
        }
        for (uVar7 = uVar7 & 3; uVar7 != 0; uVar7 = uVar7 - 1) {
          *pcVar18 = *pcVar14;
          pcVar14 = pcVar14 + 1;
          pcVar18 = pcVar18 + 1;
        }
      }
      else {
        if (uVar7 == 1) {
          pcVar18 = &DAT_0051a884;
          goto LAB_0043e7f7;
        }
        if (uVar7 == 2) {
          pcVar18 = &DAT_0051a8ac;
          goto LAB_0043e7f7;
        }
      }
      *(undefined4 *)(&DAT_0060b694 + iVar1) = 5;
      goto switchD_0043e9d7_default;
    }
    bVar5 = false;
    if ((0 < iVar12) && (*(int *)(&DAT_0060b940 + (uint)(uVar8 == 0) * 4 + iVar1) == 0)) {
      iVar9 = 0;
      bVar5 = true;
      if (0 < iVar12) {
        piVar13 = puVar2 + (uVar8 * 5 + 0x46) * 2;
        do {
          if (*(int *)(&DAT_0051bd74 + *piVar13 * 0x15a8) < 3) {
            bVar5 = false;
            break;
          }
          iVar9 = iVar9 + 1;
          piVar13 = piVar13 + 1;
        } while (iVar9 < iVar12);
      }
    }
    pcVar14 = (char *)((int)&DAT_0060b470 + uVar8 * 0xc9);
    uVar7 = Game_Random_Mod(3);
    uVar11 = 0xffffffff;
    pcVar18 = (&PTR_DAT_0051bcb0)[(uVar7 & 0xffff) + *(int *)(&DAT_0060b604 + uVar8 * 4) * 3];
    do {
      pcVar17 = pcVar18;
      if (uVar11 == 0) break;
      uVar11 = uVar11 - 1;
      pcVar17 = pcVar18 + 1;
      cVar3 = *pcVar18;
      pcVar18 = pcVar17;
    } while (cVar3 != '\0');
    uVar11 = ~uVar11;
    pcVar18 = pcVar17 + -uVar11;
    pcVar17 = pcVar14;
    for (uVar7 = uVar11 >> 2; uVar7 != 0; uVar7 = uVar7 - 1) {
      *(undefined4 *)pcVar17 = *(undefined4 *)pcVar18;
      pcVar18 = pcVar18 + 4;
      pcVar17 = pcVar17 + 4;
    }
    for (uVar11 = uVar11 & 3; uVar11 != 0; uVar11 = uVar11 - 1) {
      *pcVar17 = *pcVar18;
      pcVar18 = pcVar18 + 1;
      pcVar17 = pcVar17 + 1;
    }
    uVar7 = 0xffffffff;
    pcVar18 = &DAT_007350bc + iVar6;
    do {
      pcVar17 = pcVar18;
      if (uVar7 == 0) break;
      uVar7 = uVar7 - 1;
      pcVar17 = pcVar18 + 1;
      cVar3 = *pcVar18;
      pcVar18 = pcVar17;
    } while (cVar3 != '\0');
    uVar7 = ~uVar7;
    iVar12 = -1;
    pcVar18 = pcVar14;
    do {
      pcVar16 = pcVar18;
      if (iVar12 == 0) break;
      iVar12 = iVar12 + -1;
      pcVar16 = pcVar18 + 1;
      cVar3 = *pcVar18;
      pcVar18 = pcVar16;
    } while (cVar3 != '\0');
    pcVar18 = pcVar17 + -uVar7;
    pcVar17 = pcVar16 + -1;
    for (uVar11 = uVar7 >> 2; uVar11 != 0; uVar11 = uVar11 - 1) {
      *(undefined4 *)pcVar17 = *(undefined4 *)pcVar18;
      pcVar18 = pcVar18 + 4;
      pcVar17 = pcVar17 + 4;
    }
    for (uVar7 = uVar7 & 3; uVar7 != 0; uVar7 = uVar7 - 1) {
      *pcVar17 = *pcVar18;
      pcVar18 = pcVar18 + 1;
      pcVar17 = pcVar17 + 1;
    }
    uVar7 = 0xffffffff;
    pcVar18 = &DAT_0051a8e0;
    do {
      pcVar17 = pcVar18;
      if (uVar7 == 0) break;
      uVar7 = uVar7 - 1;
      pcVar17 = pcVar18 + 1;
      cVar3 = *pcVar18;
      pcVar18 = pcVar17;
    } while (cVar3 != '\0');
    uVar7 = ~uVar7;
    iVar12 = -1;
    pcVar18 = pcVar14;
    do {
      pcVar16 = pcVar18;
      if (iVar12 == 0) break;
      iVar12 = iVar12 + -1;
      pcVar16 = pcVar18 + 1;
      cVar3 = *pcVar18;
      pcVar18 = pcVar16;
    } while (cVar3 != '\0');
    pcVar18 = pcVar17 + -uVar7;
    pcVar17 = pcVar16 + -1;
    for (uVar11 = uVar7 >> 2; uVar11 != 0; uVar11 = uVar11 - 1) {
      *(undefined4 *)pcVar17 = *(undefined4 *)pcVar18;
      pcVar18 = pcVar18 + 4;
      pcVar17 = pcVar17 + 4;
    }
    for (uVar7 = uVar7 & 3; uVar7 != 0; uVar7 = uVar7 - 1) {
      *pcVar17 = *pcVar18;
      pcVar18 = pcVar18 + 1;
      pcVar17 = pcVar17 + 1;
    }
    uVar7 = 0xffffffff;
    pcVar18 = &DAT_007350de + iVar6;
    do {
      pcVar17 = pcVar18;
      if (uVar7 == 0) break;
      uVar7 = uVar7 - 1;
      pcVar17 = pcVar18 + 1;
      cVar3 = *pcVar18;
      pcVar18 = pcVar17;
    } while (cVar3 != '\0');
    uVar7 = ~uVar7;
    iVar12 = -1;
    pcVar18 = pcVar14;
    do {
      pcVar16 = pcVar18;
      if (iVar12 == 0) break;
      iVar12 = iVar12 + -1;
      pcVar16 = pcVar18 + 1;
      cVar3 = *pcVar18;
      pcVar18 = pcVar16;
    } while (cVar3 != '\0');
    pcVar18 = pcVar17 + -uVar7;
    pcVar17 = pcVar16 + -1;
    for (uVar11 = uVar7 >> 2; uVar11 != 0; uVar11 = uVar11 - 1) {
      *(undefined4 *)pcVar17 = *(undefined4 *)pcVar18;
      pcVar18 = pcVar18 + 4;
      pcVar17 = pcVar17 + 4;
    }
    for (uVar7 = uVar7 & 3; uVar7 != 0; uVar7 = uVar7 - 1) {
      *pcVar17 = *pcVar18;
      pcVar18 = pcVar18 + 1;
      pcVar17 = pcVar17 + 1;
    }
    uVar7 = 0xffffffff;
    pcVar18 = &DAT_007350cd + iVar6;
    do {
      pcVar17 = pcVar18;
      if (uVar7 == 0) break;
      uVar7 = uVar7 - 1;
      pcVar17 = pcVar18 + 1;
      cVar3 = *pcVar18;
      pcVar18 = pcVar17;
    } while (cVar3 != '\0');
    uVar7 = ~uVar7;
    iVar12 = -1;
    pcVar18 = pcVar14;
    do {
      pcVar16 = pcVar18;
      if (iVar12 == 0) break;
      iVar12 = iVar12 + -1;
      pcVar16 = pcVar18 + 1;
      cVar3 = *pcVar18;
      pcVar18 = pcVar16;
    } while (cVar3 != '\0');
    pcVar18 = pcVar17 + -uVar7;
    pcVar17 = pcVar16 + -1;
    for (uVar11 = uVar7 >> 2; uVar11 != 0; uVar11 = uVar11 - 1) {
      *(undefined4 *)pcVar17 = *(undefined4 *)pcVar18;
      pcVar18 = pcVar18 + 4;
      pcVar17 = pcVar17 + 4;
    }
    for (uVar7 = uVar7 & 3; uVar7 != 0; uVar7 = uVar7 - 1) {
      *pcVar17 = *pcVar18;
      pcVar18 = pcVar18 + 1;
      pcVar17 = pcVar17 + 1;
    }
    if (bVar5) {
      uVar7 = 0xffffffff;
      DAT_00705ebc = 1;
      pcVar18 = &DAT_0051a834;
      do {
        pcVar17 = pcVar18;
        if (uVar7 == 0) break;
        uVar7 = uVar7 - 1;
        pcVar17 = pcVar18 + 1;
        cVar3 = *pcVar18;
        pcVar18 = pcVar17;
      } while (cVar3 != '\0');
      uVar7 = ~uVar7;
      iVar12 = -1;
      do {
        pcVar18 = pcVar14;
        if (iVar12 == 0) break;
        iVar12 = iVar12 + -1;
        pcVar18 = pcVar14 + 1;
        cVar3 = *pcVar14;
        pcVar14 = pcVar18;
      } while (cVar3 != '\0');
      pcVar14 = pcVar17 + -uVar7;
      pcVar18 = pcVar18 + -1;
      for (uVar11 = uVar7 >> 2; uVar11 != 0; uVar11 = uVar11 - 1) {
        *(undefined4 *)pcVar18 = *(undefined4 *)pcVar14;
        pcVar14 = pcVar14 + 4;
        pcVar18 = pcVar18 + 4;
      }
      for (uVar7 = uVar7 & 3; uVar7 != 0; uVar7 = uVar7 - 1) {
        *pcVar18 = *pcVar14;
        pcVar14 = pcVar14 + 1;
        pcVar18 = pcVar18 + 1;
      }
      goto switchD_0043e9d7_default;
    }
    switch(*(undefined4 *)(&DAT_0060b948 + iVar1)) {
    case 0:
      uVar7 = Game_Random_Mod(2);
      if ((uVar7 & 0xffff) == 0) {
        pcVar18 = &DAT_0051a7ac;
      }
      else {
        if ((uVar7 & 0xffff) != 1) goto switchD_0043e9d7_default;
        pcVar18 = &DAT_0051a7f8;
      }
      break;
    case 1:
      uVar7 = Game_Random_Mod(2);
      if ((uVar7 & 0xffff) == 0) {
        pcVar18 = &DAT_0051a748;
      }
      else {
        if ((uVar7 & 0xffff) != 1) goto switchD_0043e9d7_default;
        pcVar18 = &DAT_0051a784;
      }
      break;
    case 2:
      pcVar18 = &DAT_0051a6f8;
      break;
    case 3:
      pcVar18 = &DAT_0051a6cc;
      break;
    case 4:
      pcVar18 = &DAT_0051a68c;
      break;
    case 5:
      pcVar18 = &DAT_0051a650;
      break;
    case 6:
      pcVar18 = &DAT_0051a618;
      break;
    case 7:
      pcVar18 = &DAT_0051a5d8;
      break;
    case 8:
      pcVar18 = &DAT_0051a59c;
      break;
    default:
      goto switchD_0043e9d7_default;
    }
    uVar7 = 0xffffffff;
    do {
      pcVar17 = pcVar18;
      if (uVar7 == 0) break;
      uVar7 = uVar7 - 1;
      pcVar17 = pcVar18 + 1;
      cVar3 = *pcVar18;
      pcVar18 = pcVar17;
    } while (cVar3 != '\0');
    uVar7 = ~uVar7;
    pcVar17 = pcVar17 + -uVar7;
  }
  iVar12 = -1;
  do {
    pcVar18 = pcVar14;
    if (iVar12 == 0) break;
    iVar12 = iVar12 + -1;
    pcVar18 = pcVar14 + 1;
    cVar3 = *pcVar14;
    pcVar14 = pcVar18;
  } while (cVar3 != '\0');
  pcVar14 = pcVar18 + -1;
  for (uVar11 = uVar7 >> 2; uVar11 != 0; uVar11 = uVar11 - 1) {
    *(undefined4 *)pcVar14 = *(undefined4 *)pcVar17;
    pcVar17 = pcVar17 + 4;
    pcVar14 = pcVar14 + 4;
  }
  for (uVar7 = uVar7 & 3; uVar7 != 0; uVar7 = uVar7 - 1) {
    *pcVar14 = *pcVar17;
    pcVar17 = pcVar17 + 1;
    pcVar14 = pcVar14 + 1;
  }
switchD_0043e9d7_default:
  Diplomat_Talking(uVar8);
  DAT_00705ee8 = 0;
  return;
}
