/*
 * Generated by Ghidra headless decompiler from China2EX_fontfix8.exe.
 * Address request: 0x0041b6c0
 * This is reconstructed pseudocode, not original source.
 */


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */
/* WARNING: Unknown calling convention -- yet parameter storage is locked */

byte Irrigate_Able(LandTile_0x100 *tile,int tile_x,int tile_y,int allow_dry_neighbor)

{
  int iVar1;
  int iVar2;
  int iVar3;
  int iVar4;

  Trace_Function(s_Irrigate_Able_00514eb4);
  if ((((tile->battle_stat_terrain_mode == 0) && (tile->tile_work_kind != 0)) &&
      (tile->linked_record == (void *)0x0)) &&
     (g_ground_defs[*(char *)tile].irrigation_farmland_enabled != 0)) {
    if (((char)tile->region_or_terrain_marker_a < '\0') || (tile->linked_count_or_city_count < 0)) {
      return 1;
    }
    iVar1 = (tile_y & 1U) << 5;
    tile = (LandTile_0x100 *)0x0;
    iVar2 = allow_dry_neighbor;
    do {
      iVar4 = *(int *)((int)&DAT_00589374 + iVar1) + tile_x;
      iVar3 = *(int *)((int)&DAT_005893b4 + iVar1) + tile_y;
      if (((-1 < iVar3) && (iVar3 < g_map_height_tiles)) &&
         (((-1 < iVar4 && (iVar4 < g_map_width_tiles)) ||
          (g_current_map_scenario_info.horizontal_wrap_setting == 1)))) {
        if (iVar4 < 0) {
          iVar4 = iVar4 + g_map_width_tiles;
        }
        if (g_map_width_tiles <= iVar4) {
          iVar4 = iVar4 - g_map_width_tiles;
        }
        switch(g_map_size_mode) {
        case 0:
          iVar4 = iVar4 + iVar3 * 0x138;
          break;
        case 1:
          iVar4 = iVar4 + iVar3 * 0x9c;
          break;
        case 2:
          iVar4 = iVar4 + iVar3 * 0x4e;
          break;
        case 3:
          iVar4 = iVar3 * 0x27 + iVar4;
          break;
        default:
          goto switchD_0041b79a_default;
        }
        iVar2 = iVar4 * 0x100 + _g_land_tiles;
switchD_0041b79a_default:
        if (*(char *)(iVar2 + 0x12) < '\0') {
          return 1;
        }
        if (*(short *)(iVar2 + 0x10) < 0) {
          return 1;
        }
        if ((*(char *)(iVar2 + 0x1a) == '\0') && ((char)allow_dry_neighbor != '\0')) {
          return 1;
        }
      }
      iVar1 = iVar1 + 4;
      tile = (LandTile_0x100 *)&tile->field_0x1;
    } while ((int)tile < 8);
  }
  return 0;
}
