/*
 * Generated by Ghidra headless decompiler from China2EX_fontfix8.exe.
 * Address request: 0x004086e0
 * This is reconstructed pseudocode, not original source.
 */


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void NewLand_Name(int param_1,int param_2,uint param_3)

{
  byte bVar1;
  char cVar2;
  bool bVar3;
  char *pcVar4;
  byte *pbVar5;
  void **ppvVar6;
  int iVar7;
  uint uVar8;
  uint uVar9;
  int iVar10;
  byte *pbVar11;
  byte *pbVar12;
  char *pcVar13;
  bool bVar14;
  undefined *puVar15;
  undefined2 local_290;
  undefined1 local_28e;
  undefined2 local_28d;
  undefined1 local_28b;
  undefined1 local_288 [5];
  undefined1 local_283;
  undefined2 local_282;
  undefined1 local_280;
  undefined2 local_27f;
  undefined1 local_27d;
  undefined2 local_27c;
  undefined1 local_27a;
  undefined2 local_279;
  undefined1 local_277;
  undefined2 local_276;
  undefined1 local_274;
  undefined2 local_273;
  undefined1 local_271;
  undefined2 local_270;
  undefined1 local_26e;
  undefined2 local_26d;
  undefined1 local_26b;
  byte local_268 [20];
  int local_254;
  undefined4 local_250;
  undefined1 local_24c;
  undefined4 local_24b;
  undefined1 local_247;
  byte *local_244;
  undefined1 local_240 [192];
  undefined1 local_180 [192];
  undefined1 local_c0 [192];

  Trace_Function(s_NewLand_Name_00512290);
  if ('\0' < (char)(&DAT_005e0050)[param_1 * 0x20]) {
    return;
  }
  ppvVar6 = g_land_record_buffers;
  pcVar4 = &g_country_states;
  do {
    if (('\0' < *pcVar4) && (*(char *)((int)*ppvVar6 + param_1 * 4) == '\x01')) {
      return;
    }
    pcVar4 = pcVar4 + 0xe68;
    ppvVar6 = ppvVar6 + 1;
  } while ((int)pcVar4 < 0x748da8);
  local_250 = DAT_00512288;
  local_24c = DAT_0051228c;
  local_247 = DAT_00512284;
  local_24b = DAT_00512280;
  local_254 = param_1 * 0x14;
  bVar3 = *(int *)(param_1 * 0x14 + DAT_00755918) < 0x65;
  local_244 = (byte *)(&DAT_005e005c + param_1 * 8);
  iVar7 = -1;
  pbVar11 = local_244;
  do {
    if (iVar7 == 0) break;
    iVar7 = iVar7 + -1;
    bVar1 = *pbVar11;
    pbVar11 = pbVar11 + 1;
  } while (bVar1 != 0);
  if (iVar7 == -2) {
    local_290 = DAT_0051227c;
    local_28e = DAT_0051227e;
    local_28d = DAT_00512278;
    local_28b = DAT_0051227a;
    local_288._0_2_ = DAT_00512274;
    local_288[2] = DAT_00512276;
    local_288._3_2_ = DAT_00512270;
    local_283 = DAT_00512272;
    local_282 = DAT_0051226c;
    local_280 = DAT_0051226e;
    local_27f = DAT_00512268;
    local_27d = DAT_0051226a;
    local_27c = DAT_00512264;
    local_27a = DAT_00512266;
    local_279 = DAT_00512260;
    local_277 = DAT_00512262;
    local_276 = DAT_0051225c;
    local_274 = DAT_0051225e;
    local_273 = DAT_00512258;
    local_271 = DAT_0051225a;
    local_270 = DAT_00512254;
    local_26e = DAT_00512256;
    local_26d = DAT_00512250;
    local_26b = DAT_00512252;
    if (param_1 < 100) {
      if (param_1 < 10) {
        Format_Text(local_268,&DAT_00512224,(int)(char)g_active_country->name_bytes[0],
                    (int)(char)g_active_country->name_bytes[1],local_288 + param_1 * 3,
                    (int)&local_290 + bVar3 * 3);
      }
      else {
        Format_Text(local_268,&DAT_00512230,(int)(char)g_active_country->name_bytes[0],
                    (int)(char)g_active_country->name_bytes[1],local_288 + (param_1 / 10) * 3,
                    local_288 + (param_1 % 10) * 3,(int)&local_290 + bVar3 * 3);
      }
    }
    else {
      Format_Text(local_268,&DAT_00512240,(int)(char)g_active_country->name_bytes[0],
                  (int)(char)g_active_country->name_bytes[1],local_288 + (param_1 / 100) * 3,
                  local_288 + ((param_1 % 100) / 10) * 3,local_288 + ((param_1 % 100) % 10) * 3,
                  (int)&local_290 + bVar3 * 3);
    }
  }
  else {
    uVar8 = 0xffffffff;
    pbVar11 = local_244;
    do {
      pbVar12 = pbVar11;
      if (uVar8 == 0) break;
      uVar8 = uVar8 - 1;
      pbVar12 = pbVar11 + 1;
      bVar1 = *pbVar11;
      pbVar11 = pbVar12;
    } while (bVar1 != 0);
    uVar8 = ~uVar8;
    pbVar11 = pbVar12 + -uVar8;
    pbVar12 = local_268;
    for (uVar9 = uVar8 >> 2; uVar9 != 0; uVar9 = uVar9 - 1) {
      *(undefined4 *)pbVar12 = *(undefined4 *)pbVar11;
      pbVar11 = pbVar11 + 4;
      pbVar12 = pbVar12 + 4;
    }
    for (uVar8 = uVar8 & 3; uVar8 != 0; uVar8 = uVar8 - 1) {
      *pbVar12 = *pbVar11;
      pbVar11 = pbVar11 + 1;
      pbVar12 = pbVar12 + 1;
    }
  }
  iVar7 = _DAT_00748e34;
  if (_DAT_00748e34 == g_human_country_index) {
    if (g_auto_turn_or_ai_control_flag == 0) {
      uVar8 = 0xffffffff;
      pbVar11 = local_268;
      do {
        pbVar12 = pbVar11;
        if (uVar8 == 0) break;
        uVar8 = uVar8 - 1;
        pbVar12 = pbVar11 + 1;
        bVar1 = *pbVar11;
        pbVar11 = pbVar12;
      } while (bVar1 != 0);
      uVar8 = ~uVar8;
      pbVar11 = pbVar12 + -uVar8;
      pbVar12 = local_288;
      for (uVar9 = uVar8 >> 2; uVar9 != 0; uVar9 = uVar9 - 1) {
        *(undefined4 *)pbVar12 = *(undefined4 *)pbVar11;
        pbVar11 = pbVar11 + 4;
        pbVar12 = pbVar12 + 4;
      }
      pbVar5 = local_268;
      for (uVar8 = uVar8 & 3; uVar8 != 0; uVar8 = uVar8 - 1) {
        *pbVar12 = *pbVar11;
        pbVar11 = pbVar11 + 1;
        pbVar12 = pbVar12 + 1;
      }
      pbVar11 = &DAT_0051221c;
      do {
        bVar1 = *pbVar5;
        bVar14 = bVar1 < *pbVar11;
        if (bVar1 != *pbVar11) {
LAB_00408a5f:
          iVar7 = (1 - (uint)bVar14) - (uint)(bVar14 != 0);
          goto LAB_00408a64;
        }
        if (bVar1 == 0) break;
        bVar1 = pbVar5[1];
        bVar14 = bVar1 < pbVar11[1];
        if (bVar1 != pbVar11[1]) goto LAB_00408a5f;
        pbVar5 = pbVar5 + 2;
        pbVar11 = pbVar11 + 2;
      } while (bVar1 != 0);
      iVar7 = 0;
LAB_00408a64:
      _DAT_0074a348 = (param_3 & 1) + param_2;
      _DAT_0074a350 = param_3;
      g_request_redraw = 1;
      Font_Select(DAT_005dffbc,0xe,DAT_005dffb8,0xe);
      FUN_004f5f9c(0x150,0xf6,*(undefined4 *)(DAT_007585a4 + 0xdc));
      Format_Text(local_240,&DAT_005121f8,g_active_country->name_bytes);
      Draw_Text_Centered(0x15e,0x104,local_240,0xffffffff,DAT_007350b4,0xffffffff,0xffffffff);
      FUN_00420d20(0x1b2,0x11c,local_288,1,DAT_007350b4,0xe,0x10,1,0);
      iVar10 = -1;
      pcVar4 = local_288;
      do {
        if (iVar10 == 0) break;
        iVar10 = iVar10 + -1;
        cVar2 = *pcVar4;
        pcVar4 = pcVar4 + 1;
      } while (cVar2 != '\0');
      if (iVar10 != -2) {
        uVar8 = 0xffffffff;
        pcVar4 = local_288;
        do {
          pcVar13 = pcVar4;
          if (uVar8 == 0) break;
          uVar8 = uVar8 - 1;
          pcVar13 = pcVar4 + 1;
          cVar2 = *pcVar4;
          pcVar4 = pcVar13;
        } while (cVar2 != '\0');
        uVar8 = ~uVar8;
        pbVar11 = (byte *)(pcVar13 + -uVar8);
        pbVar12 = local_268;
        for (uVar9 = uVar8 >> 2; uVar9 != 0; uVar9 = uVar9 - 1) {
          *(undefined4 *)pbVar12 = *(undefined4 *)pbVar11;
          pbVar11 = pbVar11 + 4;
          pbVar12 = pbVar12 + 4;
        }
        for (uVar8 = uVar8 & 3; uVar8 != 0; uVar8 = uVar8 - 1) {
          *pbVar12 = *pbVar11;
          pbVar11 = pbVar11 + 1;
          pbVar12 = pbVar12 + 1;
        }
      }
      FUN_00502ab0();
      pbVar12 = &DAT_0051221c;
      pbVar11 = local_288;
      do {
        bVar1 = *pbVar11;
        bVar14 = bVar1 < *pbVar12;
        if (bVar1 != *pbVar12) {
LAB_00408b92:
          iVar10 = (1 - (uint)bVar14) - (uint)(bVar14 != 0);
          goto LAB_00408b97;
        }
        if (bVar1 == 0) break;
        bVar1 = pbVar11[1];
        bVar14 = bVar1 < pbVar12[1];
        if (bVar1 != pbVar12[1]) goto LAB_00408b92;
        pbVar11 = pbVar11 + 2;
        pbVar12 = pbVar12 + 2;
      } while (bVar1 != 0);
      iVar10 = 0;
LAB_00408b97:
      if ((iVar10 == 0) && (iVar7 == 0)) {
        FUN_0041f2b0(g_human_country_index,0,0xc03e0000);
        FUN_00443e00(g_human_country_index,&DAT_005121b0,&DAT_005121c4,5,5);
      }
    }
    iVar7 = _DAT_00748e34;
    if (_DAT_00748e34 == g_human_country_index) {
      Format_Text(local_240,&DAT_005121a0,_DAT_00748e30 + 4,local_268);
      FUN_00489e20(_DAT_00748e34,0xffffffff,0xffffffff,local_240);
      iVar7 = _DAT_00748e34;
      (&DAT_005e0050)[param_1 * 0x20] = 2;
    }
  }
  if (((DAT_0074a2d2 == '\0') && (DAT_00755940 == 0)) && (DAT_00755958 == 0)) {
    return;
  }
  if ((iVar7 != g_human_country_index) || (DAT_0074a2cc != '\x01')) {
    if (((*(int *)(_DAT_00748e30 + 0x1ac + iVar7 * 4) < 2) || (iVar7 == 0)) && (DAT_00755940 == 0))
    {
      return;
    }
    if (DAT_0074a2cd != '\x01') {
      return;
    }
  }
  pbVar11 = (byte *)((int)&local_250 + bVar3 * 5);
  Format_Text(local_180,&DAT_00512180,g_active_country->name_bytes,pbVar11,local_268);
  FUN_004898b0(DAT_00755910,local_180,1,param_2,param_3);
  iVar7 = g_map_size_mode;
  uVar8 = 0xffffffff;
  pbVar12 = local_268;
  do {
    pbVar5 = pbVar12;
    if (uVar8 == 0) break;
    uVar8 = uVar8 - 1;
    pbVar5 = pbVar12 + 1;
    bVar1 = *pbVar12;
    pbVar12 = pbVar5;
  } while (bVar1 != 0);
  uVar8 = ~uVar8;
  pbVar12 = pbVar5 + -uVar8;
  pbVar5 = local_244;
  for (uVar9 = uVar8 >> 2; uVar9 != 0; uVar9 = uVar9 - 1) {
    *(undefined4 *)pbVar5 = *(undefined4 *)pbVar12;
    pbVar12 = pbVar12 + 4;
    pbVar5 = pbVar5 + 4;
  }
  for (uVar8 = uVar8 & 3; uVar8 != 0; uVar8 = uVar8 - 1) {
    *pbVar5 = *pbVar12;
    pbVar12 = pbVar12 + 1;
    pbVar5 = pbVar5 + 1;
  }
  iVar10 = local_254;
  switch(iVar7) {
  case 0:
    iVar10 = (param_2 + param_3 * 0x138) * 0x100 + _g_land_tiles;
    break;
  case 1:
    iVar10 = (param_2 + param_3 * 0x9c) * 0x100 + _g_land_tiles;
    break;
  case 2:
    iVar10 = (param_2 + param_3 * 0x4e) * 0x100 + _g_land_tiles;
    break;
  case 3:
    iVar10 = (param_3 * 0x27 + param_2) * 0x100 + _g_land_tiles;
  }
  if (*(char *)(iVar10 + 0xb5 + g_human_country_index) == '\0') {
    return;
  }
  uVar8 = 0xffffffff;
  pbVar12 = local_268;
  do {
    pbVar5 = pbVar12;
    if (uVar8 == 0) break;
    uVar8 = uVar8 - 1;
    pbVar5 = pbVar12 + 1;
    bVar1 = *pbVar12;
    pbVar12 = pbVar5;
  } while (bVar1 != 0);
  uVar8 = ~uVar8;
  pbVar12 = pbVar5 + -uVar8;
  pbVar5 = (byte *)(local_254 + 4 + DAT_00755918);
  for (uVar9 = uVar8 >> 2; uVar9 != 0; uVar9 = uVar9 - 1) {
    *(undefined4 *)pbVar5 = *(undefined4 *)pbVar12;
    pbVar12 = pbVar12 + 4;
    pbVar5 = pbVar5 + 4;
  }
  for (uVar8 = uVar8 & 3; uVar8 != 0; uVar8 = uVar8 - 1) {
    *pbVar5 = *pbVar12;
    pbVar12 = pbVar12 + 1;
    pbVar5 = pbVar5 + 1;
  }
  Format_Text(local_c0,&DAT_00512170,g_active_country->name_bytes,pbVar11);
  uVar8 = Game_Random_Mod(4);
  switch(uVar8 & 0xffff) {
  case 0:
    Format_Text(local_240,&DAT_00512148,local_268);
    break;
  case 1:
    Format_Text(local_240,&DAT_0051211c,pbVar11,local_268);
    break;
  case 2:
    pbVar12 = local_268;
    puVar15 = &DAT_005120e4;
    pbVar5 = pbVar11;
    goto LAB_00408e5e;
  case 3:
    puVar15 = &DAT_005120bc;
    pbVar5 = local_268;
    pbVar12 = pbVar11;
LAB_00408e5e:
    Format_Text(local_240,puVar15,g_active_country->name_bytes,pbVar5,pbVar12);
  }
  FUN_00443e00(_DAT_00748e34,local_c0,local_240,0,5);
  return;
}
