/*
 * Generated by Ghidra headless decompiler from China2EX_fontfix8.exe.
 * Address request: 0x00496bd0
 * This is reconstructed pseudocode, not original source.
 */


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void Order_Join_Sel(void)

{
  undefined4 *puVar1;
  byte *pbVar2;
  int iVar3;
  undefined4 *puVar4;
  byte *pbVar5;
  undefined4 *puVar6;
  int iVar7;
  undefined4 *local_8;
  int local_4;
  
  Trace_Function(s_Order_Join_Sel_0057e3d4);
  iVar7 = 0;
  if (((DAT_007584dc != (byte *)0x0) && (DAT_007584dc[0x127] == 0)) &&
     ('\x01' < *(char *)(DAT_007584ec + 0x50))) {
    puVar1 = (undefined4 *)(DAT_007584ec + 0x28);
    _DAT_00749b2c = 0;
    DAT_0074c824 = 0;
    local_4 = 10;
    pbVar5 = DAT_007584dc;
    local_8 = puVar1;
    do {
      pbVar2 = (byte *)*local_8;
      if (((pbVar2 != (byte *)0x0) && (pbVar2 != pbVar5)) &&
         ((*(int *)(pbVar2 + 0x144) == 0 &&
          (*(int *)&g_army_type_table[*pbVar2].field_0x13c == *(int *)(_DAT_0074a0b8 + 0x13c))))) {
        *(byte **)(&DAT_00748ff4 + iVar7 * 0x28) = pbVar2;
        if (pbVar2[0x148] != 0) {
          puVar6 = (undefined4 *)(&DAT_00748ff8 + iVar7 * 0x28);
          puVar4 = puVar6;
          for (iVar3 = 9; iVar3 != 0; iVar3 = iVar3 + -1) {
            *puVar4 = 0;
            puVar4 = puVar4 + 1;
          }
          iVar3 = 10;
          puVar4 = puVar1;
          do {
            pbVar5 = (byte *)*puVar4;
            if (((pbVar5 != (byte *)0x0) && (pbVar5 != DAT_007584dc)) &&
               (*(byte **)(pbVar5 + 0x14c) == pbVar2)) {
              *puVar6 = pbVar5;
              puVar6 = puVar6 + 1;
            }
            puVar4 = puVar4 + 1;
            iVar3 = iVar3 + -1;
          } while (iVar3 != 0);
          if ((int)DAT_0074c824 < (int)(uint)pbVar2[0x148]) {
            DAT_0074c824 = (uint)pbVar2[0x148];
          }
        }
        iVar7 = iVar7 + 1;
        pbVar5 = DAT_007584dc;
        _DAT_00749b2c = iVar7;
      }
      local_8 = local_8 + 1;
      local_4 = local_4 + -1;
    } while (local_4 != 0);
    if (iVar7 == 1) {
      FUN_004711f0(pbVar5,_DAT_00748ff4);
      FUN_0041ec80();
      return;
    }
    DAT_0074c06e = 1;
    _DAT_0057e1e8 = 0xffffffff;
    FUN_00472120(&DAT_005c3478);
  }
  return;
}

