/*
 * Generated by Ghidra headless decompiler from China2EX_fontfix8.exe.
 * Address request: 0x00494110
 * This is reconstructed pseudocode, not original source.
 */


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void Order_Check(void)

{
  char cVar1;
  byte bVar2;
  ArmyUnit_0x164_plus *pAVar3;
  ArmyUnit_0x164_plus *pAVar4;
  bool bVar5;
  bool bVar6;
  LandTile_0x100 *pLVar7;
  int iVar8;
  ArmyUnit_0x164_plus **ppAVar9;
  int iVar10;
  int iVar11;
  uint uVar12;
  uint uVar13;
  int iVar14;
  int iVar15;
  char *pcVar16;
  char *pcVar17;
  undefined4 *puVar18;
  char *pcVar19;
  uint local_c;
  int local_8;
  int local_4;

  Trace_Function(s_Order_Check_0057e2d8);
  iVar14 = 0;
  DAT_0057e1ec = 0xffffffff;
  if (DAT_007584dc->mission_action_id == 0x41) {
    if (*(int *)(DAT_007584e4 + 0xc) == 0) {
      iVar8 = ((int)DAT_007584dc->tile_y & 1U) << 5;
      local_8 = 0;
      iVar11 = (int)DAT_007584dc->tile_x;
      do {
        iVar15 = *(int *)((int)&DAT_00589374 + iVar8) + (int)DAT_007584dc->tile_x;
        iVar10 = *(int *)((int)&DAT_005893b4 + iVar8) + (int)DAT_007584dc->tile_y;
        if (((-1 < iVar10) && (iVar10 < g_map_height_tiles)) &&
           (((-1 < iVar15 && (iVar15 < g_map_width_tiles)) ||
            (g_current_map_scenario_info.horizontal_wrap_enabled == 1)))) {
          if (iVar15 < 0) {
            iVar15 = iVar15 + g_map_width_tiles;
          }
          if (g_map_width_tiles <= iVar15) {
            iVar15 = iVar15 - g_map_width_tiles;
          }
          switch(g_map_size_mode) {
          case 0:
            iVar15 = iVar15 + iVar10 * 0x138;
            break;
          case 1:
            iVar15 = iVar15 + iVar10 * 0x9c;
            break;
          case 2:
            iVar15 = iVar15 + iVar10 * 0x4e;
            break;
          case 3:
            iVar15 = iVar10 * 0x27 + iVar15;
            break;
          default:
            goto switchD_004941d6_default;
          }
          iVar11 = iVar15 * 0x100 + _g_land_tiles;
switchD_004941d6_default:
          if (0 < *(short *)(iVar11 + 0x10)) {
            uVar12 = 0xffffffff;
            DAT_00714ffc = 0x20;
            pcVar17 = &DAT_0057e2d0;
            goto code_r0x0049424c;
          }
        }
        iVar8 = iVar8 + 4;
        local_8 = local_8 + 1;
      } while (local_8 < 8);
    }
    else {
      uVar12 = 0xffffffff;
      DAT_00714ffc = 0x20;
      pcVar17 = &DAT_0057e2c8;
      do {
        pcVar16 = pcVar17;
        if (uVar12 == 0) break;
        uVar12 = uVar12 - 1;
        pcVar16 = pcVar17 + 1;
        cVar1 = *pcVar17;
        pcVar17 = pcVar16;
      } while (cVar1 != '\0');
      uVar12 = ~uVar12;
      iVar14 = 1;
      pcVar17 = pcVar16 + -uVar12;
      pcVar16 = (char *)&DAT_00714f98;
      for (uVar13 = uVar12 >> 2; uVar13 != 0; uVar13 = uVar13 - 1) {
        *(undefined4 *)pcVar16 = *(undefined4 *)pcVar17;
        pcVar17 = pcVar17 + 4;
        pcVar16 = pcVar16 + 4;
      }
      for (uVar12 = uVar12 & 3; uVar12 != 0; uVar12 = uVar12 - 1) {
        *pcVar16 = *pcVar17;
        pcVar17 = pcVar17 + 1;
        pcVar16 = pcVar16 + 1;
      }
    }
    goto LAB_004950fa;
  }
  if (DAT_007584dc->mission_action_id != 0x47) {
    if (((DAT_007584dc->cargo_or_subunit_count != 0) && (0 < *(int *)(DAT_007584e4 + 300))) &&
       (DAT_007584ec->linked_record != (void *)0x0)) {
      uVar12 = 0xffffffff;
      DAT_00714ffc = 0x46;
      pcVar17 = &DAT_0057e2b0;
      do {
        pcVar16 = pcVar17;
        if (uVar12 == 0) break;
        uVar12 = uVar12 - 1;
        pcVar16 = pcVar17 + 1;
        cVar1 = *pcVar17;
        pcVar17 = pcVar16;
      } while (cVar1 != '\0');
      uVar12 = ~uVar12;
      pcVar17 = pcVar16 + -uVar12;
      pcVar16 = (char *)&DAT_00714f98;
      for (uVar13 = uVar12 >> 2; uVar13 != 0; uVar13 = uVar13 - 1) {
        *(undefined4 *)pcVar16 = *(undefined4 *)pcVar17;
        pcVar17 = pcVar17 + 4;
        pcVar16 = pcVar16 + 4;
      }
      iVar14 = 1;
      for (uVar12 = uVar12 & 3; uVar12 != 0; uVar12 = uVar12 - 1) {
        *pcVar16 = *pcVar17;
        pcVar17 = pcVar17 + 1;
        pcVar16 = pcVar16 + 1;
      }
    }
    puVar18 = &DAT_0074c074;
    for (iVar11 = 10; iVar11 != 0; iVar11 = iVar11 + -1) {
      *puVar18 = 0xffffffff;
      puVar18 = puVar18 + 1;
    }
    _DAT_0074a5e0 = 0;
    puVar18 = (undefined4 *)&DAT_00748ea4;
    for (iVar11 = 10; iVar11 != 0; iVar11 = iVar11 + -1) {
      *puVar18 = 0xffffffff;
      puVar18 = puVar18 + 1;
    }
    DAT_0074c848 = 0;
    local_c = *(uint *)(DAT_007584e4 + 0x144);
    if ((0 < (int)local_c) && (DAT_007584dc->transport_parent == (ArmyUnit_0x164_plus *)0x0)) {
      bVar5 = true;
      if (DAT_007584dc->cargo_or_subunit_count != 0) {
        iVar8 = 0;
        iVar11 = (int)(char)DAT_007584ec->army_count_or_occupant_count;
        ppAVar9 = DAT_007584ec->army_or_city_ptrs_a;
        do {
          if (iVar11 < 1) break;
          pAVar3 = *ppAVar9;
          if (pAVar3 != (ArmyUnit_0x164_plus *)0x0) {
            if ((pAVar3 != DAT_007584dc) && (pAVar3->transport_parent == DAT_007584dc)) {
              uVar12 = g_army_type_table[pAVar3->army_type_id].transportable_mask;
              if (uVar12 == 0) {
                bVar5 = false;
              }
              else if ((int)local_c < (int)uVar12) {
                local_c = uVar12;
              }
            }
            iVar11 = iVar11 + -1;
          }
          iVar8 = iVar8 + 1;
          ppAVar9 = ppAVar9 + 1;
        } while (iVar8 < 10);
        if (!bVar5) goto LAB_004945b4;
      }
      iVar11 = 0;
      local_8 = (int)(char)DAT_007584ec->army_count_or_occupant_count;
      ppAVar9 = DAT_007584ec->army_or_city_ptrs_a;
      do {
        if (local_8 < 1) break;
        pAVar3 = *ppAVar9;
        if (pAVar3 != (ArmyUnit_0x164_plus *)0x0) {
          if (pAVar3 != DAT_007584dc) {
            bVar2 = pAVar3->army_type_id;
            if (((g_army_type_table[bVar2].air_or_city_capability_mask & local_c) != 0) &&
               ((int)(pAVar3->cargo_or_subunit_count + 1 +
                     (uint)DAT_007584dc->cargo_or_subunit_count) <=
                g_army_type_table[bVar2].transport_capacity)) {
              if (g_army_type_table[bVar2].unit_class == 1) {
                (&DAT_0074c074)[_DAT_0074a5e0] = iVar11;
                _DAT_0074a5e0 = _DAT_0074a5e0 + 1;
              }
              else if ((DAT_007584ec->linked_record != (void *)0x0) || (bVar2 == 0x3a)) {
                *(int *)(&DAT_00748ea4 + DAT_0074c848 * 4) = iVar11;
                DAT_0074c848 = DAT_0074c848 + 1;
              }
            }
          }
          local_8 = local_8 + -1;
        }
        iVar11 = iVar11 + 1;
        ppAVar9 = ppAVar9 + 1;
      } while (iVar11 < 10);
      if (0 < _DAT_0074a5e0) {
        uVar12 = 0xffffffff;
        pcVar17 = &DAT_0057e2a8;
        do {
          pcVar16 = pcVar17;
          if (uVar12 == 0) break;
          uVar12 = uVar12 - 1;
          pcVar16 = pcVar17 + 1;
          cVar1 = *pcVar17;
          pcVar17 = pcVar16;
        } while (cVar1 != '\0');
        uVar12 = ~uVar12;
        (&DAT_00714ffc)[iVar14] = 0x41;
        pcVar17 = pcVar16 + -uVar12;
        pcVar16 = (char *)((int)&DAT_00714f98 + iVar14 * 5);
        for (uVar13 = uVar12 >> 2; uVar13 != 0; uVar13 = uVar13 - 1) {
          *(undefined4 *)pcVar16 = *(undefined4 *)pcVar17;
          pcVar17 = pcVar17 + 4;
          pcVar16 = pcVar16 + 4;
        }
        iVar14 = iVar14 + 1;
        for (uVar12 = uVar12 & 3; uVar12 != 0; uVar12 = uVar12 - 1) {
          *pcVar16 = *pcVar17;
          pcVar17 = pcVar17 + 1;
          pcVar16 = pcVar16 + 1;
        }
      }
      if (0 < DAT_0074c848) {
        uVar12 = 0xffffffff;
        pcVar17 = &DAT_0057e2a0;
        do {
          pcVar16 = pcVar17;
          if (uVar12 == 0) break;
          uVar12 = uVar12 - 1;
          pcVar16 = pcVar17 + 1;
          cVar1 = *pcVar17;
          pcVar17 = pcVar16;
        } while (cVar1 != '\0');
        uVar12 = ~uVar12;
        (&DAT_00714ffc)[iVar14] = 0x47;
        pcVar17 = pcVar16 + -uVar12;
        pcVar16 = (char *)((int)&DAT_00714f98 + iVar14 * 5);
        for (uVar13 = uVar12 >> 2; uVar13 != 0; uVar13 = uVar13 - 1) {
          *(undefined4 *)pcVar16 = *(undefined4 *)pcVar17;
          pcVar17 = pcVar17 + 4;
          pcVar16 = pcVar16 + 4;
        }
        iVar14 = iVar14 + 1;
        for (uVar12 = uVar12 & 3; uVar12 != 0; uVar12 = uVar12 - 1) {
          *pcVar16 = *pcVar17;
          pcVar17 = pcVar17 + 1;
          pcVar16 = pcVar16 + 1;
        }
      }
    }
LAB_004945b4:
    if (DAT_007584dc->army_type_id == 0) {
      if (DAT_007584ec->linked_record == (void *)0x0) {
        if ((DAT_007584ec->region_or_terrain_marker_a == 0) &&
           (0 < DAT_007584ec->linked_count_or_city_count)) {
          uVar12 = 0xffffffff;
          pcVar17 = &DAT_0057e298;
          do {
            pcVar16 = pcVar17;
            if (uVar12 == 0) break;
            uVar12 = uVar12 - 1;
            pcVar16 = pcVar17 + 1;
            cVar1 = *pcVar17;
            pcVar17 = pcVar16;
          } while (cVar1 != '\0');
          uVar12 = ~uVar12;
          (&DAT_00714ffc)[iVar14] = 1;
          pcVar17 = pcVar16 + -uVar12;
          pcVar16 = (char *)((int)&DAT_00714f98 + iVar14 * 5);
          for (uVar13 = uVar12 >> 2; uVar13 != 0; uVar13 = uVar13 - 1) {
            *(undefined4 *)pcVar16 = *(undefined4 *)pcVar17;
            pcVar17 = pcVar17 + 4;
            pcVar16 = pcVar16 + 4;
          }
          for (uVar12 = uVar12 & 3; uVar12 != 0; uVar12 = uVar12 - 1) {
            *pcVar16 = *pcVar17;
            pcVar17 = pcVar17 + 1;
            pcVar16 = pcVar16 + 1;
          }
LAB_00494657:
          iVar14 = iVar14 + 1;
        }
      }
      else if (g_current_map_scenario_info.scenario_value_30 < 2) {
        uVar12 = 0xffffffff;
        pcVar17 = &DAT_00574f60;
        do {
          pcVar16 = pcVar17;
          if (uVar12 == 0) break;
          uVar12 = uVar12 - 1;
          pcVar16 = pcVar17 + 1;
          cVar1 = *pcVar17;
          pcVar17 = pcVar16;
        } while (cVar1 != '\0');
        uVar12 = ~uVar12;
        (&DAT_00714ffc)[iVar14] = 0x1f;
        pcVar17 = pcVar16 + -uVar12;
        pcVar16 = (char *)((int)&DAT_00714f98 + iVar14 * 5);
        for (uVar13 = uVar12 >> 2; uVar13 != 0; uVar13 = uVar13 - 1) {
          *(undefined4 *)pcVar16 = *(undefined4 *)pcVar17;
          pcVar17 = pcVar17 + 4;
          pcVar16 = pcVar16 + 4;
        }
        for (uVar12 = uVar12 & 3; uVar12 != 0; uVar12 = uVar12 - 1) {
          *pcVar16 = *pcVar17;
          pcVar17 = pcVar17 + 1;
          pcVar16 = pcVar16 + 1;
        }
        goto LAB_00494657;
      }
    }
    iVar11 = DAT_007584e4;
    if (0 < *(int *)(DAT_007584e4 + 0x110)) {
      uVar12 = 0xffffffff;
      pcVar17 = (char *)&DAT_0057c9c8;
      do {
        pcVar16 = pcVar17;
        if (uVar12 == 0) break;
        uVar12 = uVar12 - 1;
        pcVar16 = pcVar17 + 1;
        cVar1 = *pcVar17;
        pcVar17 = pcVar16;
      } while (cVar1 != '\0');
      uVar12 = ~uVar12;
      (&DAT_00714ffc)[iVar14] = 0x1c;
      pcVar17 = pcVar16 + -uVar12;
      pcVar16 = (char *)((int)&DAT_00714f98 + iVar14 * 5);
      for (uVar13 = uVar12 >> 2; iVar11 = DAT_007584e4, uVar13 != 0; uVar13 = uVar13 - 1) {
        *(undefined4 *)pcVar16 = *(undefined4 *)pcVar17;
        pcVar17 = pcVar17 + 4;
        pcVar16 = pcVar16 + 4;
      }
      iVar14 = iVar14 + 1;
      for (uVar12 = uVar12 & 3; uVar12 != 0; uVar12 = uVar12 - 1) {
        *pcVar16 = *pcVar17;
        pcVar17 = pcVar17 + 1;
        pcVar16 = pcVar16 + 1;
      }
    }
    iVar8 = iVar11;
    if ((((1 < *(int *)(iVar11 + 0xf8)) || (1 < *(int *)(iVar11 + 0xfc))) ||
        (iVar8 = DAT_007584e4, 1 < *(int *)(iVar11 + 0x100))) &&
       ((iVar11 = iVar8, 0 < *(short *)&DAT_007584dc->field_0x12c ||
        (iVar11 = DAT_007584e4, *(int *)(iVar8 + 0x110) == 0)))) {
      pcVar17 = (char *)((int)&DAT_00714f98 + iVar14 * 5);
      if (*(int *)(iVar11 + 0x124) < 2) {
        uVar12 = 0xffffffff;
        (&DAT_00714ffc)[iVar14] = 0x1d;
        pcVar16 = (char *)&DAT_00570cfc;
        do {
          pcVar19 = pcVar16;
          if (uVar12 == 0) break;
          uVar12 = uVar12 - 1;
          pcVar19 = pcVar16 + 1;
          cVar1 = *pcVar16;
          pcVar16 = pcVar19;
        } while (cVar1 != '\0');
        uVar12 = ~uVar12;
        pcVar16 = pcVar19 + -uVar12;
        for (uVar13 = uVar12 >> 2; uVar13 != 0; uVar13 = uVar13 - 1) {
          *(undefined4 *)pcVar17 = *(undefined4 *)pcVar16;
          pcVar16 = pcVar16 + 4;
          pcVar17 = pcVar17 + 4;
        }
        for (uVar12 = uVar12 & 3; uVar12 != 0; uVar12 = uVar12 - 1) {
          *pcVar17 = *pcVar16;
          pcVar16 = pcVar16 + 1;
          pcVar17 = pcVar17 + 1;
        }
      }
      else {
        uVar12 = 0xffffffff;
        (&DAT_00714ffc)[iVar14] = 0x1e;
        pcVar16 = &DAT_0057e290;
        do {
          pcVar19 = pcVar16;
          if (uVar12 == 0) break;
          uVar12 = uVar12 - 1;
          pcVar19 = pcVar16 + 1;
          cVar1 = *pcVar16;
          pcVar16 = pcVar19;
        } while (cVar1 != '\0');
        uVar12 = ~uVar12;
        pcVar16 = pcVar19 + -uVar12;
        for (uVar13 = uVar12 >> 2; uVar13 != 0; uVar13 = uVar13 - 1) {
          *(undefined4 *)pcVar17 = *(undefined4 *)pcVar16;
          pcVar16 = pcVar16 + 4;
          pcVar17 = pcVar17 + 4;
        }
        for (uVar12 = uVar12 & 3; uVar12 != 0; uVar12 = uVar12 - 1) {
          *pcVar17 = *pcVar16;
          pcVar16 = pcVar16 + 1;
          pcVar17 = pcVar17 + 1;
        }
      }
      iVar14 = iVar14 + 1;
    }
    if ((0 < *(int *)(DAT_007584e4 + 0x110)) && (*(int *)(DAT_007584e4 + 0x124) != 2)) {
      uVar12 = 0xffffffff;
      pcVar17 = &DAT_0057e288;
      do {
        pcVar16 = pcVar17;
        if (uVar12 == 0) break;
        uVar12 = uVar12 - 1;
        pcVar16 = pcVar17 + 1;
        cVar1 = *pcVar17;
        pcVar17 = pcVar16;
      } while (cVar1 != '\0');
      uVar12 = ~uVar12;
      (&DAT_00714ffc)[iVar14] = 2;
      pcVar17 = pcVar16 + -uVar12;
      pcVar16 = (char *)((int)&DAT_00714f98 + iVar14 * 5);
      for (uVar13 = uVar12 >> 2; uVar13 != 0; uVar13 = uVar13 - 1) {
        *(undefined4 *)pcVar16 = *(undefined4 *)pcVar17;
        pcVar17 = pcVar17 + 4;
        pcVar16 = pcVar16 + 4;
      }
      iVar14 = iVar14 + 1;
      for (uVar12 = uVar12 & 3; uVar12 != 0; uVar12 = uVar12 - 1) {
        *pcVar16 = *pcVar17;
        pcVar17 = pcVar17 + 1;
        pcVar16 = pcVar16 + 1;
      }
    }
    uVar12 = 0xffffffff;
    pcVar17 = &DAT_0057e280;
    do {
      pcVar16 = pcVar17;
      if (uVar12 == 0) break;
      uVar12 = uVar12 - 1;
      pcVar16 = pcVar17 + 1;
      cVar1 = *pcVar17;
      pcVar17 = pcVar16;
    } while (cVar1 != '\0');
    uVar12 = ~uVar12;
    (&DAT_00714ffc)[iVar14] = 3;
    pcVar17 = pcVar16 + -uVar12;
    pcVar16 = (char *)((int)&DAT_00714f98 + iVar14 * 5);
    for (uVar13 = uVar12 >> 2; uVar13 != 0; uVar13 = uVar13 - 1) {
      *(undefined4 *)pcVar16 = *(undefined4 *)pcVar17;
      pcVar17 = pcVar17 + 4;
      pcVar16 = pcVar16 + 4;
    }
    DAT_00714f94 = iVar14 + 1;
    for (uVar12 = uVar12 & 3; uVar12 != 0; uVar12 = uVar12 - 1) {
      *pcVar16 = *pcVar17;
      pcVar17 = pcVar17 + 1;
      pcVar16 = pcVar16 + 1;
    }
    if ((DAT_007584dc->army_type_id == 1) || (DAT_007584dc->army_type_id == 0x3e)) {
      if (DAT_007584dc->field_0x126 == '\x01') {
        uVar12 = 0xffffffff;
        pcVar17 = &DAT_0057e278;
        do {
          pcVar16 = pcVar17;
          if (uVar12 == 0) break;
          uVar12 = uVar12 - 1;
          pcVar16 = pcVar17 + 1;
          cVar1 = *pcVar17;
          pcVar17 = pcVar16;
        } while (cVar1 != '\0');
        uVar12 = ~uVar12;
        (&DAT_00714ffc)[DAT_00714f94] = 0x1b;
        pcVar17 = pcVar16 + -uVar12;
        pcVar16 = (char *)(iVar14 + 0x714f99 + DAT_00714f94 * 4);
        for (uVar13 = uVar12 >> 2; uVar13 != 0; uVar13 = uVar13 - 1) {
          *(undefined4 *)pcVar16 = *(undefined4 *)pcVar17;
          pcVar17 = pcVar17 + 4;
          pcVar16 = pcVar16 + 4;
        }
        for (uVar12 = uVar12 & 3; uVar12 != 0; uVar12 = uVar12 - 1) {
          *pcVar16 = *pcVar17;
          pcVar17 = pcVar17 + 1;
          pcVar16 = pcVar16 + 1;
        }
      }
      else {
        uVar12 = 0xffffffff;
        pcVar17 = &DAT_0057e270;
        do {
          pcVar16 = pcVar17;
          if (uVar12 == 0) break;
          uVar12 = uVar12 - 1;
          pcVar16 = pcVar17 + 1;
          cVar1 = *pcVar17;
          pcVar17 = pcVar16;
        } while (cVar1 != '\0');
        uVar12 = ~uVar12;
        (&DAT_00714ffc)[DAT_00714f94] = 0x1a;
        (&DAT_00715000)[DAT_00714f94] = 0x21;
        pcVar17 = pcVar16 + -uVar12;
        pcVar16 = (char *)(iVar14 + 0x714f99 + DAT_00714f94 * 4);
        for (uVar13 = uVar12 >> 2; uVar13 != 0; uVar13 = uVar13 - 1) {
          *(undefined4 *)pcVar16 = *(undefined4 *)pcVar17;
          pcVar17 = pcVar17 + 4;
          pcVar16 = pcVar16 + 4;
        }
        for (uVar12 = uVar12 & 3; iVar11 = _DAT_00748e30, uVar12 != 0; uVar12 = uVar12 - 1) {
          *pcVar16 = *pcVar17;
          pcVar17 = pcVar17 + 1;
          pcVar16 = pcVar16 + 1;
        }
        uVar12 = 0xffffffff;
        pcVar17 = (char *)&DAT_0057e268;
        do {
          pcVar16 = pcVar17;
          if (uVar12 == 0) break;
          uVar12 = uVar12 - 1;
          pcVar16 = pcVar17 + 1;
          cVar1 = *pcVar17;
          pcVar17 = pcVar16;
        } while (cVar1 != '\0');
        uVar12 = ~uVar12;
        pcVar17 = pcVar16 + -uVar12;
        pcVar16 = (char *)((int)&DAT_00714fa2 + iVar14 * 5);
        for (uVar13 = uVar12 >> 2; uVar13 != 0; uVar13 = uVar13 - 1) {
          *(undefined4 *)pcVar16 = *(undefined4 *)pcVar17;
          pcVar17 = pcVar17 + 4;
          pcVar16 = pcVar16 + 4;
        }
        DAT_00714f94 = iVar14 + 3;
        for (uVar12 = uVar12 & 3; uVar12 != 0; uVar12 = uVar12 - 1) {
          *pcVar16 = *pcVar17;
          pcVar17 = pcVar17 + 1;
          pcVar16 = pcVar16 + 1;
        }
        if (*(int *)(iVar11 + 0x7b4) == 2) {
          uVar12 = 0xffffffff;
          pcVar17 = (char *)&DAT_00572b04;
          do {
            pcVar16 = pcVar17;
            if (uVar12 == 0) break;
            uVar12 = uVar12 - 1;
            pcVar16 = pcVar17 + 1;
            cVar1 = *pcVar17;
            pcVar17 = pcVar16;
          } while (cVar1 != '\0');
          uVar12 = ~uVar12;
          (&DAT_00714ffc)[DAT_00714f94] = 0x22;
          pcVar17 = pcVar16 + -uVar12;
          pcVar16 = (char *)(iVar14 + 0x714f9b + DAT_00714f94 * 4);
          for (uVar13 = uVar12 >> 2; uVar13 != 0; uVar13 = uVar13 - 1) {
            *(undefined4 *)pcVar16 = *(undefined4 *)pcVar17;
            pcVar17 = pcVar17 + 4;
            pcVar16 = pcVar16 + 4;
          }
          DAT_00714f94 = iVar14 + 4;
          for (uVar12 = uVar12 & 3; uVar12 != 0; uVar12 = uVar12 - 1) {
            *pcVar16 = *pcVar17;
            pcVar17 = pcVar17 + 1;
            pcVar16 = pcVar16 + 1;
          }
        }
        if ((*(int *)(iVar11 + 0x77c) == 2) && (iVar14 = Bridge_Able(DAT_007584ec), 0 < iVar14)) {
          uVar12 = 0xffffffff;
          pcVar17 = &DAT_0057e260;
          do {
            pcVar16 = pcVar17;
            if (uVar12 == 0) break;
            uVar12 = uVar12 - 1;
            pcVar16 = pcVar17 + 1;
            cVar1 = *pcVar17;
            pcVar17 = pcVar16;
          } while (cVar1 != '\0');
          uVar12 = ~uVar12;
          (&DAT_00714ffc)[DAT_00714f94] = 0x14;
          pcVar17 = pcVar16 + -uVar12;
          pcVar16 = (char *)((int)&DAT_00714f98 + DAT_00714f94 * 5);
          for (uVar13 = uVar12 >> 2; uVar13 != 0; uVar13 = uVar13 - 1) {
            *(undefined4 *)pcVar16 = *(undefined4 *)pcVar17;
            pcVar17 = pcVar17 + 4;
            pcVar16 = pcVar16 + 4;
          }
          DAT_00714f94 = DAT_00714f94 + 1;
          for (uVar12 = uVar12 & 3; uVar12 != 0; uVar12 = uVar12 - 1) {
            *pcVar16 = *pcVar17;
            pcVar17 = pcVar17 + 1;
            pcVar16 = pcVar16 + 1;
          }
        }
        pLVar7 = DAT_007584ec;
        if ((*(char *)DAT_007584ec == '\n') || (DAT_007584ec->alternate_battle_terrain_kind == 10))
        {
          uVar12 = 0xffffffff;
          pcVar17 = (char *)&DAT_0057e258;
          do {
            pcVar16 = pcVar17;
            if (uVar12 == 0) break;
            uVar12 = uVar12 - 1;
            pcVar16 = pcVar17 + 1;
            cVar1 = *pcVar17;
            pcVar17 = pcVar16;
          } while (cVar1 != '\0');
          uVar12 = ~uVar12;
          (&DAT_00714ffc)[DAT_00714f94] = 0x13;
          pcVar17 = pcVar16 + -uVar12;
          pcVar16 = (char *)((int)&DAT_00714f98 + DAT_00714f94 * 5);
          for (uVar13 = uVar12 >> 2; uVar13 != 0; uVar13 = uVar13 - 1) {
            *(undefined4 *)pcVar16 = *(undefined4 *)pcVar17;
            pcVar17 = pcVar17 + 4;
            pcVar16 = pcVar16 + 4;
          }
          DAT_00714f94 = DAT_00714f94 + 1;
          for (uVar12 = uVar12 & 3; uVar12 != 0; uVar12 = uVar12 - 1) {
            *pcVar16 = *pcVar17;
            pcVar17 = pcVar17 + 1;
            pcVar16 = pcVar16 + 1;
          }
        }
        if ((pLVar7->field_0x1a == -1) && (pLVar7->linked_record == (void *)0x0)) {
          if (DAT_007584dc->army_type_id == 1) {
            if ((*(int *)(_DAT_00748e30 + 0x6e0) == 2) &&
               (iVar14 = Irrigate_Able(pLVar7,DAT_005c0ec8,DAT_005c0ecc,
                                       CONCAT31((int3)((uint)DAT_00714f94 >> 8),
                                                *(int *)(_DAT_00748e30 + 0x72c) == 2)),
               (char)iVar14 != '\0')) {
              uVar12 = 0xffffffff;
              pcVar17 = (char *)&DAT_0057c65c;
              do {
                pcVar16 = pcVar17;
                if (uVar12 == 0) break;
                uVar12 = uVar12 - 1;
                pcVar16 = pcVar17 + 1;
                cVar1 = *pcVar17;
                pcVar17 = pcVar16;
              } while (cVar1 != '\0');
              uVar12 = ~uVar12;
              (&DAT_00714ffc)[DAT_00714f94] = 0xe;
              pcVar17 = pcVar16 + -uVar12;
              pcVar16 = (char *)((int)&DAT_00714f98 + DAT_00714f94 * 5);
              for (uVar13 = uVar12 >> 2; uVar13 != 0; uVar13 = uVar13 - 1) {
                *(undefined4 *)pcVar16 = *(undefined4 *)pcVar17;
                pcVar17 = pcVar17 + 4;
                pcVar16 = pcVar16 + 4;
              }
              DAT_00714f94 = DAT_00714f94 + 1;
              for (uVar12 = uVar12 & 3; uVar12 != 0; uVar12 = uVar12 - 1) {
                *pcVar16 = *pcVar17;
                pcVar17 = pcVar17 + 1;
                pcVar16 = pcVar16 + 1;
              }
            }
            if ((*(int *)(_DAT_00748e30 + 0x6dc) == 2) &&
               (iVar14 = Pasturage_Able(DAT_007584ec), (char)iVar14 != '\0')) {
              uVar12 = 0xffffffff;
              pcVar17 = (char *)&DAT_0057c654;
              do {
                pcVar16 = pcVar17;
                if (uVar12 == 0) break;
                uVar12 = uVar12 - 1;
                pcVar16 = pcVar17 + 1;
                cVar1 = *pcVar17;
                pcVar17 = pcVar16;
              } while (cVar1 != '\0');
              uVar12 = ~uVar12;
              (&DAT_00714ffc)[DAT_00714f94] = 0xf;
              pcVar17 = pcVar16 + -uVar12;
              pcVar16 = (char *)((int)&DAT_00714f98 + DAT_00714f94 * 5);
              for (uVar13 = uVar12 >> 2; uVar13 != 0; uVar13 = uVar13 - 1) {
                *(undefined4 *)pcVar16 = *(undefined4 *)pcVar17;
                pcVar17 = pcVar17 + 4;
                pcVar16 = pcVar16 + 4;
              }
              DAT_00714f94 = DAT_00714f94 + 1;
              for (uVar12 = uVar12 & 3; uVar12 != 0; uVar12 = uVar12 - 1) {
                *pcVar16 = *pcVar17;
                pcVar17 = pcVar17 + 1;
                pcVar16 = pcVar16 + 1;
              }
            }
            if ((*(int *)(_DAT_00748e30 + 0x6d8) == 2) &&
               (iVar14 = Fish_Able(DAT_007584ec), (char)iVar14 != '\0')) {
              uVar12 = 0xffffffff;
              pcVar17 = (char *)&DAT_0057e250;
              do {
                pcVar16 = pcVar17;
                if (uVar12 == 0) break;
                uVar12 = uVar12 - 1;
                pcVar16 = pcVar17 + 1;
                cVar1 = *pcVar17;
                pcVar17 = pcVar16;
              } while (cVar1 != '\0');
              uVar12 = ~uVar12;
              (&DAT_00714ffc)[DAT_00714f94] = 0x11;
              pcVar17 = pcVar16 + -uVar12;
              pcVar16 = (char *)((int)&DAT_00714f98 + DAT_00714f94 * 5);
              for (uVar13 = uVar12 >> 2; uVar13 != 0; uVar13 = uVar13 - 1) {
                *(undefined4 *)pcVar16 = *(undefined4 *)pcVar17;
                pcVar17 = pcVar17 + 4;
                pcVar16 = pcVar16 + 4;
              }
              DAT_00714f94 = DAT_00714f94 + 1;
              for (uVar12 = uVar12 & 3; uVar12 != 0; uVar12 = uVar12 - 1) {
                *pcVar16 = *pcVar17;
                pcVar17 = pcVar17 + 1;
                pcVar16 = pcVar16 + 1;
              }
            }
          }
          if ((*(int *)(_DAT_00748e30 + 0x6cc) == 2) &&
             (iVar14 = Mine_Able(DAT_007584ec), (char)iVar14 != '\0')) {
            uVar12 = 0xffffffff;
            pcVar17 = (char *)&DAT_0057e248;
            do {
              pcVar16 = pcVar17;
              if (uVar12 == 0) break;
              uVar12 = uVar12 - 1;
              pcVar16 = pcVar17 + 1;
              cVar1 = *pcVar17;
              pcVar17 = pcVar16;
            } while (cVar1 != '\0');
            uVar12 = ~uVar12;
            (&DAT_00714ffc)[DAT_00714f94] = 0x10;
            pcVar17 = pcVar16 + -uVar12;
            pcVar16 = (char *)((int)&DAT_00714f98 + DAT_00714f94 * 5);
            for (uVar13 = uVar12 >> 2; uVar13 != 0; uVar13 = uVar13 - 1) {
              *(undefined4 *)pcVar16 = *(undefined4 *)pcVar17;
              pcVar17 = pcVar17 + 4;
              pcVar16 = pcVar16 + 4;
            }
            DAT_00714f94 = DAT_00714f94 + 1;
            for (uVar12 = uVar12 & 3; uVar12 != 0; uVar12 = uVar12 - 1) {
              *pcVar16 = *pcVar17;
              pcVar17 = pcVar17 + 1;
              pcVar16 = pcVar16 + 1;
            }
          }
        }
        if ((*(int *)(_DAT_00748e30 + 0x718) != 2) ||
           (iVar14 = LongWall_Able(DAT_007584ec), (char)iVar14 != '\x01')) goto LAB_00494c05;
        uVar12 = 0xffffffff;
        pcVar17 = (char *)&DAT_00572af4;
        do {
          pcVar16 = pcVar17;
          if (uVar12 == 0) break;
          uVar12 = uVar12 - 1;
          pcVar16 = pcVar17 + 1;
          cVar1 = *pcVar17;
          pcVar17 = pcVar16;
        } while (cVar1 != '\0');
        uVar12 = ~uVar12;
        (&DAT_00714ffc)[DAT_00714f94] = 0x12;
        pcVar17 = pcVar16 + -uVar12;
        pcVar16 = (char *)((int)&DAT_00714f98 + DAT_00714f94 * 5);
        for (uVar13 = uVar12 >> 2; uVar13 != 0; uVar13 = uVar13 - 1) {
          *(undefined4 *)pcVar16 = *(undefined4 *)pcVar17;
          pcVar17 = pcVar17 + 4;
          pcVar16 = pcVar16 + 4;
        }
        for (uVar12 = uVar12 & 3; uVar12 != 0; uVar12 = uVar12 - 1) {
          *pcVar16 = *pcVar17;
          pcVar17 = pcVar17 + 1;
          pcVar16 = pcVar16 + 1;
        }
      }
      DAT_00714f94 = DAT_00714f94 + 1;
    }
LAB_00494c05:
    pLVar7 = DAT_007584ec;
    if (-1 < (char)DAT_007584ec->field_0x1a) {
      uVar12 = 0xffffffff;
      pcVar17 = &DAT_0057e240;
      do {
        pcVar16 = pcVar17;
        if (uVar12 == 0) break;
        uVar12 = uVar12 - 1;
        pcVar16 = pcVar17 + 1;
        cVar1 = *pcVar17;
        pcVar17 = pcVar16;
      } while (cVar1 != '\0');
      uVar12 = ~uVar12;
      (&DAT_00714ffc)[DAT_00714f94] = 4;
      pcVar17 = pcVar16 + -uVar12;
      pcVar16 = (char *)((int)&DAT_00714f98 + DAT_00714f94 * 5);
      for (uVar13 = uVar12 >> 2; uVar13 != 0; uVar13 = uVar13 - 1) {
        *(undefined4 *)pcVar16 = *(undefined4 *)pcVar17;
        pcVar17 = pcVar17 + 4;
        pcVar16 = pcVar16 + 4;
      }
      DAT_00714f94 = DAT_00714f94 + 1;
      for (uVar12 = uVar12 & 3; uVar12 != 0; uVar12 = uVar12 - 1) {
        *pcVar16 = *pcVar17;
        pcVar17 = pcVar17 + 1;
        pcVar16 = pcVar16 + 1;
      }
    }
    pAVar3 = DAT_007584dc;
    if ((((DAT_007584dc->army_type_id == 0x2a) && (DAT_007584dc->cargo_or_subunit_count == 0)) &&
        (pLVar7->city_resource_or_feature_id == 0x26)) &&
       (((pLVar7->linked_record == (void *)0x0 && (pLVar7->field_0x1a == -1)) &&
        ('\n' < *(char *)pLVar7)))) {
      uVar12 = 0xffffffff;
      pcVar17 = &DAT_0057e238;
      do {
        pcVar16 = pcVar17;
        if (uVar12 == 0) break;
        uVar12 = uVar12 - 1;
        pcVar16 = pcVar17 + 1;
        cVar1 = *pcVar17;
        pcVar17 = pcVar16;
      } while (cVar1 != '\0');
      uVar12 = ~uVar12;
      (&DAT_00714ffc)[DAT_00714f94] = 99;
      pcVar17 = pcVar16 + -uVar12;
      pcVar16 = (char *)((int)&DAT_00714f98 + DAT_00714f94 * 5);
      for (uVar13 = uVar12 >> 2; uVar13 != 0; uVar13 = uVar13 - 1) {
        *(undefined4 *)pcVar16 = *(undefined4 *)pcVar17;
        pcVar17 = pcVar17 + 4;
        pcVar16 = pcVar16 + 4;
      }
      DAT_00714f94 = DAT_00714f94 + 1;
      for (uVar12 = uVar12 & 3; uVar12 != 0; uVar12 = uVar12 - 1) {
        *pcVar16 = *pcVar17;
        pcVar17 = pcVar17 + 1;
        pcVar16 = pcVar16 + 1;
      }
    }
    iVar11 = DAT_00714f94;
    if ((char)pAVar3->map_presence_or_cargo_state < '\x03') {
      if (((DAT_007584dc->transport_parent == (ArmyUnit_0x164_plus *)0x0) &&
          (0 < *(int *)(DAT_007584e4 + 0x13c))) &&
         ('\x01' < (char)DAT_007584ec->army_count_or_occupant_count)) {
        iVar14 = 0;
        ppAVar9 = DAT_007584ec->army_or_city_ptrs_a;
        do {
          pAVar3 = *ppAVar9;
          if ((((pAVar3 != (ArmyUnit_0x164_plus *)0x0) && (pAVar3 != DAT_007584dc)) &&
              (pAVar3->transport_parent == (ArmyUnit_0x164_plus *)0x0)) &&
             (*(int *)(DAT_007584e4 + 0x13c) ==
              *(int *)&g_army_type_table[pAVar3->army_type_id].field_0x13c)) {
            bVar2 = pAVar3->mission_action_id;
            uVar12 = 0xffffffff;
            pcVar17 = &DAT_0057e230;
            goto code_r0x00494d58;
          }
          iVar14 = iVar14 + 1;
          ppAVar9 = ppAVar9 + 1;
        } while (iVar14 < 10);
      }
      goto LAB_00494dc2;
    }
    goto LAB_00494eae;
  }
  if (DAT_007584dc->army_type_id == 0x37) {
    uVar12 = 0xffffffff;
    DAT_00714ffc = 0x5f;
    pcVar17 = &DAT_0057e2c0;
    do {
      pcVar16 = pcVar17;
      if (uVar12 == 0) break;
      uVar12 = uVar12 - 1;
      pcVar16 = pcVar17 + 1;
      cVar1 = *pcVar17;
      pcVar17 = pcVar16;
    } while (cVar1 != '\0');
    uVar12 = ~uVar12;
    pcVar17 = pcVar16 + -uVar12;
    pcVar16 = (char *)&DAT_00714f98;
    for (uVar13 = uVar12 >> 2; uVar13 != 0; uVar13 = uVar13 - 1) {
      *(undefined4 *)pcVar16 = *(undefined4 *)pcVar17;
      pcVar17 = pcVar17 + 4;
      pcVar16 = pcVar16 + 4;
    }
    iVar14 = 1;
    for (uVar12 = uVar12 & 3; uVar12 != 0; uVar12 = uVar12 - 1) {
      *pcVar16 = *pcVar17;
      pcVar17 = pcVar17 + 1;
      pcVar16 = pcVar16 + 1;
    }
  }
  if ((DAT_0074c858 == 0) && (DAT_007584dc->army_type_id != 0x3a)) goto LAB_004950fa;
  uVar12 = 0xffffffff;
  pcVar17 = &DAT_0057e2b8;
  do {
    pcVar16 = pcVar17;
    if (uVar12 == 0) break;
    uVar12 = uVar12 - 1;
    pcVar16 = pcVar17 + 1;
    cVar1 = *pcVar17;
    pcVar17 = pcVar16;
  } while (cVar1 != '\0');
  uVar12 = ~uVar12;
  (&DAT_00714ffc)[iVar14] = 0x48;
  pcVar17 = pcVar16 + -uVar12;
  pcVar16 = (char *)((int)&DAT_00714f98 + iVar14 * 5);
  for (uVar13 = uVar12 >> 2; uVar13 != 0; uVar13 = uVar13 - 1) {
    *(undefined4 *)pcVar16 = *(undefined4 *)pcVar17;
    pcVar17 = pcVar17 + 4;
    pcVar16 = pcVar16 + 4;
  }
  for (uVar12 = uVar12 & 3; uVar12 != 0; uVar12 = uVar12 - 1) {
    *pcVar16 = *pcVar17;
    pcVar17 = pcVar17 + 1;
    pcVar16 = pcVar16 + 1;
  }
  goto LAB_004950f9;
  while( true ) {
    uVar12 = uVar12 - 1;
    pcVar16 = pcVar17 + 1;
    cVar1 = *pcVar17;
    pcVar17 = pcVar16;
    if (cVar1 == '\0') break;
code_r0x0049424c:
    pcVar16 = pcVar17;
    if (uVar12 == 0) break;
  }
  uVar12 = ~uVar12;
  pcVar17 = pcVar16 + -uVar12;
  pcVar16 = (char *)&DAT_00714f98;
  for (uVar13 = uVar12 >> 2; uVar13 != 0; uVar13 = uVar13 - 1) {
    *(undefined4 *)pcVar16 = *(undefined4 *)pcVar17;
    pcVar17 = pcVar17 + 4;
    pcVar16 = pcVar16 + 4;
  }
  iVar14 = 1;
  for (uVar12 = uVar12 & 3; uVar12 != 0; uVar12 = uVar12 - 1) {
    *pcVar16 = *pcVar17;
    pcVar17 = pcVar17 + 1;
    pcVar16 = pcVar16 + 1;
  }
  goto LAB_004950fa;
  while( true ) {
    uVar12 = uVar12 - 1;
    pcVar16 = pcVar17 + 1;
    cVar1 = *pcVar17;
    pcVar17 = pcVar16;
    if (cVar1 == '\0') break;
code_r0x00494d58:
    pcVar16 = pcVar17;
    if (uVar12 == 0) break;
  }
  uVar12 = ~uVar12;
  (&DAT_00714ffc)[DAT_00714f94] = 0x54;
  pcVar17 = pcVar16 + -uVar12;
  pcVar16 = (char *)((int)&DAT_00714f98 + DAT_00714f94 * 5);
  for (uVar13 = uVar12 >> 2; uVar13 != 0; uVar13 = uVar13 - 1) {
    *(undefined4 *)pcVar16 = *(undefined4 *)pcVar17;
    pcVar17 = pcVar17 + 4;
    pcVar16 = pcVar16 + 4;
  }
  iVar11 = DAT_00714f94 + 1;
  for (uVar12 = uVar12 & 3; uVar12 != 0; uVar12 = uVar12 - 1) {
    *pcVar16 = *pcVar17;
    pcVar17 = pcVar17 + 1;
    pcVar16 = pcVar16 + 1;
  }
  if (bVar2 == 0) {
    uVar12 = 0xffffffff;
    pcVar17 = &DAT_0057e228;
    do {
      pcVar16 = pcVar17;
      if (uVar12 == 0) break;
      uVar12 = uVar12 - 1;
      pcVar16 = pcVar17 + 1;
      cVar1 = *pcVar17;
      pcVar17 = pcVar16;
    } while (cVar1 != '\0');
    uVar12 = ~uVar12;
    (&DAT_00714ffc)[iVar11] = 0x56;
    pcVar17 = pcVar16 + -uVar12;
    pcVar16 = (char *)(DAT_00714f94 + 0x714f99 + iVar11 * 4);
    for (uVar13 = uVar12 >> 2; uVar13 != 0; uVar13 = uVar13 - 1) {
      *(undefined4 *)pcVar16 = *(undefined4 *)pcVar17;
      pcVar17 = pcVar17 + 4;
      pcVar16 = pcVar16 + 4;
    }
    for (uVar12 = uVar12 & 3; iVar11 = DAT_00714f94 + 2, uVar12 != 0; uVar12 = uVar12 - 1) {
      *pcVar16 = *pcVar17;
      pcVar17 = pcVar17 + 1;
      pcVar16 = pcVar16 + 1;
    }
  }
LAB_00494dc2:
  if ((DAT_007584dc->transport_parent != (ArmyUnit_0x164_plus *)0x0) ||
     (DAT_007584dc->cargo_or_subunit_count != 0)) {
    if ((*(int *)(DAT_007584e4 + 0xc) == 1) &&
       ((DAT_007584dc->cargo_or_subunit_count != 0 && (0 < *(int *)(DAT_007584e4 + 300))))) {
      bVar5 = true;
    }
    else {
      bVar5 = false;
    }
    if ((((*(int *)(DAT_007584e4 + 0xc) == 2) && (DAT_007584dc->cargo_or_subunit_count != 0)) &&
        (0 < *(int *)(DAT_007584e4 + 300))) && (DAT_007584ec->linked_record == (void *)0x0)) {
      bVar6 = true;
    }
    else {
      bVar6 = false;
    }
    if ((!bVar5) && (!bVar6)) {
      uVar12 = 0xffffffff;
      pcVar17 = &DAT_0057e220;
      do {
        pcVar16 = pcVar17;
        if (uVar12 == 0) break;
        uVar12 = uVar12 - 1;
        pcVar16 = pcVar17 + 1;
        cVar1 = *pcVar17;
        pcVar17 = pcVar16;
      } while (cVar1 != '\0');
      uVar12 = ~uVar12;
      (&DAT_00714ffc)[iVar11] = 0x55;
      (&DAT_00715000)[iVar11] = 0x57;
      pcVar17 = pcVar16 + -uVar12;
      pcVar16 = (char *)((int)&DAT_00714f98 + iVar11 * 5);
      for (uVar13 = uVar12 >> 2; uVar13 != 0; uVar13 = uVar13 - 1) {
        *(undefined4 *)pcVar16 = *(undefined4 *)pcVar17;
        pcVar17 = pcVar17 + 4;
        pcVar16 = pcVar16 + 4;
      }
      for (uVar12 = uVar12 & 3; uVar12 != 0; uVar12 = uVar12 - 1) {
        *pcVar16 = *pcVar17;
        pcVar17 = pcVar17 + 1;
        pcVar16 = pcVar16 + 1;
      }
      uVar12 = 0xffffffff;
      pcVar17 = &DAT_0057e218;
      do {
        pcVar16 = pcVar17;
        if (uVar12 == 0) break;
        uVar12 = uVar12 - 1;
        pcVar16 = pcVar17 + 1;
        cVar1 = *pcVar17;
        pcVar17 = pcVar16;
      } while (cVar1 != '\0');
      uVar12 = ~uVar12;
      pcVar17 = (char *)((int)&DAT_00714f98 + iVar11 * 5 + 1);
      pcVar16 = pcVar16 + -uVar12;
      for (uVar13 = uVar12 >> 2; pcVar17 = pcVar17 + 4, uVar13 != 0; uVar13 = uVar13 - 1) {
        *(undefined4 *)pcVar17 = *(undefined4 *)pcVar16;
        pcVar16 = pcVar16 + 4;
      }
      iVar11 = iVar11 + 2;
      for (uVar12 = uVar12 & 3; uVar12 != 0; uVar12 = uVar12 - 1) {
        *pcVar17 = *pcVar16;
        pcVar16 = pcVar16 + 1;
        pcVar17 = pcVar17 + 1;
      }
    }
  }
LAB_00494eae:
  pAVar3 = DAT_007584dc;
  iVar14 = (int)(char)DAT_007584ec->army_count_or_occupant_count;
  if (((*(int *)(DAT_007584e4 + 500) == 1) &&
      (DAT_007584dc->transport_parent == (ArmyUnit_0x164_plus *)0x0)) &&
     ((DAT_007584dc->cargo_or_subunit_count == 0 &&
      ((1 < iVar14 && ((char)DAT_007584dc->strength_or_health < 'd')))))) {
    bVar5 = false;
    iVar8 = 0;
    ppAVar9 = DAT_007584ec->army_or_city_ptrs_a;
    local_4 = iVar14;
    do {
      if ((iVar14 < 1) || (bVar5)) break;
      pAVar4 = *ppAVar9;
      if (pAVar4 != (ArmyUnit_0x164_plus *)0x0) {
        if (((((pAVar4 != DAT_007584dc) && (pAVar4->army_type_id == DAT_007584dc->army_type_id)) &&
             (pAVar4->mission_state == 0)) &&
            (pAVar4->transport_parent == (ArmyUnit_0x164_plus *)0x0)) &&
           ((((bVar2 = pAVar4->mission_action_id, bVar2 == 0 || (bVar2 == 3)) || (bVar2 == 2)) &&
            ((int)(char)pAVar4->strength_or_health + (int)(char)DAT_007584dc->strength_or_health <
             0x65)))) {
          bVar5 = true;
        }
        iVar14 = local_4 + -1;
        local_4 = iVar14;
      }
      iVar8 = iVar8 + 1;
      ppAVar9 = ppAVar9 + 1;
    } while (iVar8 < 10);
    if (bVar5) {
      uVar12 = 0xffffffff;
      pcVar17 = &DAT_0057e210;
      do {
        pcVar16 = pcVar17;
        if (uVar12 == 0) break;
        uVar12 = uVar12 - 1;
        pcVar16 = pcVar17 + 1;
        cVar1 = *pcVar17;
        pcVar17 = pcVar16;
      } while (cVar1 != '\0');
      uVar12 = ~uVar12;
      (&DAT_00714ffc)[iVar11] = 0xc;
      pcVar17 = pcVar16 + -uVar12;
      pcVar16 = (char *)((int)&DAT_00714f98 + iVar11 * 5);
      for (uVar13 = uVar12 >> 2; uVar13 != 0; uVar13 = uVar13 - 1) {
        *(undefined4 *)pcVar16 = *(undefined4 *)pcVar17;
        pcVar17 = pcVar17 + 4;
        pcVar16 = pcVar16 + 4;
      }
      iVar11 = iVar11 + 1;
      for (uVar12 = uVar12 & 3; uVar12 != 0; uVar12 = uVar12 - 1) {
        *pcVar16 = *pcVar17;
        pcVar17 = pcVar17 + 1;
        pcVar16 = pcVar16 + 1;
      }
    }
  }
  pLVar7 = DAT_007584ec;
  if ((DAT_007584ec->linked_record != (City_0x1b8_plus *)0x0) &&
     (DAT_007584ec->linked_record != pAVar3->stationed_city)) {
    uVar12 = 0xffffffff;
    pcVar17 = &DAT_0057e208;
    do {
      pcVar16 = pcVar17;
      if (uVar12 == 0) break;
      uVar12 = uVar12 - 1;
      pcVar16 = pcVar17 + 1;
      cVar1 = *pcVar17;
      pcVar17 = pcVar16;
    } while (cVar1 != '\0');
    uVar12 = ~uVar12;
    (&DAT_00714ffc)[iVar11] = 5;
    pcVar17 = pcVar16 + -uVar12;
    pcVar16 = (char *)((int)&DAT_00714f98 + iVar11 * 5);
    for (uVar13 = uVar12 >> 2; uVar13 != 0; uVar13 = uVar13 - 1) {
      *(undefined4 *)pcVar16 = *(undefined4 *)pcVar17;
      pcVar17 = pcVar17 + 4;
      pcVar16 = pcVar16 + 4;
    }
    iVar11 = iVar11 + 1;
    for (uVar12 = uVar12 & 3; uVar12 != 0; uVar12 = uVar12 - 1) {
      *pcVar16 = *pcVar17;
      pcVar17 = pcVar17 + 1;
      pcVar16 = pcVar16 + 1;
    }
  }
  uVar12 = 0xffffffff;
  pcVar17 = &DAT_0057e200;
  do {
    pcVar16 = pcVar17;
    if (uVar12 == 0) break;
    uVar12 = uVar12 - 1;
    pcVar16 = pcVar17 + 1;
    cVar1 = *pcVar17;
    pcVar17 = pcVar16;
  } while (cVar1 != '\0');
  uVar12 = ~uVar12;
  (&DAT_00714ffc)[iVar11] = 6;
  pcVar17 = pcVar16 + -uVar12;
  pcVar16 = (char *)((int)&DAT_00714f98 + iVar11 * 5);
  for (uVar13 = uVar12 >> 2; uVar13 != 0; uVar13 = uVar13 - 1) {
    *(undefined4 *)pcVar16 = *(undefined4 *)pcVar17;
    pcVar17 = pcVar17 + 4;
    pcVar16 = pcVar16 + 4;
  }
  iVar14 = iVar11 + 1;
  for (uVar12 = uVar12 & 3; uVar12 != 0; uVar12 = uVar12 - 1) {
    *pcVar16 = *pcVar17;
    pcVar17 = pcVar17 + 1;
    pcVar16 = pcVar16 + 1;
  }
  if (pLVar7->linked_record == (void *)0x0) goto LAB_004950fa;
  uVar12 = 0xffffffff;
  pcVar17 = &DAT_0057e1f8;
  do {
    pcVar16 = pcVar17;
    if (uVar12 == 0) break;
    uVar12 = uVar12 - 1;
    pcVar16 = pcVar17 + 1;
    cVar1 = *pcVar17;
    pcVar17 = pcVar16;
  } while (cVar1 != '\0');
  uVar12 = ~uVar12;
  (&DAT_00714ffc)[iVar14] = 8;
  pcVar17 = pcVar16 + -uVar12;
  pcVar16 = (char *)(iVar11 + 0x714f99 + iVar14 * 4);
  for (uVar13 = uVar12 >> 2; uVar13 != 0; uVar13 = uVar13 - 1) {
    *(undefined4 *)pcVar16 = *(undefined4 *)pcVar17;
    pcVar17 = pcVar17 + 4;
    pcVar16 = pcVar16 + 4;
  }
  iVar14 = iVar11 + 2;
  for (uVar12 = uVar12 & 3; uVar12 != 0; uVar12 = uVar12 - 1) {
    *pcVar16 = *pcVar17;
    pcVar17 = pcVar17 + 1;
    pcVar16 = pcVar16 + 1;
  }
  if ((((*(int *)(DAT_007584e4 + 0xc) != 0) || (*(int *)(DAT_007584e4 + 0xf8) < 2)) ||
      (*(int *)(DAT_007584e4 + 0x110) < 1)) ||
     ((DAT_007584dc->army_type_id == 0x41 || (DAT_007584dc->army_type_id == 0x3f))))
  goto LAB_004950fa;
  uVar12 = 0xffffffff;
  pcVar17 = &DAT_0057e1f0;
  do {
    pcVar16 = pcVar17;
    if (uVar12 == 0) break;
    uVar12 = uVar12 - 1;
    pcVar16 = pcVar17 + 1;
    cVar1 = *pcVar17;
    pcVar17 = pcVar16;
  } while (cVar1 != '\0');
  uVar12 = ~uVar12;
  (&DAT_00714ffc)[iVar14] = 10;
  pcVar17 = pcVar16 + -uVar12;
  pcVar16 = (char *)(iVar11 + 0x714f9a + iVar14 * 4);
  for (uVar13 = uVar12 >> 2; uVar13 != 0; uVar13 = uVar13 - 1) {
    *(undefined4 *)pcVar16 = *(undefined4 *)pcVar17;
    pcVar17 = pcVar17 + 4;
    pcVar16 = pcVar16 + 4;
  }
  for (uVar12 = uVar12 & 3; uVar12 != 0; uVar12 = uVar12 - 1) {
    *pcVar16 = *pcVar17;
    pcVar17 = pcVar17 + 1;
    pcVar16 = pcVar16 + 1;
  }
LAB_004950f9:
  iVar14 = iVar14 + 1;
LAB_004950fa:
  uVar12 = 0xffffffff;
  pcVar17 = &DAT_00512518;
  do {
    pcVar16 = pcVar17;
    if (uVar12 == 0) break;
    uVar12 = uVar12 - 1;
    pcVar16 = pcVar17 + 1;
    cVar1 = *pcVar17;
    pcVar17 = pcVar16;
  } while (cVar1 != '\0');
  uVar12 = ~uVar12;
  (&DAT_00714ffc)[iVar14] = 9;
  pcVar17 = pcVar16 + -uVar12;
  pcVar16 = (char *)((int)&DAT_00714f98 + iVar14 * 5);
  for (uVar13 = uVar12 >> 2; uVar13 != 0; uVar13 = uVar13 - 1) {
    *(undefined4 *)pcVar16 = *(undefined4 *)pcVar17;
    pcVar17 = pcVar17 + 4;
    pcVar16 = pcVar16 + 4;
  }
  DAT_00714f94 = iVar14 + 1;
  for (uVar12 = uVar12 & 3; uVar12 != 0; uVar12 = uVar12 - 1) {
    *pcVar16 = *pcVar17;
    pcVar17 = pcVar17 + 1;
    pcVar16 = pcVar16 + 1;
  }
  if (((1 < (byte)(&DAT_00735ed0)[(char)DAT_007584dc->owner_country_id * 0xe68]) &&
      ((*(int *)(DAT_007584e4 + 0x1dc) == 1 ||
       ((DAT_007584dc->cargo_or_subunit_count != 0 && (*(int *)(DAT_007584e4 + 0x1dc) == 2)))))) &&
     ((char)DAT_007584dc->map_presence_or_cargo_state < '\x02')) {
    uVar12 = 0xffffffff;
    pcVar17 = &DAT_00570ce4;
    do {
      pcVar16 = pcVar17;
      if (uVar12 == 0) break;
      uVar12 = uVar12 - 1;
      pcVar16 = pcVar17 + 1;
      cVar1 = *pcVar17;
      pcVar17 = pcVar16;
    } while (cVar1 != '\0');
    uVar12 = ~uVar12;
    (&DAT_00714ffc)[DAT_00714f94] = 0xb;
    pcVar17 = pcVar16 + -uVar12;
    pcVar16 = (char *)(iVar14 + 0x714f99 + DAT_00714f94 * 4);
    for (uVar13 = uVar12 >> 2; uVar13 != 0; uVar13 = uVar13 - 1) {
      *(undefined4 *)pcVar16 = *(undefined4 *)pcVar17;
      pcVar17 = pcVar17 + 4;
      pcVar16 = pcVar16 + 4;
    }
    DAT_00714f94 = iVar14 + 2;
    for (uVar12 = uVar12 & 3; uVar12 != 0; uVar12 = uVar12 - 1) {
      *pcVar16 = *pcVar17;
      pcVar17 = pcVar17 + 1;
      pcVar16 = pcVar16 + 1;
    }
  }
  DAT_005c33d8 = (DAT_00714f94 * 3 + 3) * 8;
  return;
}
