/*
 * Generated by Ghidra headless decompiler from China2EX_fontfix8.exe.
 * Address request: 0x00495c90
 * This is reconstructed pseudocode, not original source.
 */


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void Order_Forset(void)

{
  byte *pbVar1;
  undefined4 uVar2;
  int iVar3;
  int iVar4;
  int iVar5;
  int *piVar6;
  int *piVar7;
  uint uVar8;
  int iVar9;
  undefined4 *puVar10;
  int local_60;
  int local_5c;
  int local_58;
  uint local_54;
  int local_50;
  undefined1 local_4c [36];
  int local_28 [10];
  
  Trace_Function(s_Order_Forset_0057e39c);
  if ((DAT_00706838 == '\x01') &&
     (g_active_country->available_special_project_flags[DAT_0074c034 + 0x1a] == 2)) {
    FUN_004b0130(_DAT_00748ff0,0,0xffffffff,0x40,0xffffffff,0,0xffffffff,0xffffffff);
    return;
  }
  if (0 < *(int *)(_DAT_0074a0b8 + 0xf8)) {
    local_58 = 0;
    iVar3 = (DAT_00706840 & 1) << 5;
    iVar5 = iVar3;
    do {
      local_5c = *(int *)((int)&DAT_00589374 + iVar5) + DAT_0070683c;
      iVar9 = *(int *)((int)&DAT_005893b4 + iVar5) + DAT_00706840;
      if (((-1 < iVar9) && (iVar9 < g_map_height_tiles)) &&
         (((-1 < local_5c && (local_5c < g_map_width_tiles)) ||
          (g_current_map_scenario_info.horizontal_wrap_enabled == 1)))) {
        if (local_5c < 0) {
          local_5c = local_5c + g_map_width_tiles;
        }
        if (g_map_width_tiles <= local_5c) {
          local_5c = local_5c - g_map_width_tiles;
        }
        switch(g_map_size_mode) {
        case 0:
          iVar3 = local_5c + iVar9 * 0x138;
          break;
        case 1:
          iVar3 = local_5c + iVar9 * 0x9c;
          break;
        case 2:
          iVar3 = local_5c + iVar9 * 0x4e;
          break;
        case 3:
          iVar3 = iVar9 * 0x27 + local_5c;
          break;
        default:
          goto switchD_00495d9d_default;
        }
        iVar3 = iVar3 * 0x100 + _g_land_tiles;
switchD_00495d9d_default:
        if (('\0' < *(char *)(iVar3 + 0x50)) &&
           ((*(int *)(_DAT_0074a0b8 + 0xc) != 0 ||
            ((*(short *)(iVar3 + 0x10) == *(short *)(DAT_0075597c + 0x10) &&
             (0 < *(short *)(DAT_0075597c + 0x10))))))) {
          if ((*(char *)(iVar3 + 0x27) < '\0') ||
             ((iVar4 = (int)*(char *)(iVar3 + 0x27), iVar4 == _DAT_00748e34 ||
              (g_active_country->diplomacy_state_by_country[iVar4] < 6)))) {
            local_60 = (int)*(char *)(iVar3 + 0x50);
            iVar4 = 0;
            puVar10 = (undefined4 *)(iVar3 + 0x28);
            do {
              if (local_60 < 1) break;
              pbVar1 = (byte *)*puVar10;
              if (pbVar1 != (byte *)0x0) {
                if ((((char)pbVar1[1] != _DAT_00748e34) &&
                    (5 < g_active_country->diplomacy_state_by_country[(char)pbVar1[1]])) &&
                   (*(int *)(_DAT_0074a0b8 + 0x130 + g_army_type_table[*pbVar1].unit_class * 4) == 1
                   )) {
                  iVar4 = (int)(char)pbVar1[1];
                  goto LAB_00495e9d;
                }
                local_60 = local_60 + -1;
              }
              iVar4 = iVar4 + 1;
              puVar10 = puVar10 + 1;
            } while (iVar4 < 10);
          }
          else {
LAB_00495e9d:
            if (-1 < iVar4) {
              if (((_DAT_00748e34 == g_human_country_index) && (g_auto_turn_or_ai_control_flag == 0)
                  ) || (('\0' < *(char *)(_DAT_00748ff0 + 0x132) &&
                        ((*(int *)(_DAT_00748ff0 + 0x154) == 0 ||
                         (*(int *)(*(int *)(_DAT_00748ff0 + 0x154) + 0xcc) == 0)))))) {
                FUN_004b0130(_DAT_00748ff0,0x29,0x22,0xffffffff,
                             *(undefined4 *)(&DAT_00588f24 + local_58 * 4),0,local_5c,iVar9);
                return;
              }
              if ((DAT_00706838 == '\x01') && (DAT_0074c858 != 0)) {
                uVar8 = *(byte *)(DAT_0074c858 + 0x20) + 1;
                if (0x2d < uVar8) {
                  uVar8 = 0x2d;
                }
                if (*(byte *)(DAT_0074c858 + 0x15e) < uVar8) {
                  FUN_004b0130(_DAT_00748ff0,3,0x7c,0x41,0xffffffff,0,0xffffffff,0xffffffff);
                  return;
                }
              }
              FUN_004b0130(_DAT_00748ff0,0,0x7c,0x41,0xffffffff,0,0xffffffff,0xffffffff);
              return;
            }
          }
        }
      }
      local_58 = local_58 + 1;
      iVar5 = iVar5 + 4;
    } while (local_58 < 8);
  }
  if ((DAT_00706838 == '\x01') && (DAT_0074c858 != 0)) {
    iVar5 = *(int *)(_DAT_00748ff0 + 0x154);
    if (((DAT_0074c858 != iVar5) && (iVar5 != 0)) &&
       (((((*(int *)(iVar5 + 0xcc) == 0 || (2 < *(int *)(iVar5 + 0x28))) &&
          (0 < *(int *)(DAT_0074c858 + 0xcc))) &&
         ((0 < *(short *)(DAT_0074c858 + 0xd6) && (*(int *)(DAT_0074c858 + 0x28) < 3)))) &&
        (*(char *)(DAT_0074c858 + 0x20) != '\0')))) {
      FUN_004b0130(_DAT_00748ff0,5,100,0xffffffff,0xffffffff,0,0xffffffff,0xffffffff);
      return;
    }
    uVar8 = 1;
    local_54 = 1;
    if (*(short *)(DAT_0074c858 + 0x17e) != 0) {
      uVar8 = 2;
      local_54 = 2;
    }
    if ((int)uVar8 < (int)*(char *)(DAT_0075597c + 0x50)) {
      iVar3 = 0;
      piVar6 = local_28;
      piVar7 = (int *)(DAT_0075597c + 0x28);
      iVar5 = 10;
      do {
        iVar9 = *piVar7;
        if ((iVar9 == 0) || (*(char *)(iVar9 + 0x128) != '\x02')) {
          *piVar6 = 0;
        }
        else {
          iVar3 = iVar3 + 1;
          *piVar6 = (int)*(char *)(iVar9 + 0x12f) + (uint)*(ushort *)(iVar9 + 0x136) * 4;
        }
        piVar7 = piVar7 + 1;
        piVar6 = piVar6 + 1;
        iVar5 = iVar5 + -1;
      } while (iVar5 != 0);
      if ((int)uVar8 < iVar3) {
        iVar5 = 0;
        do {
          if (local_28[iVar5] < 1) {
            *(undefined4 *)(local_4c + iVar5 * 4 + -4) = 0xffffffff;
          }
          else {
            *(int *)(local_4c + iVar5 * 4 + -4) = iVar5;
          }
          iVar5 = iVar5 + 1;
        } while (iVar5 < 10);
        iVar5 = 0;
        do {
          iVar3 = iVar5 + 1;
          if (iVar3 < 10) {
            puVar10 = (undefined4 *)(local_4c + iVar5 * 4 + -4);
            piVar6 = local_28 + iVar5;
            iVar5 = (4 - (int)&local_50) + (int)puVar10;
            do {
              iVar9 = *(int *)((int)local_28 + iVar5);
              if (*piVar6 < iVar9) {
                uVar2 = *puVar10;
                *puVar10 = *(undefined4 *)(local_4c + iVar5 + -4);
                *(undefined4 *)(local_4c + iVar5 + -4) = uVar2;
                iVar4 = *piVar6;
                *piVar6 = iVar9;
                *(int *)((int)local_28 + iVar5) = iVar4;
                uVar8 = local_54;
              }
              iVar5 = iVar5 + 4;
            } while (iVar5 < 0x28);
          }
          iVar5 = iVar3;
        } while (iVar3 < 9);
        if (uVar8 < 10) {
          piVar6 = (int *)(local_4c + uVar8 * 4 + -4);
          iVar5 = 10 - uVar8;
          do {
            if (-1 < *piVar6) {
              FUN_004b0130(*(undefined4 *)(DAT_0075597c + 0x28 + *piVar6 * 4),0,0xffffffff,0x42,
                           0xffffffff,0,0xffffffff,0xffffffff);
            }
            piVar6 = piVar6 + 1;
            iVar5 = iVar5 + -1;
          } while (iVar5 != 0);
        }
      }
    }
  }
  DAT_0070684c = 1;
  return;
}

