/*
 * Generated by Ghidra headless decompiler from China2EX_fontfix8.exe.
 * Address request: 0x0041b960
 * This is reconstructed pseudocode, not original source.
 */


/* WARNING: Unknown calling convention -- yet parameter storage is locked */

byte Resource_Able(LandTile_0x100 *tile,int resource_id)

{
  byte bVar1;

  Trace_Function(s_Resource_Able_00514efc);
  bVar1 = 0;
  if (((0 < g_city_resource_defs[resource_id].terrain_compatibility_by_kind
            [(char)tile->terrain_kind]) ||
      (((g_city_resource_defs[resource_id].placement_or_resource_class == 2 &&
        ((char)tile->terrain_kind < '\v')) || (resource_id == 0x26)))) &&
     ((bVar1 = 0, g_city_resource_defs[resource_id].requires_battle_feature_or_clearable == 0 ||
      (0 < g_battle_feature_values[(char)tile->battle_resource_or_feature_id])))) {
    bVar1 = 1;
  }
  return bVar1;
}
