/*
 * Generated by Ghidra headless decompiler from China2EX_fontfix8.exe.
 * Address request: 0x004d2cc0
 * This is reconstructed pseudocode, not original source.
 */


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */
/* WARNING: Unknown calling convention -- yet parameter storage is locked */

int TestRoad(ArmyUnit_0x164_plus *army)

{
  bool bVar1;
  char cVar2;
  int iVar3;
  int iVar4;
  ArmyUnit_0x164_plus *pAVar5;
  undefined4 uVar6;
  int *piVar7;
  char *pcVar8;
  int iVar9;
  short *psVar10;
  undefined4 *puVar11;
  int iVar12;
  byte bVar13;
  int iVar14;
  int iVar15;
  int *piVar16;
  ArmyUnit_0x164_plus *pAVar17;
  short *psVar18;
  byte *pbVar19;
  int local_54;
  int local_4c;
  int local_1c;
  void *local_c;
  undefined1 *puStack_8;
  undefined4 local_4;

  local_4 = 0xffffffff;
  puStack_8 = &LAB_0050e988;
  local_c = ExceptionList;
  ExceptionList = &local_c;
  Trace_Function(s_TestRoad_005cba8c);
  g_testroad_army = army;
  if (((0x31 < DAT_00706858) && (DAT_00755960 != 0)) && (army->mission_action_id != 0x20)) {
    army->active_anim_step_count = 0;
    ExceptionList = local_c;
    return -4;
  }
  iVar3 = Get_Game_Tick();
  g_testroad_start_x = (int)g_testroad_army->tile_x;
  g_testroad_start_y = (int)g_testroad_army->tile_y;
  g_testroad_target_x = (int)g_testroad_army->target_tile_x_or_anim_x;
  g_testroad_target_y = (int)g_testroad_army->target_tile_y_or_anim_y;
  g_testroad_target_reached_or_blocked._0_1_ = 0;
  if ((g_testroad_start_x == g_testroad_target_x) && (g_testroad_start_y == g_testroad_target_y)) {
    g_testroad_target_reached_or_blocked._0_1_ = 1;
    g_testroad_army->active_anim_step_count = 0;
    ExceptionList = local_c;
    return 0;
  }
  pAVar17 = army;
  switch(g_map_size_mode) {
  case 0:
    army = (ArmyUnit_0x164_plus *)
           ((g_testroad_start_x + g_testroad_start_y * 0x138) * 0x100 + _g_land_tiles);
    pAVar17 = (ArmyUnit_0x164_plus *)
              ((g_testroad_target_x + g_testroad_target_y * 0x138) * 0x100 + _g_land_tiles);
    break;
  case 1:
    army = (ArmyUnit_0x164_plus *)
           ((g_testroad_start_x + g_testroad_start_y * 0x9c) * 0x100 + _g_land_tiles);
    pAVar17 = (ArmyUnit_0x164_plus *)
              ((g_testroad_target_x + g_testroad_target_y * 0x9c) * 0x100 + _g_land_tiles);
    break;
  case 2:
    army = (ArmyUnit_0x164_plus *)
           ((g_testroad_start_x + g_testroad_start_y * 0x4e) * 0x100 + _g_land_tiles);
    pAVar17 = (ArmyUnit_0x164_plus *)
              ((g_testroad_target_x + g_testroad_target_y * 0x4e) * 0x100 + _g_land_tiles);
    break;
  case 3:
    army = (ArmyUnit_0x164_plus *)
           ((g_testroad_start_y * 0x27 + g_testroad_start_x) * 0x100 + _g_land_tiles);
    pAVar17 = (ArmyUnit_0x164_plus *)
              ((g_testroad_target_y * 0x27 + g_testroad_target_x) * 0x100 + _g_land_tiles);
  }
  g_testroad_start_land_index = (int)*(short *)&army->field_0x10;
  g_testroad_target_land_index = (int)*(short *)&pAVar17->field_0x10;
  g_testroad_start_route_marker = (int)(char)army->field_0x12;
  g_testroad_target_route_marker = (int)(char)pAVar17->field_0x12;
  g_testroad_army_type = g_army_type_table + g_testroad_army->army_type_id;
  iVar9 = g_army_type_table[g_testroad_army->army_type_id].unit_class;
  g_testroad_long_sea_route_flag = 0;
  iVar15 = g_testroad_army->cargo_or_subunit_count + 1;
  if (((iVar9 == 1) && (g_testroad_start_land_index < 0)) &&
     ((g_testroad_target_land_index < 0 &&
      (iVar4 = Tile_Distance_With_Wrap
                         (g_testroad_start_x,g_testroad_start_y,g_testroad_target_x,
                          g_testroad_target_y,(byte *)0x0), 0x1e < iVar4)))) {
    g_testroad_long_sea_route_flag = 1;
  }
  FUN_0049b5e0();
  local_4 = 0;
  g_testroad_adjacent_attack_possible = 0;
  switch(iVar9) {
  case 0:
    if (DAT_005d8f90 == 0) {
      if (_DAT_00748f30 != 5) {
        if ((g_testroad_start_land_index == g_testroad_target_land_index) ||
           (g_testroad_army->mission_action_id == 0x20)) {
switchD_004d3107_default:
          if ((((_DAT_00748f30 != 5) && (_DAT_00748f30 != 2)) &&
              ((*(byte *)((int)&pAVar17->target_tile_y_or_anim_y + 1) ==
                g_testroad_army->owner_country_id ||
               (*(byte *)((int)&pAVar17->next_path_step_x + 1) == g_testroad_army->owner_country_id)
               ))) && ((iVar4 = (int)(char)pAVar17->field_0x7c + (int)(char)pAVar17->field_0x50,
                       iVar4 == 10 || (10 < iVar4 + iVar15)))) {
            g_testroad_target_reached_or_blocked._0_1_ = 1;
            cVar2 = FUN_0048d3f0(3);
            if (cVar2 == '\0') {
              g_testroad_army->active_anim_step_count = 0;
              goto LAB_004d30d6;
            }
            switch(g_map_size_mode) {
            case 0:
              iVar15 = g_testroad_target_x + g_testroad_target_y * 0x138;
              break;
            case 1:
              iVar15 = g_testroad_target_x + g_testroad_target_y * 0x9c;
              break;
            case 2:
              iVar15 = g_testroad_target_x + g_testroad_target_y * 0x4e;
              break;
            case 3:
              iVar15 = g_testroad_target_y * 0x27 + g_testroad_target_x;
              break;
            default:
              goto switchD_004d31ee_default;
            }
            pAVar17 = (ArmyUnit_0x164_plus *)(iVar15 * 0x100 + _g_land_tiles);
          }
          goto switchD_004d31ee_default;
        }
        if (('\0' < (char)pAVar17->field_0x50) &&
           (((*(byte *)((int)&pAVar17->target_tile_y_or_anim_y + 1) ==
              g_testroad_army->owner_country_id ||
             (*(byte *)((int)&pAVar17->next_path_step_x + 1) == g_testroad_army->owner_country_id))
            && (iVar4 = (int)(char)pAVar17->field_0x50,
               (char)pAVar17->field_0x7c + iVar4 + iVar15 < 0xb)))) {
          iVar12 = 0;
          puVar11 = (undefined4 *)&pAVar17->field_0x28;
          do {
            if (iVar4 < 1) break;
            pbVar19 = (byte *)*puVar11;
            if (pbVar19 != (byte *)0x0) {
              if ((0 < g_army_type_table[*pbVar19].transport_capacity) &&
                 ((int)((uint)pbVar19[0x148] + iVar15) <=
                  g_army_type_table[*pbVar19].transport_capacity)) goto switchD_004d3107_default;
              iVar4 = iVar4 + -1;
            }
            iVar12 = iVar12 + 1;
            puVar11 = puVar11 + 1;
          } while (iVar12 < 10);
        }
        if (((g_testroad_target_land_index < 0) &&
            (1 < g_testroad_army_type->attack_farthest_preference)) &&
           (('\0' < (char)pAVar17->field_0x50 &&
            (*(byte *)((int)&pAVar17->target_tile_y_or_anim_y + 1) !=
             g_testroad_army->owner_country_id)))) {
          iVar4 = Tile_Distance_With_Wrap
                            (g_testroad_start_x,g_testroad_start_y,g_testroad_target_x,
                             g_testroad_target_y,(byte *)0x0);
          if (iVar4 == 1) {
            iVar4 = (int)(char)pAVar17->field_0x50;
            iVar12 = 0;
            puVar11 = (undefined4 *)&pAVar17->field_0x28;
            do {
              if (iVar4 < 1) goto LAB_004d30ac;
              if (g_testroad_adjacent_attack_possible != 0) goto switchD_004d3107_default;
              if ((byte *)*puVar11 != (byte *)0x0) {
                if ((&g_testroad_army_type->attack_target_mask)
                    [g_army_type_table[*(byte *)*puVar11].unit_class] != 0) {
                  g_testroad_adjacent_attack_possible = 1;
                  goto switchD_004d3107_default;
                }
                iVar4 = iVar4 + -1;
              }
              iVar12 = iVar12 + 1;
              puVar11 = puVar11 + 1;
            } while (iVar12 < 10);
          }
          else {
LAB_004d30ac:
            if (g_testroad_adjacent_attack_possible != 0) goto switchD_004d3107_default;
          }
        }
        g_testroad_target_reached_or_blocked._0_1_ = 1;
        cVar2 = FUN_0048d3f0(99);
        if (cVar2 != '\0') {
          switch(g_map_size_mode) {
          case 0:
            iVar4 = g_testroad_target_x + g_testroad_target_y * 0x138;
            break;
          case 1:
            iVar4 = g_testroad_target_x + g_testroad_target_y * 0x9c;
            break;
          case 2:
            iVar4 = g_testroad_target_x + g_testroad_target_y * 0x4e;
            break;
          case 3:
            iVar4 = g_testroad_target_y * 0x27 + g_testroad_target_x;
            break;
          default:
            goto switchD_004d3107_default;
          }
          pAVar17 = (ArmyUnit_0x164_plus *)(iVar4 * 0x100 + _g_land_tiles);
          goto switchD_004d3107_default;
        }
LAB_004d30c9:
        g_testroad_army->active_anim_step_count = 0;
LAB_004d30d6:
        local_4 = 0xffffffff;
        thunk_FUN_0049b600();
        ExceptionList = local_c;
        return -1;
      }
switchD_004d31ee_default:
      if (('\0' < (char)pAVar17->field_0x8) &&
         ((&g_testroad_army_type->border_influence_or_visibility_mask)[(char)pAVar17->field_0x8] ==
          0)) {
        g_testroad_target_reached_or_blocked._0_1_ = 1;
        cVar2 = FUN_0048d5d0(99);
        if (cVar2 == '\0') {
          g_testroad_army->active_anim_step_count = 0;
          goto LAB_004d30d6;
        }
        switch(g_map_size_mode) {
        case 0:
          iVar15 = g_testroad_target_x + g_testroad_target_y * 0x138;
          break;
        case 1:
          iVar15 = g_testroad_target_x + g_testroad_target_y * 0x9c;
          break;
        case 2:
          iVar15 = g_testroad_target_x + g_testroad_target_y * 0x4e;
          break;
        case 3:
          iVar15 = g_testroad_target_y * 0x27 + g_testroad_target_x;
          break;
        default:
          goto switchD_004d32af_default;
        }
        pAVar17 = (ArmyUnit_0x164_plus *)(iVar15 * 0x100 + _g_land_tiles);
      }
switchD_004d32af_default:
      if ((((_DAT_00748f30 != 5) && (g_testroad_army_type->attack_stat_a == 0)) &&
          (g_testroad_army_type->attack_stat_b == 0)) && (g_testroad_army_type->attack_stat_c == 0))
      {
        bVar13 = *(byte *)((int)&pAVar17->target_tile_y_or_anim_y + 1);
        if (((bVar13 != g_testroad_army->owner_country_id) && ('\0' < (char)pAVar17->field_0x50)) &&
           ('\0' < (char)bVar13)) {
          bVar13 = 0xff;
          iVar15 = 0;
          piVar16 = (int *)&pAVar17->field_0x28;
          do {
            if (*piVar16 != 0) {
              bVar13 = *(byte *)(*piVar16 + 1);
              break;
            }
            iVar15 = iVar15 + 1;
            piVar16 = piVar16 + 1;
          } while (iVar15 < 10);
          if (bVar13 != g_testroad_army->owner_country_id) {
            g_testroad_target_reached_or_blocked._0_1_ = 1;
            goto LAB_004d30c9;
          }
        }
      }
    }
    break;
  case 1:
    if ((*(int *)&army->field_0x88 != 0) ||
       ((g_testroad_army->owner_country_id == 0 && ('\0' < (char)army->field_0xb3)))) {
      local_4c = 8;
      iVar15 = (g_testroad_start_y & 1U) << 5;
      pAVar5 = army;
      do {
        iVar4 = *(int *)((int)g_hex_neighbor_delta_x_by_parity + iVar15) + g_testroad_start_x;
        iVar12 = *(int *)((int)g_hex_neighbor_delta_y_by_parity + iVar15) + g_testroad_start_y;
        if (((-1 < iVar12) && (iVar12 < g_map_height_tiles)) &&
           (((-1 < iVar4 && (iVar4 < g_map_width_tiles)) ||
            (g_current_map_scenario_info.horizontal_wrap_setting == 1)))) {
          if (iVar4 < 0) {
            iVar4 = iVar4 + g_map_width_tiles;
          }
          if (g_map_width_tiles <= iVar4) {
            iVar4 = iVar4 - g_map_width_tiles;
          }
          switch(g_map_size_mode) {
          case 0:
            iVar4 = iVar4 + iVar12 * 0x138;
            break;
          case 1:
            iVar4 = iVar4 + iVar12 * 0x9c;
            break;
          case 2:
            iVar4 = iVar4 + iVar12 * 0x4e;
            break;
          case 3:
            iVar4 = iVar12 * 0x27 + iVar4;
            break;
          default:
            goto switchD_004d34fc_default;
          }
          pAVar5 = (ArmyUnit_0x164_plus *)(iVar4 * 0x100 + _g_land_tiles);
switchD_004d34fc_default:
          if (*(short *)&pAVar5->field_0x10 < 0) {
            g_testroad_start_land_index = (int)*(short *)&pAVar5->field_0x10;
          }
          if ((char)pAVar5->field_0x12 < '\0') {
            g_testroad_start_route_marker = (int)(char)pAVar5->field_0x12;
          }
        }
        iVar15 = iVar15 + 4;
        local_4c = local_4c + -1;
      } while (local_4c != 0);
    }
    if ((0 < g_testroad_target_land_index) &&
       ((g_testroad_target_route_marker == 0 ||
        ((g_testroad_target_route_marker != g_testroad_start_route_marker &&
         (g_testroad_target_route_marker != g_testroad_start_land_index)))))) {
      if ((*(int *)&pAVar17->field_0x88 != 0) &&
         (*(byte *)((int)&pAVar17->target_tile_y_or_anim_y + 1) == g_testroad_army->owner_country_id
         )) {
        iVar4 = 0;
        iVar15 = (g_testroad_target_y & 1U) << 5;
        pAVar5 = army;
        do {
          iVar14 = *(int *)((int)g_hex_neighbor_delta_x_by_parity + iVar15) + g_testroad_target_x;
          iVar12 = *(int *)((int)g_hex_neighbor_delta_y_by_parity + iVar15) + g_testroad_target_y;
          if (((-1 < iVar12) && (iVar12 < g_map_height_tiles)) &&
             (((-1 < iVar14 && (iVar14 < g_map_width_tiles)) ||
              (g_current_map_scenario_info.horizontal_wrap_setting == 1)))) {
            if (iVar14 < 0) {
              iVar14 = iVar14 + g_map_width_tiles;
            }
            if (g_map_width_tiles <= iVar14) {
              iVar14 = iVar14 - g_map_width_tiles;
            }
            switch(g_map_size_mode) {
            case 0:
              pAVar5 = (ArmyUnit_0x164_plus *)((iVar14 + iVar12 * 0x138) * 0x100 + _g_land_tiles);
              break;
            case 1:
              pAVar5 = (ArmyUnit_0x164_plus *)((iVar14 + iVar12 * 0x9c) * 0x100 + _g_land_tiles);
              break;
            case 2:
              pAVar5 = (ArmyUnit_0x164_plus *)((iVar14 + iVar12 * 0x4e) * 0x100 + _g_land_tiles);
              break;
            case 3:
              pAVar5 = (ArmyUnit_0x164_plus *)((iVar12 * 0x27 + iVar14) * 0x100 + _g_land_tiles);
            }
            if (((g_testroad_start_land_index < 0) &&
                ((*(short *)&pAVar5->field_0x10 == g_testroad_start_land_index ||
                 ((char)pAVar5->field_0x12 == g_testroad_start_land_index)))) ||
               ((g_testroad_start_route_marker < 0 &&
                ((*(short *)&pAVar5->field_0x10 == g_testroad_start_route_marker ||
                 ((char)pAVar5->field_0x12 == g_testroad_start_route_marker))))))
            goto switchD_004d2f29_default;
          }
          iVar4 = iVar4 + 1;
          iVar15 = iVar15 + 4;
        } while (iVar4 < 8);
      }
      if (((0 < g_testroad_army_type->attack_stat_a) && ('\0' < (char)pAVar17->field_0x50)) &&
         (*(byte *)((int)&pAVar17->next_path_step_x + 1) != g_testroad_army->owner_country_id)) {
        iVar4 = 0;
        iVar15 = (g_testroad_target_y & 1U) << 5;
        pAVar17 = army;
        do {
          iVar12 = *(int *)((int)g_hex_neighbor_delta_x_by_parity + iVar15) + g_testroad_target_x;
          iVar14 = *(int *)((int)g_hex_neighbor_delta_y_by_parity + iVar15) + g_testroad_target_y;
          if (((-1 < iVar14) && (iVar14 < g_map_height_tiles)) &&
             (((-1 < iVar12 && (iVar12 < g_map_width_tiles)) ||
              (g_current_map_scenario_info.horizontal_wrap_setting == 1)))) {
            if (iVar12 < 0) {
              iVar12 = iVar12 + g_map_width_tiles;
            }
            if (g_map_width_tiles <= iVar12) {
              iVar12 = iVar12 - g_map_width_tiles;
            }
            switch(g_map_size_mode) {
            case 0:
              iVar12 = iVar12 + iVar14 * 0x138;
              break;
            case 1:
              iVar12 = iVar12 + iVar14 * 0x9c;
              break;
            case 2:
              iVar12 = iVar12 + iVar14 * 0x4e;
              break;
            case 3:
              iVar12 = iVar14 * 0x27 + iVar12;
              break;
            default:
              goto switchD_004d37a2_default;
            }
            pAVar17 = (ArmyUnit_0x164_plus *)(iVar12 * 0x100 + _g_land_tiles);
switchD_004d37a2_default:
            if ((((g_testroad_start_land_index < 0) || (*(int *)&army->field_0x88 != 0)) &&
                ((*(short *)&pAVar17->field_0x10 == g_testroad_start_land_index ||
                 ((char)pAVar17->field_0x12 == g_testroad_start_land_index)))) ||
               ((g_testroad_start_route_marker < 0 &&
                ((*(short *)&pAVar17->field_0x10 == g_testroad_start_route_marker ||
                 ((char)pAVar17->field_0x12 == g_testroad_start_route_marker))))))
            goto switchD_004d2f29_default;
          }
          iVar4 = iVar4 + 1;
          iVar15 = iVar15 + 4;
        } while (iVar4 < 8);
      }
      g_testroad_target_reached_or_blocked._0_1_ = 1;
      cVar2 = FUN_0048d7b0(99);
      if (cVar2 == '\0') {
        g_testroad_army->active_anim_step_count = 0;
        goto LAB_004d30d6;
      }
    }
    break;
  case 2:
    break;
  case 3:
    if ((g_testroad_start_land_index != g_testroad_target_land_index) &&
       (g_testroad_army->mission_action_id != 0x20)) {
      g_testroad_target_reached_or_blocked._0_1_ = 1;
      cVar2 = FUN_0048d3f0(100);
      if (cVar2 == '\0') {
        g_testroad_army->active_anim_step_count = 0;
        goto LAB_004d30d6;
      }
      switch(g_map_size_mode) {
      case 0:
        iVar15 = g_testroad_target_x + g_testroad_target_y * 0x138;
        break;
      case 1:
        iVar15 = g_testroad_target_x + g_testroad_target_y * 0x9c;
        break;
      case 2:
        iVar15 = g_testroad_target_x + g_testroad_target_y * 0x4e;
        break;
      case 3:
        iVar15 = g_testroad_target_y * 0x27 + g_testroad_target_x;
        break;
      default:
        goto switchD_004d38dc_default;
      }
      pAVar17 = (ArmyUnit_0x164_plus *)(iVar15 * 0x100 + _g_land_tiles);
    }
switchD_004d38dc_default:
    if (('\0' < (char)pAVar17->field_0x8) &&
       ((&g_testroad_army_type->border_influence_or_visibility_mask)[(char)pAVar17->field_0x8] == 0)
       ) {
      g_testroad_target_reached_or_blocked._0_1_ = 1;
      cVar2 = FUN_0048d5d0(100);
      if (cVar2 == '\0') {
        g_testroad_army->active_anim_step_count = 0;
        goto LAB_004d30d6;
      }
    }
  }
switchD_004d2f29_default:
  g_testroad_tick_after_rules = Get_Game_Tick();
  if ((DAT_005d8f90 < 1) &&
     ((((char)g_testroad_army->owner_country_id != g_human_country_index ||
       (g_testroad_army != DAT_007584dc)) || (g_auto_turn_or_ai_control_flag != 0)))) {
    uVar6 = 0;
  }
  else {
    uVar6 = 1;
  }
  iVar15 = FUN_0049b660(g_testroad_start_x,g_testroad_start_y,g_testroad_target_x,
                        g_testroad_target_y,uVar6);
  if (iVar15 < 1) {
    thunk_FUN_0049b600();
    g_testroad_army->active_anim_step_count = 0;
  }
  else {
    if (local_1c == 0) {
      g_testroad_army->active_anim_step_count = 0;
    }
    else {
      iVar15 = 0;
      local_54 = 0;
      piVar16 = (int *)0x0;
      do {
        iVar4 = local_54;
        piVar7 = (int *)((int)g_bestpath_temp_buffer + iVar15);
        iVar15 = iVar15 + 0x10;
        local_54 = iVar4 + 1;
        *piVar7 = (int)*(short *)(local_1c + 0xc);
        piVar7[1] = (int)*(short *)(local_1c + 0xe);
        piVar7[2] = *(int *)(local_1c + 4);
        piVar7[3] = (int)piVar16;
        local_1c = *(int *)(local_1c + 0x18);
        if (iVar15 == 0x1f50) break;
        piVar16 = piVar7;
      } while (local_1c != 0);
      bVar1 = false;
      if (piVar7 == (int *)0x0) {
        local_54 = -1;
      }
      else if ((g_testroad_start_x == *piVar7) && (g_testroad_start_y == piVar7[1])) {
        piVar7 = (int *)piVar7[3];
        bVar1 = true;
        local_54 = iVar4;
      }
      psVar10 = &g_testroad_army->next_path_step_x;
      for (iVar15 = 0x19; iVar15 != 0; iVar15 = iVar15 + -1) {
        *(undefined4 *)psVar10 = 0xffffffff;
        psVar10 = psVar10 + 2;
      }
      psVar10 = &g_testroad_army->next_path_step_y;
      for (iVar15 = 0x19; iVar15 != 0; iVar15 = iVar15 + -1) {
        *(undefined4 *)psVar10 = 0xffffffff;
        psVar10 = psVar10 + 2;
      }
      pbVar19 = g_testroad_army->path_step_turn_cost;
      for (iVar15 = 0xc; iVar15 != 0; iVar15 = iVar15 + -1) {
        pbVar19[0] = 0xff;
        pbVar19[1] = 0xff;
        pbVar19[2] = 0xff;
        pbVar19[3] = 0xff;
        pbVar19 = pbVar19 + 4;
      }
      pbVar19[0] = 0xff;
      pbVar19[1] = 0xff;
      if (bVar1) {
        army = (ArmyUnit_0x164_plus *)0x1;
        iVar15 = (int)g_testroad_army->movement_points_remaining;
        if (0x32 < local_54) {
          local_54 = 0x32;
        }
        iVar4 = 0;
        if (0 < local_54) {
          pcVar8 = (char *)0x1;
          local_4c = 0x8a;
          do {
            *(short *)(local_4c + -100 + (int)g_testroad_army) = (short)*piVar7;
            *(short *)(&g_testroad_army->army_type_id + local_4c) = (short)piVar7[1];
            g_testroad_army->path_step_turn_cost[iVar4] = 0;
            iVar12 = 1;
            if (iVar9 == 0) {
              if (_DAT_00748f30 == 4) {
                iVar12 = 9;
                goto LAB_004d3c22;
              }
              switch(g_map_size_mode) {
              case 0:
                iVar12 = *piVar7 + piVar7[1] * 0x138;
                break;
              case 1:
                iVar12 = *piVar7 + piVar7[1] * 0x9c;
                break;
              case 2:
                iVar12 = *piVar7 + piVar7[1] * 0x4e;
                break;
              case 3:
                iVar12 = piVar7[1] * 0x27 + *piVar7;
                break;
              default:
                goto switchD_004d3b5e_default;
              }
              pcVar8 = (char *)(iVar12 * 0x100 + _g_land_tiles);
switchD_004d3b5e_default:
              if (pcVar8[0x24] < '\0') {
                if (pcVar8[0x15] < '\0') {
                  if (pcVar8[0x13] < '\0') {
                    if (pcVar8[8] == '\0') {
                      iVar12 = *(int *)(&DAT_005cba40 + *pcVar8 * 4);
                      if (iVar12 < 0) {
                        iVar12 = *(int *)(&DAT_005cba40 + pcVar8[2] * 4);
                      }
                    }
                    else {
                      iVar12 = *(int *)(&DAT_005cba78 + pcVar8[8] * 4);
                    }
                  }
                  else if (pcVar8[0x14] == '\x02') {
                    iVar12 = 1;
                  }
                  else {
                    iVar12 = (pcVar8[0x14] != '\x01') + 2;
                  }
                }
                else {
                  iVar12 = 2;
                }
              }
              else {
                iVar12 = 3;
              }
            }
LAB_004d3c22:
            if (iVar15 < iVar12) {
              do {
                iVar15 = iVar15 + g_testroad_army_type->movement_or_speed *
                                  g_current_map_scenario_info.movement_base;
                army = (ArmyUnit_0x164_plus *)&army->owner_country_id;
              } while (iVar15 < iVar12);
            }
            if ((0x8a < local_4c) &&
               (army == (ArmyUnit_0x164_plus *)
                        (int)(char)g_testroad_army->path_step_turn_cost[iVar4 + -1])) {
              g_testroad_army->path_step_turn_cost[iVar4 + -1] = 0;
            }
            iVar15 = iVar15 - iVar12;
            g_testroad_army->path_step_turn_cost[iVar4] = (byte)army;
            piVar7 = (int *)piVar7[3];
            iVar4 = iVar4 + 1;
            local_4c = local_4c + 2;
          } while (iVar4 < local_54);
        }
      }
      else {
        local_54 = 0;
      }
      g_testroad_army->active_anim_step_count = (byte)local_54;
      if ((0 < local_54) &&
         (((&g_testroad_army->target_tile_y_or_anim_y)[local_54] != g_testroad_target_x ||
          (*(short *)(g_testroad_army->path_step_turn_cost + local_54 * 2 + -0x66) !=
           g_testroad_target_y)))) {
        if (g_testroad_army->path_replan_stall_counter == 0) {
          g_testroad_army->path_replan_origin_x = (short)g_testroad_start_x;
          g_testroad_army->path_replan_origin_y = (short)g_testroad_start_y;
        }
        g_testroad_army->path_replan_stall_counter = g_testroad_army->path_replan_stall_counter + 1;
        if ('\x02' < (char)g_testroad_army->path_replan_stall_counter) {
          iVar9 = Tile_Distance_With_Wrap
                            (g_testroad_target_x,g_testroad_target_y,
                             (int)g_testroad_army->path_replan_origin_x,
                             (int)g_testroad_army->path_replan_origin_y,(byte *)0x0);
          iVar15 = Tile_Distance_With_Wrap
                             (g_testroad_target_x,g_testroad_target_y,
                              (int)(&g_testroad_army->target_tile_y_or_anim_y)[local_54],
                              (int)*(short *)(g_testroad_army->path_step_turn_cost +
                                             local_54 * 2 + -0x66),(byte *)0x0);
          if (iVar9 < iVar15) {
            g_testroad_army->path_replan_stall_counter = 0;
            g_testroad_army->active_anim_step_count = 0;
            thunk_FUN_0049b600();
            local_4 = 0xffffffff;
            thunk_FUN_0049b600();
            ExceptionList = local_c;
            return -2;
          }
          g_testroad_army->path_replan_stall_counter = 3;
        }
      }
      iVar15 = (int)(char)g_testroad_army->active_anim_step_count;
      iVar9 = 0;
      bVar1 = false;
      if (iVar15 < 1) {
LAB_004d3e3c:
        iVar9 = 0;
        if (0 < iVar15) {
          psVar10 = &g_testroad_army->next_path_step_y;
          do {
            if (bVar1) goto LAB_004d3f35;
            iVar4 = 0;
            if (0 < iVar15) {
              psVar18 = &g_testroad_army->next_path_step_y;
              do {
                if (bVar1) break;
                if (((iVar4 != iVar9) && (psVar10[-0x32] == psVar18[-0x32])) &&
                   (*psVar10 == *psVar18)) {
                  bVar1 = true;
                }
                iVar4 = iVar4 + 1;
                psVar18 = psVar18 + 1;
              } while (iVar4 < iVar15);
            }
            iVar9 = iVar9 + 1;
            psVar10 = psVar10 + 1;
          } while (iVar9 < iVar15);
          if (bVar1) goto LAB_004d3f35;
        }
        if (0 < local_54) {
          iVar15 = (int)g_testroad_army->next_path_step_y;
          iVar4 = (int)g_testroad_army->next_path_step_x;
          iVar9 = Tile_Distance_With_Wrap
                            (iVar4,iVar15,(int)g_testroad_army->tile_x,(int)g_testroad_army->tile_y,
                             (byte *)0x0);
          if (1 < iVar9) goto LAB_004d3f44;
          iVar9 = 1;
          if ('\x01' < (char)g_testroad_army->active_anim_step_count) {
            iVar12 = 0x8c;
            do {
              if (bVar1) break;
              iVar15 = Tile_Distance_With_Wrap
                                 (iVar4,iVar15,(int)*(short *)(iVar12 + -100 + (int)g_testroad_army)
                                  ,(int)*(short *)(&g_testroad_army->army_type_id + iVar12),
                                  (byte *)0x0);
              if (1 < iVar15) {
                bVar1 = true;
              }
              iVar9 = iVar9 + 1;
              iVar4 = (int)*(short *)(iVar12 + -100 + (int)g_testroad_army);
              iVar15 = (int)*(short *)(&g_testroad_army->army_type_id + iVar12);
              iVar12 = iVar12 + 2;
            } while (iVar9 < (char)g_testroad_army->active_anim_step_count);
            goto LAB_004d3f35;
          }
        }
      }
      else {
        psVar10 = &g_testroad_army->next_path_step_y;
        do {
          if (bVar1) goto LAB_004d3f35;
          if ((g_testroad_army->tile_x == psVar10[-0x32]) && (g_testroad_army->tile_y == *psVar10))
          {
            bVar1 = true;
          }
          iVar9 = iVar9 + 1;
          psVar10 = psVar10 + 1;
        } while (iVar9 < iVar15);
        if (!bVar1) goto LAB_004d3e3c;
LAB_004d3f35:
        if (bVar1) {
LAB_004d3f44:
          psVar10 = &g_testroad_army->next_path_step_x;
          for (iVar3 = 0x19; iVar3 != 0; iVar3 = iVar3 + -1) {
            *(undefined4 *)psVar10 = 0xffffffff;
            psVar10 = psVar10 + 2;
          }
          psVar10 = &g_testroad_army->next_path_step_y;
          for (iVar3 = 0x19; iVar3 != 0; iVar3 = iVar3 + -1) {
            *(undefined4 *)psVar10 = 0xffffffff;
            psVar10 = psVar10 + 2;
          }
          g_testroad_army->active_anim_step_count = 0;
          thunk_FUN_0049b600();
          goto LAB_004d3f7c;
        }
      }
    }
    thunk_FUN_0049b600();
  }
  if (DAT_00755960 != 0) {
    iVar9 = Get_Game_Tick();
    DAT_00706858 = DAT_00706858 + (iVar9 - iVar3);
    if (0x31 < (uint)(iVar9 - iVar3)) {
LAB_004d3f7c:
      local_4 = 0xffffffff;
      thunk_FUN_0049b600();
      ExceptionList = local_c;
      return -3;
    }
  }
  local_4 = 0xffffffff;
  thunk_FUN_0049b600();
  ExceptionList = local_c;
  return 1;
}
