/*
 * Generated by Ghidra headless decompiler from China2EX_fontfix8.exe.
 * Address request: 0x0041daf0
 * This is reconstructed pseudocode, not original source.
 */


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void UserSet_City_Resource(uint param_1)

{
  char cVar1;
  int iVar2;
  uint uVar3;
  int iVar4;
  int iVar5;
  int iVar6;
  char *pcVar7;
  int local_1c;
  int local_18;
  int local_14;
  int local_10;
  int local_c;
  int local_8;
  int local_4;
  
  iVar2 = param_1;
  Trace_Function(s_UserSet_City_Resource_00515160);
  param_1 = 0;
  local_4 = (int)*(char *)(iVar2 + 1);
  if ((local_4 != 0) && (param_1 = *(byte *)(iVar2 + 0x20) + 1, 0x2d < param_1)) {
    param_1 = 0x2d;
  }
  if (*(byte *)(iVar2 + 0x166) < param_1) {
    param_1 = (uint)*(byte *)(iVar2 + 0x166);
  }
  *(undefined1 *)(iVar2 + 0x15f) = (undefined1)param_1;
  if ((*(byte *)(iVar2 + 0x15e) != 0) && (1 < *(byte *)(iVar2 + 0x15e))) {
    pcVar7 = (char *)(iVar2 + 0x132);
    uVar3 = param_1;
    do {
      iVar6 = (int)pcVar7[-0x2d] + (uint)*(ushort *)(iVar2 + 0x16);
      iVar4 = (uint)*(ushort *)(iVar2 + 0x18) + (int)*pcVar7;
      if ((-1 < iVar4) && (iVar4 < g_map_height_tiles)) {
        if ((iVar6 < 0) || (g_map_width_tiles <= iVar6)) {
          if (g_current_map_scenario_info.horizontal_wrap_enabled != 1) goto LAB_0041dc22;
          if (g_map_width_tiles <= iVar6) {
            iVar6 = iVar6 - g_map_width_tiles;
          }
        }
        if (iVar6 < 0) {
          iVar6 = iVar6 + g_map_width_tiles;
        }
        switch(g_map_size_mode) {
        case 0:
          iVar6 = iVar6 + iVar4 * 0x138;
          break;
        case 1:
          iVar6 = iVar6 + iVar4 * 0x9c;
          break;
        case 2:
          iVar6 = iVar6 + iVar4 * 0x4e;
          break;
        case 3:
          iVar6 = iVar4 * 0x27 + iVar6;
          break;
        default:
          goto switchD_0041dbcd_default;
        }
        uVar3 = iVar6 * 0x100 + _g_land_tiles;
switchD_0041dbcd_default:
        if (*(int *)(uVar3 + 0x8c) == iVar2) {
          *(undefined4 *)(uVar3 + 0x8c) = 0;
        }
      }
LAB_0041dc22:
      pcVar7 = pcVar7 + 1;
    } while ((int)(pcVar7 + (-0x131 - iVar2)) < (int)(uint)*(byte *)(iVar2 + 0x15e));
  }
  iVar6 = 0;
  local_8 = 0;
  local_c = 0;
  local_18 = 1;
  uVar3 = param_1;
  if (1 < *(byte *)(iVar2 + 0x15e)) {
    do {
      if ((int)(uint)*(byte *)(iVar2 + 0x15f) <= local_18) break;
      iVar5 = (int)*(char *)(local_18 + 0x104 + iVar2) + (uint)*(ushort *)(iVar2 + 0x16);
      iVar4 = (int)*(char *)(local_18 + 0x131 + iVar2) + (uint)*(ushort *)(iVar2 + 0x18);
      if ((-1 < iVar4) && (iVar4 < g_map_height_tiles)) {
        if ((iVar5 < 0) || (g_map_width_tiles <= iVar5)) {
          if (g_current_map_scenario_info.horizontal_wrap_enabled != 1) goto LAB_0041de3a;
          if (g_map_width_tiles <= iVar5) {
            iVar5 = iVar5 - g_map_width_tiles;
          }
        }
        if (iVar5 < 0) {
          iVar5 = iVar5 + g_map_width_tiles;
        }
        switch(g_map_size_mode) {
        case 0:
          uVar3 = iVar5 + iVar4 * 0x138;
          break;
        case 1:
          uVar3 = iVar5 + iVar4 * 0x9c;
          break;
        case 2:
          uVar3 = iVar5 + iVar4 * 0x4e;
          break;
        case 3:
          uVar3 = iVar4 * 0x27 + iVar5;
        }
        iVar4 = uVar3 * 0x100 + _g_land_tiles;
        if (((('\0' < *(char *)(iVar4 + 0xb5 + local_4)) && (*(char *)(iVar4 + 0x25) == local_4)) &&
            ((*(char *)(iVar4 + 0x27) == local_4 || (*(char *)(iVar4 + 0x27) == -1)))) &&
           ((*(int *)(iVar4 + 0x88) == 0 && (*(int *)(iVar4 + 0x8c) == 0)))) {
          local_14 = 0;
          local_10 = 0;
          local_1c = 0;
          FUN_0041d170(iVar4,&local_14,&local_10,&local_1c,local_4,iVar2);
          if (*(char *)(iVar2 + 0x22) == '\x05') {
            local_1c = local_1c << 1;
          }
          *(char *)(iVar4 + 0xad) = (char)local_1c;
          *(char *)(iVar4 + 0xab) = (char)local_14;
          *(char *)(iVar4 + 0xac) = (char)local_10;
          *(int *)(iVar4 + 0x8c) = iVar2;
          iVar6 = iVar6 + 0x18;
          *(int *)(DAT_0074c84c + -0x10 + iVar6) = local_1c + local_14 * 3 + local_10 * 2;
          *(int *)(DAT_0074c84c + -0xc + iVar6) = local_14;
          *(int *)(DAT_0074c84c + -8 + iVar6) = local_10;
          local_c = local_c + 1;
          *(int *)(DAT_0074c84c + -4 + iVar6) = local_1c;
          cVar1 = *(char *)(iVar4 + 0x1a);
          if ((cVar1 < '\0') || ('\x03' < cVar1)) {
            *(char *)(iVar2 + 0x171) = *(char *)(iVar2 + 0x171) + '\x01';
          }
          else {
            *(char *)(cVar1 + 0x172 + iVar2) = *(char *)(cVar1 + 0x172 + iVar2) + '\x01';
          }
        }
        local_8 = local_8 + 1;
        if ((int)param_1 <= local_8) break;
      }
LAB_0041de3a:
      local_18 = local_18 + 1;
    } while (local_18 < (int)(uint)*(byte *)(iVar2 + 0x15e));
  }
  *(char *)(iVar2 + 0x15e) = (char)local_c + '\x01';
  *(char *)(iVar2 + 0x160) = *(char *)(iVar2 + 0x15f) - ((char)local_c + '\x01');
  return;
}

