# Ghidra headless Jython script.
# Run with:
# analyzeHeadless <project_dir> CHNIII -import China2EX_fontfix8.exe -scriptPath tools/reverse_probe -postScript ghidra_export.py <out_dir>

from __future__ import print_function

import os
import re

from ghidra.app.decompiler import DecompInterface
from ghidra.util.task import ConsoleTaskMonitor


TARGET_FUNCTIONS = {
    0x46D310: "render/init_directdraw_runtime.c",
    0x478EB0: "ui/main_menu_init.c",
    0x479000: "ui/main_menu_quit.c",
    0x479040: "ui/main_menu_putscreen.c",
    0x479420: "ui/main_menu_mouse_left_release.c",
    0x49BEC0: "render/load_tmg_background.c",
    0x4C2DA0: "render/apply_resolution_mode.c",
    0x4F0030: "render/lock_back_surface.c",
    0x4F0070: "render/unlock_back_surface.c",
    0x4F02D0: "render/present_dirty_rects.c",
    0x4F0AFD: "render/set_display_mode_from_mode_table.c",
    0x4F0CE0: "render/create_front_surface.c",
    0x4F0DE0: "render/create_back_surface.c",
    0x4F81E0: "render/init_surface_pixel_state.c",
}

STRING_HINTS = [
    "Battle:",
    "Battle_",
    "City_",
    "City_View",
    "Diplomat",
    "Decode_",
    "Load_Dat",
    "Do_City",
    "Do_Map",
    "MAINMENU",
    "UI_",
]


def mkdirs(path):
    if not os.path.isdir(path):
        os.makedirs(path)


def sanitize_name(name):
    cleaned = re.sub(r"[^A-Za-z0-9_.-]+", "_", name)
    return cleaned[:96] or "unnamed"


def get_string_refs(program, needle):
    listing = program.getListing()
    refs = program.getReferenceManager()
    memory = program.getMemory()
    out = []
    for block in memory.getBlocks():
        if not block.isInitialized():
            continue
        addr = block.getStart()
        end = block.getEnd()
        while addr is not None and addr.compareTo(end) <= 0:
            data = listing.getDataAt(addr)
            if data is not None and data.hasStringValue():
                try:
                    value = str(data.getValue())
                except Exception:
                    value = ""
                if needle in value:
                    for ref in refs.getReferencesTo(addr):
                        out.append((value, ref.getFromAddress()))
            addr = addr.next()
    return out


def decompile_function(ifc, function):
    res = ifc.decompileFunction(function, 90, ConsoleTaskMonitor())
    if res and res.decompileCompleted():
        return res.getDecompiledFunction().getC()
    return None


def write_decomp(ifc, out_root, va, rel_path):
    fm = currentProgram.getFunctionManager()
    addr = currentProgram.getAddressFactory().getDefaultAddressSpace().getAddress(va)
    fn = fm.getFunctionAt(addr)
    if fn is None:
        fn = fm.getFunctionContaining(addr)
    out_path = os.path.join(out_root, rel_path)
    mkdirs(os.path.dirname(out_path))
    with open(out_path, "w") as f:
        f.write("/* Generated by Ghidra headless decompiler from %s.\n" % currentProgram.getName())
        f.write(" * Address request: 0x%08x\n" % va)
        f.write(" * This is reconstructed pseudocode, not original source.\n")
        f.write(" */\n\n")
        if fn is None:
            f.write("/* No Ghidra function found at or containing 0x%08x. */\n" % va)
            return
        c = decompile_function(ifc, fn)
        if c:
            f.write(c)
        else:
            f.write("/* Decompile failed for %s at %s. */\n" % (fn.getName(), fn.getEntryPoint()))


def main():
    args = getScriptArgs()
    if len(args) < 1:
        raise Exception("usage: ghidra_export.py <out_dir>")
    out_root = os.path.abspath(args[0])
    mkdirs(out_root)

    ifc = DecompInterface()
    ifc.openProgram(currentProgram)

    for va, rel_path in sorted(TARGET_FUNCTIONS.items()):
        write_decomp(ifc, out_root, va, rel_path)

    fm = currentProgram.getFunctionManager()
    listing_path = os.path.join(out_root, "function_inventory.md")
    with open(listing_path, "w") as f:
        f.write("# Ghidra Function Inventory\n\n")
        f.write("Generated from `%s`. Addresses use image base `%s`.\n\n" % (
            currentProgram.getName(), currentProgram.getImageBase()))
        f.write("| Address | Name | Size | Call count |\n")
        f.write("|---:|---|---:|---:|\n")
        for fn in fm.getFunctions(True):
            body = fn.getBody()
            call_count = 0
            for _ in fn.getCalledFunctions(ConsoleTaskMonitor()):
                call_count += 1
            f.write("| `0x%s` | `%s` | %d | %d |\n" % (
                fn.getEntryPoint(), fn.getName(), body.getNumAddresses(), call_count))

    refs_path = os.path.join(out_root, "string_xrefs.md")
    with open(refs_path, "w") as f:
        f.write("# String Cross References\n\n")
        f.write("| Hint | String | Referrer | Function |\n")
        f.write("|---|---|---:|---|\n")
        seen = set()
        for hint in STRING_HINTS:
            for value, ref_addr in get_string_refs(currentProgram, hint):
                fn = fm.getFunctionContaining(ref_addr)
                fn_name = fn.getName() if fn else ""
                key = (hint, value, str(ref_addr), fn_name)
                if key in seen:
                    continue
                seen.add(key)
                safe_value = value.replace("|", "\\|").replace("\n", "\\n")
                f.write("| `%s` | `%s` | `0x%s` | `%s` |\n" % (
                    hint, safe_value, ref_addr, fn_name))


main()
