/*
 * Generated by Ghidra headless decompiler from China2EX_fontfix8.exe.
 * Address request: 0x00478b30
 * This is reconstructed pseudocode, not original source.
 */


void Free_EMG_Resource(int *param_1)

{
  Trace_Function(s_Safe_FreeEMG_00575a94);
  if (*param_1 != 0) {
    FUN_004f8c00(param_1);
    *param_1 = 0;
  }
  return;
}

