/*
 * Generated by Ghidra headless decompiler from China2EX_fontfix8.exe.
 * Address request: 0x00478ac0
 * This is reconstructed pseudocode, not original source.
 */


void Load_XMG_Resource(undefined4 param_1,int *param_2)

{
  int iVar1;
  int iVar2;
  undefined1 local_68 [104];

  Format_Text(local_68,s_Safe_LoadXMG____s_00575a80,param_1);
  Trace_Function(local_68);
  if (*param_2 == 0) {
    iVar2 = 0;
    do {
      iVar1 = FUN_004f8c50(param_1,0,0);
      *param_2 = iVar1;
      if (iVar1 != 0) {
        return;
      }
      iVar2 = iVar2 + 1;
    } while (iVar2 < 5);
    FUN_0046a230(s_Safe_LoadXMG__00575a70,param_1);
  }
  return;
}
