/*
 * Generated by Ghidra headless decompiler from China2EX_fontfix8.exe.
 * Address request: 0x00479040
 * This is reconstructed pseudocode, not original source.
 */


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void PutScreen_Mainmenu(void)

{
  char cVar1;
  undefined2 extraout_var;
  int iVar2;
  undefined2 extraout_var_00;
  int iVar3;
  uint uVar4;
  undefined2 extraout_var_01;
  undefined2 extraout_var_02;
  undefined2 uVar5;
  int *piVar6;
  char *pcVar7;
  int iVar8;
  char *pcVar9;
  undefined4 uVar10;
  undefined4 uVar11;
  void *pvVar12;

  Trace_Function(s_PutScreen_Mainmenu_00575f44);
  iVar8 = 0;
  uVar11 = 0;
  uVar10 = 0;
  pvVar12 = g_loaded_tmg_background;
  Draw_Image_To_Backbuffer();
  Font_Select(s_Courier_New_Bold_005745a0,0x18,s_SimSun_005745dc,0x18,uVar10,uVar11,pvVar12);
  uVar5 = extraout_var_01;
  if (DAT_0075593e == '\x01') {
    Draw_Text(0,0x2e5,&DAT_00575f3c,0xffffffff,CONCAT22(extraout_var_00,DAT_007350b4),0xffffffff,
              0xffffffff);
    uVar5 = extraout_var_02;
  }
  Draw_Text(0x2d6,0x2e5,&DAT_00575f20,0xffffffff,CONCAT22(uVar5,DAT_0074c800),0xffffffff,0xffffffff)
  ;
  Draw_Text(0x2d5,0x2e4,&DAT_00575f20,0xffffffff,CONCAT22(extraout_var,_DAT_0074a316),0xffffffff,
            0xffffffff);
  Draw_MainMenu_Number(0x3aa,0x2e9,(double)_DAT_00575b50,1,2,0);
  Draw_MainMenu_Number(0x3c9,0x2e9,(double)_DAT_00575b54,1,2,0);
  Font_Select(s_Courier_New_Bold_005745a0,0x12,s_SimSun_005745dc,0x12);
  if (g_mainmenu_anim_state != 0) {
    if (g_mainmenu_anim_state == 1) {
      piVar6 = &DAT_00575bb4;
      do {
        (*g_draw_sprite_fn)(piVar6[-0x11] + -6,piVar6[-0x10] + -8,
                            *(undefined4 *)(iVar8 + (int)g_mainmenu_sprite_bank));
        iVar2 = *piVar6;
        if ((-1 < iVar2) && (iVar2 < 10)) {
          (*g_draw_sprite_fn)(piVar6[-0x13] + -0x27,piVar6[-0x12] + -0x26,
                              *(undefined4 *)((int)g_mainmenu_sprite_bank + iVar2 * 4 + 0x48));
          iVar2 = *piVar6 + 1;
          *piVar6 = iVar2;
          if (iVar2 == 10) {
            g_mainmenu_intro_completed_count = g_mainmenu_intro_completed_count + 1;
            if (g_mainmenu_intro_completed_count == 9) {
              g_mainmenu_anim_state = 2;
            }
          }
          else if ((iVar2 == 3) && (g_mainmenu_intro_spawn_index < 9)) {
            (&DAT_00575bb4)[g_mainmenu_intro_spawn_index * 0x18] = 0;
            g_mainmenu_intro_spawn_index = g_mainmenu_intro_spawn_index + 1;
          }
        }
        piVar6 = piVar6 + 0x18;
        iVar8 = iVar8 + 4;
      } while ((int)piVar6 < 0x575f14);
      return;
    }
    iVar8 = 0;
    pcVar7 = &DAT_00575b80;
    do {
      if (*(int *)(pcVar7 + -8) != 0) {
        if (g_mainmenu_selected_index == iVar8) {
          (*g_draw_sprite_fn)(*(int *)(pcVar7 + -0x18) + -6,*(int *)(pcVar7 + -0x14) + -8,
                              *(undefined4 *)((int)g_mainmenu_sprite_bank + iVar8 * 4 + 0x24));
          Font_Select(0,0x12,0,0x12);
          uVar4 = 0xffffffff;
          pcVar9 = pcVar7;
          do {
            if (uVar4 == 0) break;
            uVar4 = uVar4 - 1;
            cVar1 = *pcVar9;
            pcVar9 = pcVar9 + 1;
          } while (cVar1 != '\0');
          Draw_Text_Centered((0x39 - (~uVar4 - 1 >> 1)) * 9,0x277,pcVar7,0xffffffff,DAT_0074c800,
                             0xffffffff,0xffffffff);
          uVar4 = 0xffffffff;
          pcVar9 = pcVar7;
          do {
            if (uVar4 == 0) break;
            uVar4 = uVar4 - 1;
            cVar1 = *pcVar9;
            pcVar9 = pcVar9 + 1;
          } while (cVar1 != '\0');
          Draw_Text_Centered((~uVar4 - 1 >> 1) * -9 + 0x200,0x276,pcVar7,0xffffffff,DAT_00755910,
                             0xffffffff,0xffffffff);
          (*g_draw_sprite_fn)(*(int *)(pcVar7 + -0x18) + -0x27,*(int *)(pcVar7 + -0x14) + -0x26,
                              *(undefined4 *)
                               ((int)g_mainmenu_sprite_bank + g_mainmenu_highlight_frame * 4 + 0x48)
                             );
          g_mainmenu_highlight_frame = g_mainmenu_highlight_frame + 1;
          if (g_mainmenu_highlight_frame == 10) {
            g_mainmenu_highlight_frame = 0;
          }
        }
        else {
          (*g_draw_sprite_fn)(*(int *)(pcVar7 + -0x18) + -6,*(int *)(pcVar7 + -0x14) + -8,
                              *(undefined4 *)((int)g_mainmenu_sprite_bank + iVar8 * 4));
        }
      }
      pcVar7 = pcVar7 + 0x60;
      iVar8 = iVar8 + 1;
      if (0x575edf < (int)pcVar7) {
        return;
      }
    } while( true );
  }
  g_mainmenu_anim_state = 1;
  g_mainmenu_intro_spawn_index = 0;
  g_mainmenu_highlight_frame = 0;
  g_mainmenu_intro_completed_count = 0;
  piVar6 = &DAT_00575b70;
  do {
    (*g_draw_sprite_fn)(*piVar6 + -6,piVar6[1] + -8,
                        *(undefined4 *)(iVar8 + (int)g_mainmenu_sprite_bank));
    if (piVar6[2] == 0) {
      iVar2 = *piVar6;
      if ((iVar2 != piVar6[-2]) || (piVar6[1] != piVar6[-1])) {
        iVar3 = iVar2 - piVar6[-2];
        if (iVar3 < 1) {
          if (iVar3 < 0) {
            if (-0x1f < iVar3) goto LAB_004791c8;
            iVar2 = iVar2 + 0x1e;
            goto LAB_004791ca;
          }
        }
        else {
          if (iVar3 < 0x1f) {
LAB_004791c8:
            iVar2 = iVar2 - iVar3;
          }
          else {
            iVar2 = iVar2 + -0x1e;
          }
LAB_004791ca:
          *piVar6 = iVar2;
        }
        iVar2 = piVar6[1];
        iVar3 = iVar2 - piVar6[-1];
        if (iVar3 < 1) {
          if (iVar3 < 0) {
            if (-0x1f < iVar3) goto LAB_004791f0;
            iVar2 = iVar2 + 0x1e;
            goto LAB_004791f2;
          }
        }
        else {
          if (iVar3 < 0x1f) {
LAB_004791f0:
            iVar2 = iVar2 - iVar3;
          }
          else {
            iVar2 = iVar2 + -0x1e;
          }
LAB_004791f2:
          piVar6[1] = iVar2;
        }
        if ((*piVar6 == piVar6[-2]) && (piVar6[1] == piVar6[-1])) {
          *piVar6 = piVar6[-2];
          piVar6[1] = piVar6[-1];
          piVar6[2] = 1;
        }
        g_mainmenu_anim_state = 0;
      }
    }
    piVar6 = piVar6 + 0x18;
    iVar8 = iVar8 + 4;
    if (0x575ecf < (int)piVar6) {
      return;
    }
  } while( true );
}
